<?php
/**
 * Copyright (c) UNA, Inc - https://una.io
 * MIT License - https://opensource.org/licenses/MIT
 *
 * System language strings added or changed in 15.0.0.RC1 (Studio dashboard, launcher, audit, queues). Applied by the
 * upgrader's language step (BxDolUpgradeUtil::executeLangsAdd): new keys are added, existing ones get the new text.
 */

$aLangContent = array(
    '_adm_dbd_txt_ver_installed' => 'First Installed',
    '_adm_dbd_txt_ver_updated' => 'Last Updated',
    '_adm_dbd_txt_ver_applied' => 'Installed {0}',
    '_adm_dbd_txt_ver_latest_stable' => 'Latest Stable',
    '_adm_dbd_txt_ver_latest_beta' => 'Latest Beta',
    '_adm_dbd_txt_ver_apps_count' => '{0} Apps',
    '_adm_dbd_txt_ver_apps_updates' => 'Updates: {0}',
    '_adm_dbd_txt_ver_up_to_date' => 'Up to date',
    '_adm_dbd_txt_ver_check' => 'Check for updates',
    '_adm_dbd_txt_ver_checking' => 'Checking...',
    '_adm_dbd_txt_ver_auto' => 'Automatic Updates',
    '_adm_dbd_txt_ver_beta' => 'Beta Updates',
    '_adm_dbd_txt_ver_force' => 'Force Automatic Updates',
    '_adm_dbd_txt_su_local' => 'Local Storage',
    '_adm_dbd_txt_su_remote' => 'Remote Storage',
    '_adm_dbd_txt_su_remote_off' => 'Not connected',
    '_adm_dbd_txt_su_files' => 'Files',
    '_adm_dbd_txt_su_images' => 'Images',
    '_adm_dbd_txt_su_files_count' => '{0} files',
    '_adm_dbd_txt_su_file_count_1' => '1 file',
    '_adm_dbd_txt_chart_used' => '{0} used',
    '_adm_dbd_txt_chart_total' => '{0} total',
    '_adm_dbd_txt_ht_tools' => 'Server tools',
    '_adm_dbd_txt_ht_status' => 'Status',
    '_adm_dbd_txt_ht_audit' => 'Audit',
    '_adm_dbd_txt_ht_permissions' => 'Permissions',
    '_adm_dbd_txt_ht_cpu' => 'CPU',
    '_adm_dbd_txt_ht_memory' => 'Memory',
    '_adm_dbd_txt_ht_disk' => 'Disk',
    '_adm_dbd_txt_ht_network' => 'Network',
    '_adm_dbd_txt_ht_kbps' => 'kbps',
    '_adm_dbd_txt_ht_mbps' => 'Mbps',
    '_adm_dbd_txt_ht_gbps' => 'Gbps',
    '_adm_dbd_txt_ht_na' => 'n/a',
    '_adm_dbd_txt_ht_high' => 'high',
    '_adm_dbd_txt_ht_system' => 'System',
    '_adm_dbd_txt_ht_services' => 'Services',
    '_adm_dbd_txt_ht_caching' => 'Caching',
    '_adm_dbd_txt_ht_security' => 'Security',
    '_adm_dbd_txt_ht_last_audit' => 'Last Audit',
    '_adm_dbd_txt_ht_run_audit' => 'Run new audit',
    '_adm_dbd_txt_ht_passed' => '{0} passed',
    '_adm_dbd_txt_ht_warning' => '1 warning',
    '_adm_dbd_txt_ht_warnings' => '{0} warnings',
    '_adm_dbd_txt_ht_failed' => '{0} failed',
    '_adm_dbd_txt_ht_unknown' => '{0} unknown',
    '_adm_dbd_txt_c_all' => 'All Caches',
    '_adm_dbd_txt_q_all' => 'All Queues',
    '_adm_dbd_txt_q_clear_all' => 'Clear all queues',
    '_adm_dbd_txt_q_clear_item' => 'Clear {0} queue',
    '_adm_dbd_txt_q_queued' => '{0} queued',
    '_adm_dbd_txt_q_failed' => '{0} failed',
    '_adm_dbd_msg_q_clean_success' => 'Queue was successfully cleared',
    '_adm_dbd_txt_c_purifier' => 'Purifier',
    '_adm_dbd_txt_c_custom' => 'Custom',
    '_adm_lmi_cpt_etemplates_html' => 'Email Templates',
    '_adm_stg_cpt_option_sys_audit_report' => 'Last server audit report',
    '_adm_str_txt_pv_screenshot' => '{0} screenshot',
    '_adm_strg_txt_images_resize_result' => 'Resized image',
    '_adm_tmi_lbl_search_apps' => 'Search applications',
    '_adm_tmi_lbl_search_clear' => 'Clear search',
    '_adm_txt_launcher_apps' => 'Apps',
    '_adm_txt_launcher_search_empty' => 'No apps match',
    '_adm_txt_launcher_search_matches' => '{0} apps match',
    '_adm_txt_launcher_search_matches_one' => '1 app matches',
    '_adm_txt_widget_action_label' => '{0} for {1}',
    '_adm_txt_widget_move_left' => 'Move {0} left',
    '_adm_txt_widget_move_right' => 'Move {0} right',
    '_adm_txt_widget_moved' => '{0} moved to position {1} of {2}',
    '_adm_txt_icon_image_current' => 'Current icon image',
    '_sys_audit_header_manual_audit' => 'Manual audit',
    '_sys_audit_header_site_optimization' => 'Optimization',
    '_sys_audit_mail_sending' => 'Email delivery',
    '_sys_audit_msg_apache_module_fail' => 'Install {0} for Apache.',
    '_sys_audit_msg_cron_jobs' => 'No run in the last hour: check the crontab entry.',
    '_sys_audit_msg_optimization_fail' => 'Enable it in Settings &gt; Cache.',
    '_sys_audit_msg_optimization_warn' => 'A PHP accelerator would speed up the file cache.',
    '_sys_audit_msg_x_based_cache_engine' => ' ({0})',
    '_sys_audit_msg_ffmpeg' => 'Not found at {0}: video and audio conversion will not work.',
    '_sys_audit_msg_hardware_requirements' => 'Not checked automatically: see the manual audit.',
    '_sys_audit_msg_mail_send_failed' => 'Sending failed.',
    '_sys_audit_msg_mail_sending' => '<span id="bx-sys-adm-audit-test-email"><a href="javascript:void(0);" onclick="bx_sys_adm_audit_test_email()">Send a test email</a></span>',
    '_sys_audit_msg_mail_sent' => 'Test email sent to {0}.',
    '_sys_audit_msg_manual_audit' => 'Some checks need a person. <a target="_blank" href="mailto:team@unacms.com?subject=Server Audit Request">Request a server audit</a>.',
    '_sys_audit_msg_permissions' => 'Details on the <a href="javascript:void(0);" onclick="oBxDolStudioDashboard.permissions()">Permissions</a> tab.',
    '_sys_audit_msg_php_accelerator_missing' => 'Install a PHP accelerator such as OPcache for a large speed-up.',
    '_sys_audit_msg_php_setup_inefficient' => 'CGI is slow: switch to mod_php, DSO or FastCGI. <a href="javascript:void(0)" onclick="bx_sys_adm_audit_phpinfo()">Open phpinfo</a>.',
    '_sys_audit_msg_userside_caching' => '<a href="{0}" target="_blank">Check in PageSpeed</a>',
    '_sys_audit_msg_value_checking_failed' => 'Could not be checked.',
    '_sys_audit_msg_version_is_incompatible' => 'Unsupported: UNA needs {0} or newer.',
    '_sys_audit_msg_version_is_outdated' => 'Outdated: the latest is {0}.',
    '_sys_audit_permissions' => 'File permissions',
    '_sys_audit_https' => 'HTTPS',
    '_sys_audit_msg_https' => 'Served over plain HTTP: switch the site to HTTPS.',
    '_sys_audit_install_dir' => 'Install directory',
    '_sys_audit_msg_install_dir' => 'Still on the server: remove the install directory.',
    '_sys_audit_display_errors' => 'Error display',
    '_sys_audit_msg_display_errors' => 'PHP shows errors to visitors: set display_errors = Off.',
    '_sys_audit_expose_php' => 'PHP version header',
    '_sys_audit_msg_expose_php' => 'The PHP version is sent in response headers: set expose_php = Off.',
    '_sys_audit_config_file' => 'Configuration file',
    '_sys_audit_msg_config_file' => 'inc/header.inc.php is writable by other users: set it to 0644.',
    '_sys_audit_present' => 'Present',
    '_sys_audit_removed' => 'Removed',
    '_sys_audit_on' => 'On',
    '_sys_audit_off' => 'Off',
    '_sys_audit_php_setup' => 'PHP handler',
    '_sys_audit_section_cache_engines' => 'Cache engines',
    '_sys_audit_section_php_extensions' => 'PHP extensions',
    '_sys_audit_section_webserver' => 'Web server',
    '_sys_audit_serverside_compression' => 'Response compression',
    '_sys_audit_userside_caching' => 'Browser caching',
    '_sys_audit_version' => 'Version',
    '_sys_menu_item_title_system_sa_tour' => 'Introduction Tour',
    '_sys_menu_item_title_sa_tour' => 'Introduction Tour',
    '_sys_page_block_title_std_dash_version' => 'Updates',
    '_sys_page_block_title_std_dash_space' => 'Space',
    '_sys_page_block_title_std_dash_host_tools' => 'Server',
    '_sys_queue_storage' => 'File deletions',
);
