<?php
/**
 * Copyright (c) UNA, Inc - https://una.io
 * MIT License - https://opensource.org/licenses/MIT
 *
 * System language strings added or changed in 15.0.0.RC1 (Studio dashboard, launcher, audit, queues). Applied by the
 * upgrader's language step (BxDolUpgradeUtil::executeLangsAdd): new keys are added, existing ones get the new text.
 */

$aLangContent = array(
    '_adm_dbd_txt_ver_installed' => 'Первая установка',
    '_adm_dbd_txt_ver_updated' => 'Последнее обновление',
    '_adm_dbd_txt_ver_applied' => 'Установлена {0}',
    '_adm_dbd_txt_ver_latest_stable' => 'Последняя стабильная',
    '_adm_dbd_txt_ver_latest_beta' => 'Последняя бета',
    '_adm_dbd_txt_ver_apps_count' => 'Приложения: {0}',
    '_adm_dbd_txt_ver_apps_updates' => 'Обновлений: {0}',
    '_adm_dbd_txt_ver_up_to_date' => 'Актуально',
    '_adm_dbd_txt_ver_check' => 'Проверить обновления',
    '_adm_dbd_txt_ver_checking' => 'Проверка...',
    '_adm_dbd_txt_ver_auto' => 'Автоматические обновления',
    '_adm_dbd_txt_ver_beta' => 'Бета-обновления',
    '_adm_dbd_txt_ver_force' => 'Принудительные автообновления',
    '_adm_dbd_txt_su_local' => 'Локальное хранилище',
    '_adm_dbd_txt_su_remote' => 'Удалённое хранилище',
    '_adm_dbd_txt_su_remote_off' => 'Не подключено',
    '_adm_dbd_txt_su_files' => 'Файлы',
    '_adm_dbd_txt_su_images' => 'Изображения',
    '_adm_dbd_txt_su_files_count' => '{0} файлов',
    '_adm_dbd_txt_su_file_count_1' => '1 файл',
    '_adm_dbd_txt_chart_used' => '{0} занято',
    '_adm_dbd_txt_chart_total' => '{0} всего',
    '_adm_dbd_txt_ht_tools' => 'Инструменты сервера',
    '_adm_dbd_txt_ht_status' => 'Статус',
    '_adm_dbd_txt_ht_audit' => 'Аудит',
    '_adm_dbd_txt_ht_permissions' => 'Права доступа',
    '_adm_dbd_txt_ht_cpu' => 'CPU',
    '_adm_dbd_txt_ht_memory' => 'Память',
    '_adm_dbd_txt_ht_disk' => 'Диск',
    '_adm_dbd_txt_ht_network' => 'Сеть',
    '_adm_dbd_txt_ht_kbps' => 'кбит/с',
    '_adm_dbd_txt_ht_mbps' => 'Мбит/с',
    '_adm_dbd_txt_ht_gbps' => 'Гбит/с',
    '_adm_dbd_txt_ht_na' => 'н/д',
    '_adm_dbd_txt_ht_high' => 'высокая',
    '_adm_dbd_txt_ht_system' => 'Система',
    '_adm_dbd_txt_ht_services' => 'Сервисы',
    '_adm_dbd_txt_ht_caching' => 'Кеширование',
    '_adm_dbd_txt_ht_security' => 'Безопасность',
    '_adm_dbd_txt_ht_last_audit' => 'Последний аудит',
    '_adm_dbd_txt_ht_run_audit' => 'Запустить новый аудит',
    '_adm_dbd_txt_ht_passed' => '{0} пройдено',
    '_adm_dbd_txt_ht_warning' => '1 предупреждение',
    '_adm_dbd_txt_ht_warnings' => '{0} предупреждений',
    '_adm_dbd_txt_ht_failed' => '{0} не пройдено',
    '_adm_dbd_txt_ht_unknown' => '{0} не проверено',
    '_adm_dbd_txt_c_all' => 'Все кеши',
    '_adm_dbd_txt_q_all' => 'Все очереди',
    '_adm_dbd_txt_q_clear_all' => 'Очистить все очереди',
    '_adm_dbd_txt_q_clear_item' => 'Очистить очередь «{0}»',
    '_adm_dbd_txt_q_queued' => '{0} в очереди',
    '_adm_dbd_txt_q_failed' => '{0} с ошибкой',
    '_adm_dbd_msg_q_clean_success' => 'Очередь успешно очищена',
    '_adm_dbd_txt_c_purifier' => 'Purifier',
    '_adm_dbd_txt_c_custom' => 'Специальный',
    '_adm_lmi_cpt_etemplates_html' => 'Email-шаблоны',
    '_adm_stg_cpt_option_sys_audit_report' => 'Отчёт последнего аудита сервера',
    '_adm_str_txt_pv_screenshot' => 'Скриншот {0}',
    '_adm_strg_txt_images_resize_result' => 'Изображение с изменённым размером',
    '_adm_tmi_lbl_search_apps' => 'Поиск приложений',
    '_adm_tmi_lbl_search_clear' => 'Очистить поиск',
    '_adm_txt_launcher_apps' => 'Приложения',
    '_adm_txt_launcher_search_empty' => 'Ничего не найдено',
    '_adm_txt_launcher_search_matches' => 'Найдено приложений: {0}',
    '_adm_txt_launcher_search_matches_one' => 'Найдено 1 приложение',
    '_adm_txt_widget_action_label' => '{0}: {1}',
    '_adm_txt_widget_move_left' => 'Переместить {0} влево',
    '_adm_txt_widget_move_right' => 'Переместить {0} вправо',
    '_adm_txt_widget_moved' => '{0}: позиция {1} из {2}',
    '_adm_txt_icon_image_current' => 'Текущее изображение иконки',
    '_sys_audit_header_manual_audit' => 'Ручной аудит',
    '_sys_audit_header_site_optimization' => 'Оптимизация',
    '_sys_audit_mail_sending' => 'Доставка почты',
    '_sys_audit_msg_apache_module_fail' => 'Установите {0} для Apache.',
    '_sys_audit_msg_cron_jobs' => 'Не запускался последний час: проверьте запись в crontab.',
    '_sys_audit_msg_optimization_fail' => 'Включите в Настройки &gt; Кэш.',
    '_sys_audit_msg_optimization_warn' => 'PHP-акселератор ускорит файловый кэш.',
    '_sys_audit_msg_x_based_cache_engine' => ' ({0})',
    '_sys_audit_msg_ffmpeg' => 'Не найден по пути {0}: конвертация видео и аудио не будет работать.',
    '_sys_audit_msg_hardware_requirements' => 'Автоматически не проверяется: см. ручной аудит.',
    '_sys_audit_msg_mail_send_failed' => 'Отправка не удалась.',
    '_sys_audit_msg_mail_sending' => '<span id="bx-sys-adm-audit-test-email"><a href="javascript:void(0);" onclick="bx_sys_adm_audit_test_email()">Отправить тестовое письмо</a></span>',
    '_sys_audit_msg_mail_sent' => 'Тестовое письмо отправлено на {0}.',
    '_sys_audit_msg_manual_audit' => 'Часть проверок делается вручную. <a target="_blank" href="mailto:team@unacms.com?subject=Server Audit Request">Запросить аудит сервера</a>.',
    '_sys_audit_msg_permissions' => 'Подробности на вкладке <a href="javascript:void(0);" onclick="oBxDolStudioDashboard.permissions()">Права доступа</a>.',
    '_sys_audit_msg_php_accelerator_missing' => 'Установите PHP-акселератор, например OPcache, для заметного ускорения.',
    '_sys_audit_msg_php_setup_inefficient' => 'CGI работает медленно: перейдите на mod_php, DSO или FastCGI. <a href="javascript:void(0)" onclick="bx_sys_adm_audit_phpinfo()">Открыть phpinfo</a>.',
    '_sys_audit_msg_userside_caching' => '<a href="{0}" target="_blank">Проверить в PageSpeed</a>',
    '_sys_audit_msg_value_checking_failed' => 'Не удалось проверить.',
    '_sys_audit_msg_version_is_incompatible' => 'Не поддерживается: UNA требует {0} или новее.',
    '_sys_audit_msg_version_is_outdated' => 'Устарела: последняя версия {0}.',
    '_sys_audit_permissions' => 'Права на файлы',
    '_sys_audit_https' => 'HTTPS',
    '_sys_audit_msg_https' => 'Сайт работает по HTTP: переведите его на HTTPS.',
    '_sys_audit_install_dir' => 'Каталог install',
    '_sys_audit_msg_install_dir' => 'Всё ещё на сервере: удалите каталог install.',
    '_sys_audit_display_errors' => 'Вывод ошибок',
    '_sys_audit_msg_display_errors' => 'PHP показывает ошибки посетителям: установите display_errors = Off.',
    '_sys_audit_expose_php' => 'Заголовок с версией PHP',
    '_sys_audit_msg_expose_php' => 'Версия PHP отправляется в заголовках ответа: установите expose_php = Off.',
    '_sys_audit_config_file' => 'Файл конфигурации',
    '_sys_audit_msg_config_file' => 'inc/header.inc.php доступен для записи другим пользователям: установите права 0644.',
    '_sys_audit_present' => 'Есть',
    '_sys_audit_removed' => 'Удалён',
    '_sys_audit_on' => 'Вкл',
    '_sys_audit_off' => 'Выкл',
    '_sys_audit_php_setup' => 'Обработчик PHP',
    '_sys_audit_section_cache_engines' => 'Движки кэша',
    '_sys_audit_section_php_extensions' => 'Расширения PHP',
    '_sys_audit_section_webserver' => 'Веб-сервер',
    '_sys_audit_serverside_compression' => 'Сжатие ответов',
    '_sys_audit_userside_caching' => 'Кэширование в браузере',
    '_sys_audit_version' => 'Версия',
    '_sys_menu_item_title_system_sa_tour' => 'Вводный тур',
    '_sys_menu_item_title_sa_tour' => 'Вводный тур',
    '_sys_page_block_title_std_dash_version' => 'Обновления',
    '_sys_page_block_title_std_dash_space' => 'Место',
    '_sys_page_block_title_std_dash_host_tools' => 'Сервер',
    '_sys_queue_storage' => 'Удаление файлов',
);
