<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$aLangContent = array(
    '_payment_pcaption_details' => 'Payment Details',
    '_payment_pcaption_view_cart' => 'Shopping cart',
    '_payment_pcaption_checkout' => 'Checkout',
    '_payment_pcaption_admin' => 'Payment administration',
    '_payment_pcaption_view_orders' => 'Order Administration',
    '_payment_pcaption_cart_history' => 'Cart History',
    '_payment_pcaption_payment_result' => 'Payment Result',
    '_payment_bcaption_details' => 'Payment Details',
    '_payment_bcaption_settings' => 'Payment Settings',
    '_payment_bcaption_cart_featured' => 'Site Cart',
    '_payment_bcaption_cart_common' => 'Members\' Carts',
    '_payment_bcaption_checkout' => 'Checkout',
    '_payment_bcaption_pending_orders' => 'Pending Orders',
    '_payment_bcaption_processed_orders' => 'Processed Orders',
    '_payment_bcaption_cart_history' => 'Cart History',
    '_payment_bcaption_payment_result' => 'Payment Result',
    '_payment_msg_no_results' => 'Empty',
    '_payment_details_return_url' => 'Data return URL',
    '_payment_details_submit' => 'Save',
    '_payment_add_to_cart' => 'Add to Cart',
    '_payment_err_wrong_data' => 'Incorrect input data',
    '_payment_err_required_login' => 'You need to login',
    '_payment_err_purchase_from_yourself' => 'You cannot purchase your own item',
    '_payment_err_inactive_vendor' => 'The vendor does not have active status',
    '_payment_err_not_accept_payments' => 'The vendor does not accept payments',
    '_payment_err_incorrect_provider' => 'Incorrect or unavailable payment provider',
    '_payment_err_unknown_vendor' => 'Unknown vendor',
    '_payment_err_empty_order' => 'The order is empty',
    '_payment_err_access_db' => 'Database access error.',
    '_payment_err_unknown' => 'An error occured during the operation',
    '_payment_err_empty_orders' => 'Fill in order numbers',
    '_payment_err_nothing_selected' => 'You need to select at least one item',
    '_payment_err_wrong_client' => 'Incorrect client\'s name',
    '_payment_err_self_purchase' => 'Cannot sell to yourself',
    '_payment_err_wrong_order' => 'Incorrect order',
    '_payment_err_wrong_module' => 'Select where item is located',
    '_payment_err_empty_items' => 'There are no items selected',
    '_payment_err_wrong_quantity' => 'Incorrect quantity specified',
    '_payment_inf_successfully_added' => 'The item was successfully added to your shopping cart',
    '_payment_inf_successfully_deleted' => 'The item was successfully deleted from your shopping cart',
    '_payment_inf_successfully_reported' => 'The order was successfully reported',
    '_payment_txt_items_on' => 'item(s) on',
    '_payment_txt_view' => 'view',
    '_payment_txt_empty' => 'empty',
    '_payment_txt_by' => 'by',
    '_payment_txt_checkout' => 'checkout',
    '_payment_txt_payment_to' => 'Payment to {0} for:',
    '_payment_btn_delete' => 'Delete',
    '_payment_btn_checkout' => 'Checkout',
    '_payment_btn_process' => 'Process',
    '_payment_btn_cancel' => 'Cancel',
    '_payment_btn_report' => 'Report',
    '_payment_btn_add' => 'Add',
    '_payment_btn_manual_order' => 'Manual Order',
    '_payment_btn_settings' => 'Settings',
    '_payment_btn_orders_processed' => 'Processed',
    '_payment_btn_orders_pending' => 'Pending',
    '_payment_btn_history' => 'History',
    '_payment_btn_cart' => 'Cart',
    '_payment_tbar_item_caption' => 'Shopping Cart',
    '_payment_tbar_item_description' => 'Shopping Cart',
    '_payment_tmenu_payments' => 'Payments',
    '_payment_tmenu_cart' => 'Cart',
    '_payment_amenu_payment' => 'Payment',
    '_payment_txt_username_administrator' => 'Administrator',
    '_payment_txt_shopping_cart' => '\'s cart',
    '_payment_txt_date' => 'Date',
    '_payment_txt_client' => 'Client',
    '_payment_txt_seller' => 'Seller',
    '_payment_txt_order' => 'Order ID',
    '_payment_txt_amount' => 'Amount',
    '_payment_txt_license' => 'License',
    '_payment_txt_action' => 'More',
    '_payment_txt_action_more' => 'More',
    '_payment_txt_processed_with' => 'Processed with',
    '_payment_txt_message' => 'Result',
    '_payment_txt_products' => 'Products',
    '_payment_txt_more_products' => 'products',
    '_payment_txt_more_items' => 'items',
    '_payment_wcaption_manual_order' => 'Manual Order',
    '_payment_wcaption_order_info' => 'Order Info',
    '_payment_fldcaption_module' => 'Items from',
    '_payment_fldcaption_client' => 'Client',
    '_payment_fldcaption_order' => 'Order',
    '_payment_ocaption_select' => 'Select one',
    '_payment_pp_active_cpt' => 'Active',
    '_payment_pp_active_dsc' => 'Activate(Deactivate) provider',
    '_payment_pp_mode_cpt' => 'Mode',
    '_payment_pp_mode_dsc' => 'Mode to process paymments',
    '_payment_pp_mode_live' => 'live',
    '_payment_pp_mode_test' => 'test',
    '_payment_pp_business_cpt' => 'Business',
    '_payment_pp_business_dsc' => 'Business email address',
    '_payment_pp_business_err' => 'You need to specify a valid email address',
    '_payment_pp_prc_type_cpt' => 'Process type',
    '_payment_pp_prc_type_dsc' => 'The type in which data is to be processed. In IPN mode use URL like the following http://www.your-site.com/your-path/m/payment/act_finalize_checkout/paypal as notify URL in your PayPal account',
    '_payment_pp_prc_type_direct' => 'direct',
    '_payment_pp_prc_type_pdt' => 'PDT',
    '_payment_pp_prc_type_ipn' => 'IPN',
    '_payment_pp_cnt_type_cpt' => 'Connection type',
    '_payment_pp_cnt_type_dsc' => 'The type of connection to be used to transfer data',
    '_payment_pp_cnt_type_ssl' => 'SSL',
    '_payment_pp_cnt_type_html' => 'HTML',
    '_payment_pp_token_cpt' => 'Identity token',
    '_payment_pp_token_dsc' => 'Identity token',
    '_payment_pp_sandbox_cpt' => 'Sandbox',
    '_payment_pp_sandbox_dsc' => 'Sandbox email address',
    '_payment_pp_sandbox_err' => 'You need to specify a valid email address',
    '_payment_pp_err_no_data_given' => 'No data given.',
    '_payment_pp_err_no_vendor_given' => 'Unknown vendor.',
    '_payment_pp_err_not_completed' => 'Payment is not completed.',
    '_payment_pp_err_wrong_business' => 'Wrong receiver email.',
    '_payment_pp_err_wrong_transaction' => 'Transaction verification failed.',
    '_payment_pp_err_wrong_verification_status' => 'No verification status received.',
    '_payment_pp_err_wrong_amount' => 'Wrong amount.',
    '_payment_pp_err_wrong_custom_data' => 'Incorrect custom data.',
    '_payment_pp_err_already_processed' => 'The payment is already processed.',
    '_payment_pp_msg_verified' => 'Successfully verified.',
    '_payment_2co_active_cpt' => 'Active',
    '_payment_2co_active_dsc' => 'Activate(Deactivate) provider',
    '_payment_2co_mode_cpt' => 'Mode',
    '_payment_2co_mode_dsc' => 'Mode to process paymments',
    '_payment_2co_mode_live' => 'live',
    '_payment_2co_mode_test' => 'test',
    '_payment_2co_account_id_cpt' => 'Account number',
    '_payment_2co_account_id_dsc' => 'Your 2Checkout vendor account number',
    '_payment_2co_payment_method_cpt' => 'Payment Method',
    '_payment_2co_payment_method_dsc' => 'This will set the default selection on the payment method step during the checkout process',
    '_payment_2co_payment_method_cc' => 'Credit Card(CC)',
    '_payment_2co_payment_method_ck' => 'Check(CK)',
    '_payment_2co_payment_method_al' => 'Acculynk PIN-debit(AL)',
    '_payment_2co_payment_method_ppi' => 'PayPal(PPI)',
    '_payment_2co_secret_word_cpt' => 'Secret Word',
    '_payment_2co_secret_word_dsc' => 'Secret word is used to calculate a check hash',
    '_payment_2co_err_no_vendor_given' => 'Unknown vendor',
    '_payment_2co_err_no_data_given' => 'No data given.',
    '_payment_2co_err_wrong_key' => 'Check key is incorrect.',
    '_payment_2co_err_wrong_payment' => 'Wrong payment amount.',
    '_payment_2co_err_already_processed' => 'The payment is already processed',
    '_payment_2co_msg_verified' => 'Successfully verified.'
);
?>
