<?php

$aFilesDelete = array(
    'plugins_public/codemirror/lib/codemirror.css',
    'plugins_public/codemirror/lib/codemirror.js',
    'plugins_public/codemirror/mode/css/css.js',
    'plugins_public/codemirror/mode/css/index.html',
    'plugins_public/codemirror/mode/css/less.html',
    'plugins_public/codemirror/mode/css/less_test.js',
    'plugins_public/codemirror/mode/css/scss.html',
    'plugins_public/codemirror/mode/css/scss_test.js',
    'plugins_public/codemirror/mode/css/test.js',
    'plugins_public/codemirror/mode/htmlembedded/htmlembedded.js',
    'plugins_public/codemirror/mode/htmlembedded/index.html',
    'plugins_public/codemirror/mode/htmlmixed/htmlmixed.js',
    'plugins_public/codemirror/mode/htmlmixed/index.html',
    'plugins_public/codemirror/mode/index.html',
    'plugins_public/codemirror/mode/javascript/index.html',
    'plugins_public/codemirror/mode/javascript/javascript.js',
    'plugins_public/codemirror/mode/javascript/json-ld.html',
    'plugins_public/codemirror/mode/javascript/test.js',
    'plugins_public/codemirror/mode/javascript/typescript.html',
    'plugins_public/codemirror/mode/meta.js',
    'plugins_public/codemirror/mode/php/index.html',
    'plugins_public/codemirror/mode/php/php.js',
    'plugins_public/codemirror/mode/php/test.js',
    'plugins_public/codemirror/mode/sql/index.html',
    'plugins_public/codemirror/mode/sql/sql.js',
    'plugins_public/codemirror/mode/xml/index.html',
    'plugins_public/codemirror/mode/xml/test.js',
    'plugins_public/codemirror/mode/xml/xml.js',

    'plugins_public/codemirror/mode/htmlembedded',
    'plugins_public/codemirror/mode/javascript',
    'plugins_public/codemirror/mode/htmlmixed',
    'plugins_public/codemirror/mode/css',
    'plugins_public/codemirror/mode/php',
    'plugins_public/codemirror/mode/sql',
    'plugins_public/codemirror/mode/xml',
    'plugins_public/codemirror/mode',
    'plugins_public/codemirror/lib',
);

