const { theme } = require('app/design/tailwind/theme.js')
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    '../../packages/**/*.{js,jsx,ts,tsx}'
  ],
  safelist: [
    // Card component density classes
    'u-card-base-compact',
    'u-card-base-default', 
    'u-card-base-relaxed',
    'u-card-header-compact',
    'u-card-header-default',
    'u-card-header-relaxed',
    'u-card-title-compact',
    'u-card-title-default',
    'u-card-title-relaxed',
    'u-card-description-compact',
    'u-card-description-default',
    'u-card-description-relaxed',
    'u-card-content-compact',
    'u-card-content-default',
    'u-card-content-relaxed',
    'u-card-footer-compact',
    'u-card-footer-default',
    'u-card-footer-relaxed',
    // Block component density classes
    'u-block-base-compact',
    'u-block-base-default', 
    'u-block-base-relaxed',
    'u-block-header-compact',
    'u-block-header-default',
    'u-block-header-relaxed',
    'u-block-title-compact',
    'u-block-title-default',
    'u-block-title-relaxed',
    'u-block-description-compact',
    'u-block-description-default',
    'u-block-description-relaxed',
    'u-block-content-compact',
    'u-block-content-default',
    'u-block-content-relaxed',
    'u-block-footer-compact',
    'u-block-footer-default',
    'u-block-footer-relaxed',
    // Content padding density classes
    'u-content-padding-compact',
    'u-content-padding-default',
    'u-content-padding-relaxed',
    // Density-aware padding utilities
    'p-sm',
    'p-md',
    'p-lg',
    'px-sm',
    'px-md',
    'px-lg',
    'py-sm',
    'py-md',
    'py-lg',
    'pt-sm',
    'pt-md',
    'pt-lg',
    'pb-sm',
    'pb-md',
    'pb-lg',
    // Density-aware gap utilities
    'gap-sm',
    'gap-md',
    'gap-lg',
    // Controls
    'u-controls-switcher-track-base',
    'u-controls-switcher-track-sm',
    'u-controls-switcher-thumb-base',
    'u-controls-switcher-thumb-sm',
    'u-controls-switcher-thumb-active-base',
    'u-controls-switcher-thumb-active-sm',
  ],
  presets: [require("nativewind/preset")],
  theme: {
    ...theme,
  },
  plugins: [],
}

