
TRUNCATE TABLE `sys_objects_embeds`;
INSERT INTO `sys_objects_embeds` (`object`, `title`, `override_class_name`, `override_class_file`) VALUES
('sys_embedly', 'Embedly', 'BxTemplEmbedEmbedly', ''),
('sys_iframely', 'Iframely', 'BxTemplEmbedIframely', '');

DELETE FROM `sys_preloader` WHERE `content` IN('jquery-ui/jquery-ui.custom.min.js', 'timepicker-addon/jquery-ui-sliderAccess.js', 'timepicker-addon/jquery-ui-timepicker-addon.min.js');

-- Settings

DELETE FROM `sys_options_categories` WHERE `name` IN('client_image_resize_width', 'client_image_resize_height', 'sys_account_limit_incorrect_login_attempts');

SET @iCategoryIdGeneral = (SELECT `id` FROM `sys_options_categories` WHERE `name` = 'general');
INSERT INTO `sys_options`(`category_id`, `name`, `caption`, `value`, `type`, `extra`, `check`, `check_error`, `order`) VALUES
(@iCategoryIdGeneral, 'client_image_resize_width', '_adm_stg_cpt_option_client_image_resize_width', '2048', 'digit', '', '', '', 42),
(@iCategoryIdGeneral, 'client_image_resize_height', '_adm_stg_cpt_option_client_image_resize_height', '2048', 'digit', '', '', '', 43);

SET @iCategoryIdAccount = (SELECT `id` FROM `sys_options_categories` WHERE `name` = 'account');
INSERT INTO `sys_options`(`category_id`, `name`, `caption`, `value`, `type`, `extra`, `check`, `check_error`, `order`) VALUES
(@iCategoryIdAccount, 'sys_account_limit_incorrect_login_attempts', '_adm_stg_cpt_option_sys_account_limit_incorrect_login_attempts', '6', 'digit', '', '', '', 22);

-- MIME types

TRUNCATE TABLE `sys_storage_mime_types`;
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('ez', 'application/andrew-inset', '', ''),
('aw', 'application/applixware', '', ''),
('atom', 'application/atom+xml', '', ''),
('atomcat', 'application/atomcat+xml', '', ''),
('atomsvc', 'application/atomsvc+xml', '', ''),
('ccxml', 'application/ccxml+xml', '', ''),
('cdmia', 'application/cdmi-capability', '', ''),
('cdmic', 'application/cdmi-container', '', ''),
('cdmid', 'application/cdmi-domain', '', ''),
('cdmio', 'application/cdmi-object', '', ''),
('cdmiq', 'application/cdmi-queue', '', ''),
('cu', 'application/cu-seeme', '', ''),
('davmount', 'application/davmount+xml', '', ''),
('dbk', 'application/docbook+xml', '', ''),
('dssc', 'application/dssc+der', '', ''),
('xdssc', 'application/dssc+xml', '', ''),
('ecma', 'application/ecmascript', '', ''),
('emma', 'application/emma+xml', '', ''),
('epub', 'application/epub+zip', '', ''),
('exi', 'application/exi', '', ''),
('pfr', 'application/font-tdpfr', '', ''),
('gml', 'application/gml+xml', '', ''),
('gpx', 'application/gpx+xml', '', ''),
('gxf', 'application/gxf', '', ''),
('stk', 'application/hyperstudio', '', ''),
('ink', 'application/inkml+xml', '', ''),
('inkml', 'application/inkml+xml', '', ''),
('ipfix', 'application/ipfix', '', ''),
('jar', 'application/java-archive', '', ''),
('ser', 'application/java-serialized-object', '', ''),
('class', 'application/java-vm', '', ''),
('js', 'application/javascript', '', 'far file-code'),
('json', 'application/json', '', 'far file-code'),
('jsonml', 'application/jsonml+json', '', ''),
('lostxml', 'application/lost+xml', '', ''),
('hqx', 'application/mac-binhex40', '', ''),
('cpt', 'application/mac-compactpro', '', ''),
('mads', 'application/mads+xml', '', ''),
('mrc', 'application/marc', '', ''),
('mrcx', 'application/marcxml+xml', '', ''),
('ma', 'application/mathematica', '', ''),
('nb', 'application/mathematica', '', ''),
('mb', 'application/mathematica', '', ''),
('mathml', 'application/mathml+xml', '', ''),
('mbox', 'application/mbox', '', 'far file-code'),
('mscml', 'application/mediaservercontrol+xml', '', ''),
('metalink', 'application/metalink+xml', '', ''),
('meta4', 'application/metalink4+xml', '', ''),
('mets', 'application/mets+xml', '', ''),
('mods', 'application/mods+xml', '', ''),
('m21', 'application/mp21', '', ''),
('mp21', 'application/mp21', '', ''),
('mp4s', 'application/mp4', '', ''),
('doc', 'application/msword', 'mime-type-document.png', 'far file-word'),
('dot', 'application/msword', '', ''),
('mxf', 'application/mxf', '', ''),
('bin', 'application/octet-stream', '', ''),
('dms', 'application/octet-stream', '', ''),
('lrf', 'application/octet-stream', '', ''),
('mar', 'application/octet-stream', '', ''),
('so', 'application/octet-stream', '', ''),
('dist', 'application/octet-stream', '', ''),
('distz', 'application/octet-stream', '', ''),
('pkg', 'application/octet-stream', '', ''),
('bpk', 'application/octet-stream', '', ''),
('dump', 'application/octet-stream', '', ''),
('elc', 'application/octet-stream', '', ''),
('deploy', 'application/octet-stream', '', ''),
('mobipocket-ebook', 'application/octet-stream', '', ''),
('oda', 'application/oda', '', ''),
('opf', 'application/oebps-package+xml', '', ''),
('ogx', 'application/ogg', '', ''),
('omdoc', 'application/omdoc+xml', '', ''),
('onetoc', 'application/onenote', '', ''),
('onetoc2', 'application/onenote', '', ''),
('onetmp', 'application/onenote', '', ''),
('onepkg', 'application/onenote', '', ''),
('oxps', 'application/oxps', '', ''),
('xer', 'application/patch-ops-error+xml', '', ''),
('pdf', 'application/pdf', 'mime-type-document.png', 'far file-pdf'),
('pgp', 'application/pgp-encrypted', '', 'far file-code'),
('asc', 'application/pgp-signature', '', 'far file-code'),
('sig', 'application/pgp-signature', '', 'far file-code'),
('prf', 'application/pics-rules', '', ''),
('p10', 'application/pkcs10', 'mime-type-vector.png', ''),
('p7m', 'application/pkcs7-mime', '', ''),
('p7c', 'application/pkcs7-mime', '', ''),
('p7s', 'application/pkcs7-signature', '', ''),
('p8', 'application/pkcs8', '', ''),
('ac', 'application/pkix-attr-cert', '', ''),
('cer', 'application/pkix-cert', '', ''),
('crl', 'application/pkix-crl', '', ''),
('pkipath', 'application/pkix-pkipath', '', ''),
('pki', 'application/pkixcmp', '', ''),
('pls', 'application/pls+xml', '', ''),
('ai', 'application/postscript', 'mime-type-vector.png', ''),
('eps', 'application/postscript', '', ''),
('ps', 'application/postscript', 'mime-type-vector.png', ''),
('cww', 'application/prs.cww', '', ''),
('pskcxml', 'application/pskc+xml', '', ''),
('rdf', 'application/rdf+xml', '', 'far file-code'),
('rif', 'application/reginfo+xml', '', ''),
('rnc', 'application/relax-ng-compact-syntax', '', ''),
('rl', 'application/resource-lists+xml', '', ''),
('rld', 'application/resource-lists-diff+xml', '', ''),
('rs', 'application/rls-services+xml', '', ''),
('gbr', 'application/rpki-ghostbusters', '', ''),
('mft', 'application/rpki-manifest', '', ''),
('roa', 'application/rpki-roa', '', ''),
('rsd', 'application/rsd+xml', '', ''),
('rss', 'application/rss+xml', '', 'far file-code'),
('rtf', 'application/rtf', 'mime-type-document.png', ''),
('sbml', 'application/sbml+xml', '', ''),
('scq', 'application/scvp-cv-request', '', ''),
('scs', 'application/scvp-cv-response', '', ''),
('spq', 'application/scvp-vp-request', '', ''),
('spp', 'application/scvp-vp-response', '', ''),
('sdp', 'application/sdp', 'mime-type-presentation.png', 'far file-powerpoint'),
('setpay', 'application/set-payment-initiation', '', ''),
('setreg', 'application/set-registration-initiation', '', ''),
('shf', 'application/shf+xml', '', ''),
('smi', 'application/smil+xml', '', ''),
('smil', 'application/smil+xml', '', ''),
('rq', 'application/sparql-query', '', 'far file-code'),
('srx', 'application/sparql-results+xml', '', ''),
('gram', 'application/srgs', '', ''),
('grxml', 'application/srgs+xml', '', ''),
('sru', 'application/sru+xml', '', ''),
('ssdl', 'application/ssdl+xml', '', ''),
('ssml', 'application/ssml+xml', '', ''),
('tei', 'application/tei+xml', '', ''),
('teicorpus', 'application/tei+xml', '', ''),
('tfi', 'application/thraud+xml', '', ''),
('tsd', 'application/timestamped-data', '', ''),
('plb', 'application/vnd.3gpp.pic-bw-large', '', ''),
('psb', 'application/vnd.3gpp.pic-bw-small', '', ''),
('pvb', 'application/vnd.3gpp.pic-bw-var', '', ''),
('tcap', 'application/vnd.3gpp2.tcap', '', ''),
('pwn', 'application/vnd.3m.post-it-notes', '', ''),
('aso', 'application/vnd.accpac.simply.aso', '', ''),
('imp', 'application/vnd.accpac.simply.imp', '', ''),
('acu', 'application/vnd.acucobol', '', ''),
('atc', 'application/vnd.acucorp', '', ''),
('acutc', 'application/vnd.acucorp', '', ''),
('air', 'application/vnd.adobe.air-application-installer-package+zip', '', ''),
('fcdt', 'application/vnd.adobe.formscentral.fcdt', '', ''),
('fxp', 'application/vnd.adobe.fxp', '', ''),
('fxpl', 'application/vnd.adobe.fxp', '', ''),
('xdp', 'application/vnd.adobe.xdp+xml', '', ''),
('xfdf', 'application/vnd.adobe.xfdf', '', ''),
('ahead', 'application/vnd.ahead.space', '', ''),
('azf', 'application/vnd.airzip.filesecure.azf', '', ''),
('azs', 'application/vnd.airzip.filesecure.azs', '', ''),
('azw', 'application/vnd.amazon.ebook', '', ''),
('acc', 'application/vnd.americandynamics.acc', '', ''),
('ami', 'application/vnd.amiga.ami', '', ''),
('apk', 'application/vnd.android.package-archive', '', ''),
('cii', 'application/vnd.anser-web-certificate-issue-initiation', '', ''),
('fti', 'application/vnd.anser-web-funds-transfer-initiation', '', ''),
('atx', 'application/vnd.antix.game-component', '', ''),
('mpkg', 'application/vnd.apple.installer+xml', '', ''),
('m3u8', 'application/vnd.apple.mpegurl', '', ''),
('swi', 'application/vnd.aristanetworks.swi', '', ''),
('iota', 'application/vnd.astraea-software.iota', '', ''),
('aep', 'application/vnd.audiograph', '', ''),
('mpm', 'application/vnd.blueice.multipass', '', ''),
('bmi', 'application/vnd.bmi', '', ''),
('rep', 'application/vnd.businessobjects', '', ''),
('cdxml', 'application/vnd.chemdraw+xml', '', ''),
('mmd', 'application/vnd.chipnuts.karaoke-mmd', '', ''),
('cdy', 'application/vnd.cinderella', '', ''),
('cla', 'application/vnd.claymore', '', ''),
('rp9', 'application/vnd.cloanto.rp9', '', ''),
('c4g', 'application/vnd.clonk.c4group', '', ''),
('c4d', 'application/vnd.clonk.c4group', '', ''),
('c4f', 'application/vnd.clonk.c4group', '', ''),
('c4p', 'application/vnd.clonk.c4group', '', ''),
('c4u', 'application/vnd.clonk.c4group', '', ''),
('c11amc', 'application/vnd.cluetrust.cartomobile-config', '', ''),
('c11amz', 'application/vnd.cluetrust.cartomobile-config-pkg', '', ''),
('csp', 'application/vnd.commonspace', '', ''),
('cdbcmsg', 'application/vnd.contact.cmsg', '', ''),
('cmc', 'application/vnd.cosmocaller', '', ''),
('clkx', 'application/vnd.crick.clicker', '', ''),
('clkk', 'application/vnd.crick.clicker.keyboard', '', ''),
('clkp', 'application/vnd.crick.clicker.palette', '', ''),
('clkt', 'application/vnd.crick.clicker.template', '', ''),
('clkw', 'application/vnd.crick.clicker.wordbank', '', ''),
('wbs', 'application/vnd.criticaltools.wbs+xml', '', ''),
('pml', 'application/vnd.ctc-posml', '', ''),
('ppd', 'application/vnd.cups-ppd', '', ''),
('car', 'application/vnd.curl.car', '', ''),
('pcurl', 'application/vnd.curl.pcurl', '', ''),
('dart', 'application/vnd.dart', '', ''),
('rdz', 'application/vnd.data-vision.rdz', '', ''),
('uvf', 'application/vnd.dece.data', '', ''),
('uvvf', 'application/vnd.dece.data', '', ''),
('uvd', 'application/vnd.dece.data', '', ''),
('uvvd', 'application/vnd.dece.data', '', ''),
('uvt', 'application/vnd.dece.ttml+xml', '', ''),
('uvvt', 'application/vnd.dece.ttml+xml', '', ''),
('uvx', 'application/vnd.dece.unspecified', '', ''),
('uvvx', 'application/vnd.dece.unspecified', '', ''),
('uvz', 'application/vnd.dece.zip', '', ''),
('uvvz', 'application/vnd.dece.zip', '', ''),
('fe_launch', 'application/vnd.denovo.fcselayout-link', '', ''),
('dna', 'application/vnd.dna', '', ''),
('mlp', 'application/vnd.dolby.mlp', '', ''),
('dpg', 'application/vnd.dpgraph', '', ''),
('dfac', 'application/vnd.dreamfactory', '', ''),
('kpxx', 'application/vnd.ds-keypoint', '', ''),
('ait', 'application/vnd.dvb.ait', 'mime-type-vector.png', ''),
('svc', 'application/vnd.dvb.service', '', '');
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('geo', 'application/vnd.dynageo', '', ''),
('mag', 'application/vnd.ecowin.chart', '', ''),
('nml', 'application/vnd.enliven', '', ''),
('esf', 'application/vnd.epson.esf', '', ''),
('msf', 'application/vnd.epson.msf', '', ''),
('qam', 'application/vnd.epson.quickanime', '', ''),
('slt', 'application/vnd.epson.salt', '', ''),
('ssf', 'application/vnd.epson.ssf', '', ''),
('es3', 'application/vnd.eszigno3+xml', '', ''),
('et3', 'application/vnd.eszigno3+xml', '', ''),
('ez2', 'application/vnd.ezpix-album', '', ''),
('ez3', 'application/vnd.ezpix-package', '', ''),
('fdf', 'application/vnd.fdf', '', ''),
('mseed', 'application/vnd.fdsn.mseed', '', ''),
('seed', 'application/vnd.fdsn.seed', '', ''),
('dataless', 'application/vnd.fdsn.seed', '', ''),
('gph', 'application/vnd.flographit', '', ''),
('ftc', 'application/vnd.fluxtime.clip', '', ''),
('fm', 'application/vnd.framemaker', '', ''),
('frame', 'application/vnd.framemaker', '', ''),
('maker', 'application/vnd.framemaker', '', ''),
('book', 'application/vnd.framemaker', '', ''),
('fnc', 'application/vnd.frogans.fnc', '', ''),
('ltf', 'application/vnd.frogans.ltf', '', ''),
('fsc', 'application/vnd.fsc.weblaunch', '', ''),
('oas', 'application/vnd.fujitsu.oasys', '', ''),
('oa2', 'application/vnd.fujitsu.oasys2', '', ''),
('oa3', 'application/vnd.fujitsu.oasys3', '', ''),
('fg5', 'application/vnd.fujitsu.oasysgp', '', ''),
('bh2', 'application/vnd.fujitsu.oasysprs', '', ''),
('ddd', 'application/vnd.fujixerox.ddd', '', ''),
('xdw', 'application/vnd.fujixerox.docuworks', '', ''),
('xbd', 'application/vnd.fujixerox.docuworks.binder', '', ''),
('fzs', 'application/vnd.fuzzysheet', '', ''),
('txd', 'application/vnd.genomatix.tuxedo', '', ''),
('ggb', 'application/vnd.geogebra.file', '', ''),
('ggt', 'application/vnd.geogebra.tool', '', ''),
('gex', 'application/vnd.geometry-explorer', '', ''),
('gre', 'application/vnd.geometry-explorer', '', ''),
('gxt', 'application/vnd.geonext', '', ''),
('g2w', 'application/vnd.geoplan', '', ''),
('g3w', 'application/vnd.geospace', '', ''),
('gmx', 'application/vnd.gmx', '', ''),
('kml', 'application/vnd.google-earth.kml+xml', '', ''),
('kmz', 'application/vnd.google-earth.kmz', '', ''),
('gqf', 'application/vnd.grafeq', '', ''),
('gqs', 'application/vnd.grafeq', '', ''),
('gac', 'application/vnd.groove-account', '', ''),
('ghf', 'application/vnd.groove-help', '', ''),
('gim', 'application/vnd.groove-identity-message', '', ''),
('grv', 'application/vnd.groove-injector', '', ''),
('gtm', 'application/vnd.groove-tool-message', '', ''),
('tpl', 'application/vnd.groove-tool-template', '', 'far file-code'),
('vcg', 'application/vnd.groove-vcard', '', ''),
('hal', 'application/vnd.hal+xml', '', ''),
('zmm', 'application/vnd.handheld-entertainment+xml', '', ''),
('hbci', 'application/vnd.hbci', '', ''),
('les', 'application/vnd.hhe.lesson-player', '', ''),
('hpgl', 'application/vnd.hp-hpgl', 'mime-type-vector.png', ''),
('hpid', 'application/vnd.hp-hpid', '', ''),
('hps', 'application/vnd.hp-hps', '', ''),
('jlt', 'application/vnd.hp-jlyt', '', ''),
('pcl', 'application/vnd.hp-pcl', '', ''),
('pclxl', 'application/vnd.hp-pclxl', '', ''),
('sfd-hdstx', 'application/vnd.hydrostatix.sof-data', '', ''),
('mpy', 'application/vnd.ibm.minipay', '', ''),
('afp', 'application/vnd.ibm.modcap', '', ''),
('listafp', 'application/vnd.ibm.modcap', '', ''),
('list3820', 'application/vnd.ibm.modcap', '', ''),
('irm', 'application/vnd.ibm.rights-management', '', ''),
('sc', 'application/vnd.ibm.secure-container', '', ''),
('icc', 'application/vnd.iccprofile', '', ''),
('icm', 'application/vnd.iccprofile', '', ''),
('igl', 'application/vnd.igloader', '', ''),
('ivp', 'application/vnd.immervision-ivp', '', ''),
('ivu', 'application/vnd.immervision-ivu', '', ''),
('igm', 'application/vnd.insors.igm', '', ''),
('xpw', 'application/vnd.intercon.formnet', '', ''),
('xpx', 'application/vnd.intercon.formnet', '', ''),
('i2g', 'application/vnd.intergeo', '', ''),
('qbo', 'application/vnd.intu.qbo', '', ''),
('qfx', 'application/vnd.intu.qfx', '', ''),
('rcprofile', 'application/vnd.ipunplugged.rcprofile', '', ''),
('irp', 'application/vnd.irepository.package+xml', '', ''),
('xpr', 'application/vnd.is-xpr', '', ''),
('fcs', 'application/vnd.isac.fcs', '', ''),
('jam', 'application/vnd.jam', '', ''),
('rms', 'application/vnd.jcp.javame.midlet-rms', '', ''),
('jisp', 'application/vnd.jisp', '', ''),
('joda', 'application/vnd.joost.joda-archive', '', ''),
('ktz', 'application/vnd.kahootz', '', ''),
('ktr', 'application/vnd.kahootz', '', ''),
('karbon', 'application/vnd.kde.karbon', '', ''),
('chrt', 'application/vnd.kde.kchart', '', ''),
('kfo', 'application/vnd.kde.kformula', '', ''),
('flw', 'application/vnd.kde.kivio', '', ''),
('kon', 'application/vnd.kde.kontour', '', ''),
('kpr', 'application/vnd.kde.kpresenter', '', ''),
('kpt', 'application/vnd.kde.kpresenter', '', ''),
('ksp', 'application/vnd.kde.kspread', '', ''),
('kwd', 'application/vnd.kde.kword', '', ''),
('kwt', 'application/vnd.kde.kword', '', ''),
('htke', 'application/vnd.kenameaapp', '', ''),
('kia', 'application/vnd.kidspiration', '', ''),
('kne', 'application/vnd.kinar', '', ''),
('knp', 'application/vnd.kinar', '', ''),
('skp', 'application/vnd.koan', '', ''),
('skd', 'application/vnd.koan', '', ''),
('skt', 'application/vnd.koan', '', ''),
('skm', 'application/vnd.koan', '', ''),
('sse', 'application/vnd.kodak-descriptor', '', ''),
('lasxml', 'application/vnd.las.las+xml', '', ''),
('lbd', 'application/vnd.llamagraphics.life-balance.desktop', '', ''),
('lbe', 'application/vnd.llamagraphics.life-balance.exchange+xml', '', ''),
('123', 'application/vnd.lotus-1-2-3', '', ''),
('apr', 'application/vnd.lotus-approach', '', ''),
('pre', 'application/vnd.lotus-freelance', '', ''),
('nsf', 'application/vnd.lotus-notes', '', ''),
('org', 'application/vnd.lotus-organizer', '', ''),
('scm', 'application/vnd.lotus-screencam', '', ''),
('lwp', 'application/vnd.lotus-wordpro', '', ''),
('portpkg', 'application/vnd.macports.portpkg', '', ''),
('mcd', 'application/vnd.mcd', '', ''),
('mc1', 'application/vnd.medcalcdata', '', ''),
('cdkey', 'application/vnd.mediastation.cdkey', '', ''),
('mwf', 'application/vnd.mfer', '', ''),
('mfm', 'application/vnd.mfmp', '', ''),
('flo', 'application/vnd.micrografx.flo', '', ''),
('igx', 'application/vnd.micrografx.igx', '', ''),
('mif', 'application/vnd.mif', '', ''),
('daf', 'application/vnd.mobius.daf', '', ''),
('dis', 'application/vnd.mobius.dis', '', ''),
('mbk', 'application/vnd.mobius.mbk', '', ''),
('mqy', 'application/vnd.mobius.mqy', '', ''),
('msl', 'application/vnd.mobius.msl', '', ''),
('plc', 'application/vnd.mobius.plc', '', ''),
('txf', 'application/vnd.mobius.txf', '', ''),
('mpn', 'application/vnd.mophun.application', '', ''),
('mpc', 'application/vnd.mophun.certificate', '', ''),
('xul', 'application/vnd.mozilla.xul+xml', '', ''),
('cil', 'application/vnd.ms-artgalry', 'mime-type-vector.png', ''),
('taxi', 'application/vnd.ms-cab-compressed', 'mime-type-archive.png', 'far file-archive'),
('xls', 'application/vnd.ms-excel', 'mime-type-spreadsheet.png', 'far file-excel'),
('xlm', 'application/vnd.ms-excel', '', ''),
('xla', 'application/vnd.ms-excel', '', ''),
('xlc', 'application/vnd.ms-excel', '', ''),
('xlt', 'application/vnd.ms-excel', 'mime-type-spreadsheet.png', 'far file-excel'),
('xlw', 'application/vnd.ms-excel', '', ''),
('xlam', 'application/vnd.ms-excel.addin.macroenabled.12', '', ''),
('xlsb', 'application/vnd.ms-excel.sheet.binary.macroenabled.12', '', ''),
('xlsm', 'application/vnd.ms-excel.sheet.macroenabled.12', '', ''),
('xltm', 'application/vnd.ms-excel.template.macroenabled.12', '', ''),
('eot', 'application/vnd.ms-fontobject', '', ''),
('chm', 'application/vnd.ms-htmlhelp', '', ''),
('ims', 'application/vnd.ms-ims', '', ''),
('lrm', 'application/vnd.ms-lrm', '', ''),
('thmx', 'application/vnd.ms-officetheme', '', ''),
('cat', 'application/vnd.ms-pki.seccat', '', ''),
('stl', 'application/vnd.ms-pki.stl', '', ''),
('ppt', 'application/vnd.ms-powerpoint', 'mime-type-presentation.png', 'far file-powerpoint'),
('pps', 'application/vnd.ms-powerpoint', '', ''),
('pot', 'application/vnd.ms-powerpoint', '', ''),
('ppam', 'application/vnd.ms-powerpoint.addin.macroenabled.12', '', ''),
('pptm', 'application/vnd.ms-powerpoint.presentation.macroenabled.12', '', ''),
('sldm', 'application/vnd.ms-powerpoint.slide.macroenabled.12', '', ''),
('ppsm', 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', '', ''),
('potm', 'application/vnd.ms-powerpoint.template.macroenabled.12', '', ''),
('mpp', 'application/vnd.ms-project', '', ''),
('mpt', 'application/vnd.ms-project', '', ''),
('docm', 'application/vnd.ms-word.document.macroenabled.12', '', ''),
('dotm', 'application/vnd.ms-word.template.macroenabled.12', '', ''),
('wps', 'application/vnd.ms-works', '', ''),
('wks', 'application/vnd.ms-works', '', ''),
('wcm', 'application/vnd.ms-works', '', ''),
('wdb', 'application/vnd.ms-works', '', ''),
('wpl', 'application/vnd.ms-wpl', '', ''),
('xps', 'application/vnd.ms-xpsdocument', '', ''),
('mseq', 'application/vnd.mseq', '', ''),
('mus', 'application/vnd.musician', '', ''),
('msty', 'application/vnd.muvee.style', '', ''),
('taglet', 'application/vnd.mynfc', '', ''),
('nlu', 'application/vnd.neurolanguage.nlu', '', ''),
('ntf', 'application/vnd.nitf', '', ''),
('nitf', 'application/vnd.nitf', '', ''),
('nnd', 'application/vnd.noblenet-directory', '', ''),
('nns', 'application/vnd.noblenet-sealer', '', ''),
('nnw', 'application/vnd.noblenet-web', '', ''),
('ngdat', 'application/vnd.nokia.n-gage.data', '', ''),
('n-gage', 'application/vnd.nokia.n-gage.symbian.install', '', ''),
('rpst', 'application/vnd.nokia.radio-preset', '', ''),
('rpss', 'application/vnd.nokia.radio-presets', '', ''),
('edm', 'application/vnd.novadigm.edm', '', ''),
('edx', 'application/vnd.novadigm.edx', '', ''),
('ext', 'application/vnd.novadigm.ext', '', ''),
('odc', 'application/vnd.oasis.opendocument.chart', '', ''),
('otc', 'application/vnd.oasis.opendocument.chart-template', '', ''),
('odb', 'application/vnd.oasis.opendocument.database', '', ''),
('odf', 'application/vnd.oasis.opendocument.formula', '', ''),
('odft', 'application/vnd.oasis.opendocument.formula-template', '', '');
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('odg', 'application/vnd.oasis.opendocument.graphics', 'mime-type-vector.png', ''),
('otg', 'application/vnd.oasis.opendocument.graphics-template', '', ''),
('odi', 'application/vnd.oasis.opendocument.image', '', ''),
('oti', 'application/vnd.oasis.opendocument.image-template', '', ''),
('odp', 'application/vnd.oasis.opendocument.presentation', 'mime-type-presentation.png', 'far file-powerpoint'),
('otp', 'application/vnd.oasis.opendocument.presentation-template', '', ''),
('ods', 'application/vnd.oasis.opendocument.spreadsheet', 'mime-type-spreadsheet.png', 'far file-excel'),
('ots', 'application/vnd.oasis.opendocument.spreadsheet-template', 'mime-type-spreadsheet.png', 'far file-excel'),
('odt', 'application/vnd.oasis.opendocument.text', 'mime-type-document.png', ''),
('odm', 'application/vnd.oasis.opendocument.text-master', '', ''),
('ott', 'application/vnd.oasis.opendocument.text-template', 'mime-type-document.png', ''),
('oth', 'application/vnd.oasis.opendocument.text-web', '', ''),
('xo', 'application/vnd.olpc-sugar', '', ''),
('dd2', 'application/vnd.oma.dd2+xml', '', ''),
('oxt', 'application/vnd.openofficeorg.extension', '', ''),
('pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'mime-type-presentation.png', 'far file-powerpoint'),
('sldx', 'application/vnd.openxmlformats-officedocument.presentationml.slide', '', ''),
('ppsx', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', '', ''),
('potx', 'application/vnd.openxmlformats-officedocument.presentationml.template', '', ''),
('xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mime-type-spreadsheet.png', 'far file-excel'),
('xltx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', '', ''),
('docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'mime-type-document.png', 'far file-word'),
('dotx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', '', ''),
('mgp', 'application/vnd.osgeo.mapguide.package', '', ''),
('dp', 'application/vnd.osgi.dp', '', ''),
('esa', 'application/vnd.osgi.subsystem', '', ''),
('pdb', 'application/vnd.palm', 'mime-type-document.png', ''),
('pqa', 'application/vnd.palm', '', ''),
('oprc', 'application/vnd.palm', '', ''),
('paw', 'application/vnd.pawaafile', '', ''),
('str', 'application/vnd.pg.format', '', ''),
('ei6', 'application/vnd.pg.osasli', '', ''),
('efif', 'application/vnd.picsel', '', ''),
('wg', 'application/vnd.pmi.widget', '', ''),
('plf', 'application/vnd.pocketlearn', '', ''),
('pbd', 'application/vnd.powerbuilder6', '', ''),
('box', 'application/vnd.previewsystems.box', '', ''),
('mgz', 'application/vnd.proteus.magazine', '', ''),
('qps', 'application/vnd.publishare-delta-tree', '', ''),
('ptid', 'application/vnd.pvi.ptid1', '', ''),
('qxd', 'application/vnd.quark.quarkxpress', '', ''),
('qxt', 'application/vnd.quark.quarkxpress', '', ''),
('qwd', 'application/vnd.quark.quarkxpress', '', ''),
('qwt', 'application/vnd.quark.quarkxpress', '', ''),
('qxl', 'application/vnd.quark.quarkxpress', '', ''),
('qxb', 'application/vnd.quark.quarkxpress', '', ''),
('bed', 'application/vnd.realvnc.bed', '', ''),
('mxl', 'application/vnd.recordare.musicxml', '', ''),
('musicxml', 'application/vnd.recordare.musicxml+xml', '', ''),
('cryptonote', 'application/vnd.rig.cryptonote', '', ''),
('cod', 'application/vnd.rim.cod', '', ''),
('rm', 'application/vnd.rn-realmedia', '', ''),
('rmvb', 'application/vnd.rn-realmedia-vbr', '', ''),
('link66', 'application/vnd.route66.link66+xml', '', ''),
('st', 'application/vnd.sailingtracker.track', '', ''),
('see', 'application/vnd.seemail', '', ''),
('sema', 'application/vnd.sema', '', ''),
('semd', 'application/vnd.semd', '', ''),
('semf', 'application/vnd.semf', '', ''),
('ifm', 'application/vnd.shana.informed.formdata', '', ''),
('itp', 'application/vnd.shana.informed.formtemplate', '', ''),
('iif', 'application/vnd.shana.informed.interchange', '', ''),
('ipk', 'application/vnd.shana.informed.package', '', ''),
('twd', 'application/vnd.simtech-mindmapper', '', ''),
('twds', 'application/vnd.simtech-mindmapper', '', ''),
('mmf', 'application/vnd.smaf', '', ''),
('teacher', 'application/vnd.smart.teacher', '', ''),
('sdkm', 'application/vnd.solent.sdkm+xml', '', ''),
('sdkd', 'application/vnd.solent.sdkm+xml', '', ''),
('dxp', 'application/vnd.spotfire.dxp', '', ''),
('sfs', 'application/vnd.spotfire.sfs', '', ''),
('sdc', 'application/vnd.stardivision.calc', 'mime-type-spreadsheet.png', 'far file-excel'),
('sda', 'application/vnd.stardivision.draw', '', ''),
('sdd', 'application/vnd.stardivision.impress', 'mime-type-presentation.png', 'far file-powerpoint'),
('smf', 'application/vnd.stardivision.math', '', ''),
('sdw', 'application/vnd.stardivision.writer', 'mime-type-document.png', ''),
('vor', 'application/vnd.stardivision.writer', '', ''),
('sgl', 'application/vnd.stardivision.writer-global', '', ''),
('smzip', 'application/vnd.stepmania.package', '', ''),
('sm', 'application/vnd.stepmania.stepchart', '', ''),
('sxc', 'application/vnd.sun.xml.calc', 'mime-type-spreadsheet.png', 'far file-excel'),
('stc', 'application/vnd.sun.xml.calc.template', 'mime-type-spreadsheet.png', 'far file-excel'),
('sxd', 'application/vnd.sun.xml.draw', 'mime-type-vector.png', ''),
('std', 'application/vnd.sun.xml.draw.template', '', ''),
('sxi', 'application/vnd.sun.xml.impress', 'mime-type-presentation.png', 'far file-powerpoint'),
('sti', 'application/vnd.sun.xml.impress.template', 'mime-type-presentation.png', 'far file-powerpoint'),
('sxm', 'application/vnd.sun.xml.math', '', ''),
('sxw', 'application/vnd.sun.xml.writer', 'mime-type-document.png', ''),
('sxg', 'application/vnd.sun.xml.writer.global', '', ''),
('stw', 'application/vnd.sun.xml.writer.template', 'mime-type-document.png', ''),
('sus', 'application/vnd.sus-calendar', '', ''),
('susp', 'application/vnd.sus-calendar', '', ''),
('svd', 'application/vnd.svd', '', ''),
('sis', 'application/vnd.symbian.install', '', ''),
('sisx', 'application/vnd.symbian.install', '', ''),
('xsm', 'application/vnd.syncml+xml', '', ''),
('bdm', 'application/vnd.syncml.dm+wbxml', '', ''),
('xdm', 'application/vnd.syncml.dm+xml', '', ''),
('tao', 'application/vnd.tao.intent-module-archive', '', ''),
('pcap', 'application/vnd.tcpdump.pcap', '', ''),
('cap', 'application/vnd.tcpdump.pcap', '', ''),
('dmp', 'application/vnd.tcpdump.pcap', '', ''),
('tmo', 'application/vnd.tmobile-livetv', '', ''),
('tpt', 'application/vnd.trid.tpt', '', ''),
('mxs', 'application/vnd.triscape.mxs', '', ''),
('tra', 'application/vnd.trueapp', '', ''),
('ufd', 'application/vnd.ufdl', '', ''),
('ufdl', 'application/vnd.ufdl', '', ''),
('utz', 'application/vnd.uiq.theme', '', ''),
('umj', 'application/vnd.umajin', '', ''),
('unityweb', 'application/vnd.unity', '', ''),
('uoml', 'application/vnd.uoml+xml', '', ''),
('vcx', 'application/vnd.vcx', '', ''),
('vsd', 'application/vnd.visio', '', ''),
('vst', 'application/vnd.visio', '', ''),
('vss', 'application/vnd.visio', 'mime-type-vector.png', ''),
('vsw', 'application/vnd.visio', '', ''),
('vis', 'application/vnd.visionary', '', ''),
('vsf', 'application/vnd.vsf', '', ''),
('wbxml', 'application/vnd.wap.wbxml', '', ''),
('wmlc', 'application/vnd.wap.wmlc', '', ''),
('wmlsc', 'application/vnd.wap.wmlscriptc', '', ''),
('wtb', 'application/vnd.webturbo', '', ''),
('nbp', 'application/vnd.wolfram.player', '', ''),
('wpd', 'application/vnd.wordperfect', '', ''),
('wqd', 'application/vnd.wqd', '', ''),
('stf', 'application/vnd.wt.stf', '', ''),
('xar', 'application/vnd.xara', '', ''),
('xfdl', 'application/vnd.xfdl', '', ''),
('hvd', 'application/vnd.yamaha.hv-dic', '', ''),
('hvs', 'application/vnd.yamaha.hv-script', '', ''),
('hvp', 'application/vnd.yamaha.hv-voice', '', ''),
('osf', 'application/vnd.yamaha.openscoreformat', '', ''),
('osfpvg', 'application/vnd.yamaha.openscoreformat.osfpvg+xml', '', ''),
('saf', 'application/vnd.yamaha.smaf-audio', '', ''),
('spf', 'application/vnd.yamaha.smaf-phrase', '', ''),
('cmp', 'application/vnd.yellowriver-custom-menu', '', ''),
('zir', 'application/vnd.zul', '', ''),
('zirz', 'application/vnd.zul', '', ''),
('zaz', 'application/vnd.zzazz.deck+xml', '', ''),
('vxml', 'application/voicexml+xml', '', ''),
('wgt', 'application/widget', '', ''),
('hlp', 'application/winhlp', '', ''),
('wsdl', 'application/wsdl+xml', '', ''),
('wspolicy', 'application/wspolicy+xml', '', ''),
('7z', 'application/x-7z-compressed', 'mime-type-archive.png', 'far file-archive'),
('abw', 'application/x-abiword', '', ''),
('ace', 'application/x-ace-compressed', 'mime-type-archive.png', 'far file-archive'),
('dmg', 'application/x-apple-diskimage', '', ''),
('aab', 'application/x-authorware-bin', '', ''),
('x32', 'application/x-authorware-bin', '', ''),
('u32', 'application/x-authorware-bin', '', ''),
('vox', 'application/x-authorware-bin', '', ''),
('aam', 'application/x-authorware-map', '', ''),
('aas', 'application/x-authorware-seg', '', ''),
('bcpio', 'application/x-bcpio', '', ''),
('torrent', 'application/x-bittorrent', '', ''),
('blb', 'application/x-blorb', '', ''),
('blorb', 'application/x-blorb', '', ''),
('bz', 'application/x-bzip', '', ''),
('bz2', 'application/x-bzip2', 'mime-type-archive.png', 'far file-archive'),
('boz', 'application/x-bzip2', '', ''),
('cbr', 'application/x-cbr', '', ''),
('cba', 'application/x-cbr', '', ''),
('cbt', 'application/x-cbr', '', ''),
('cbz', 'application/x-cbr', '', ''),
('cb7', 'application/x-cbr', '', ''),
('vcd', 'application/x-cdlink', '', ''),
('cfs', 'application/x-cfs-compressed', '', ''),
('chat', 'application/x-chat', '', ''),
('pgn', 'application/x-chess-pgn', '', ''),
('nsc', 'application/x-conference', '', ''),
('cpio', 'application/x-cpio', '', ''),
('csh', 'application/x-csh', '', 'far file-code'),
('deb', 'application/x-debian-package', '', ''),
('udeb', 'application/x-debian-package', '', ''),
('dgc', 'application/x-dgc-compressed', '', ''),
('dir', 'application/x-director', '', ''),
('dcr', 'application/x-director', '', ''),
('dxr', 'application/x-director', '', ''),
('cst', 'application/x-director', '', ''),
('cct', 'application/x-director', '', ''),
('cxt', 'application/x-director', '', '');
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('w3d', 'application/x-director', '', ''),
('fgd', 'application/x-director', '', ''),
('swa', 'application/x-director', '', ''),
('wad', 'application/x-doom', '', ''),
('ncx', 'application/x-dtbncx+xml', '', ''),
('dtb', 'application/x-dtbook+xml', '', ''),
('res', 'application/x-dtbresource+xml', '', ''),
('dvi', 'application/x-dvi', '', ''),
('evy', 'application/x-envoy', '', ''),
('eva', 'application/x-eva', '', ''),
('bdf', 'application/x-font-bdf', '', ''),
('gsf', 'application/x-font-ghostscript', '', ''),
('psf', 'application/x-font-linux-psf', '', ''),
('otf', 'application/x-font-otf', '', ''),
('pcf', 'application/x-font-pcf', '', ''),
('snf', 'application/x-font-snf', '', ''),
('ttf', 'application/x-font-ttf', '', ''),
('ttc', 'application/x-font-ttf', '', ''),
('pfa', 'application/x-font-type1', '', ''),
('pfb', 'application/x-font-type1', '', ''),
('pfm', 'application/x-font-type1', '', ''),
('afm', 'application/x-font-type1', '', ''),
('woff', 'application/x-font-woff', '', ''),
('arc', 'application/x-freearc', '', ''),
('spl', 'application/x-futuresplash', '', ''),
('gca', 'application/x-gca-compressed', '', ''),
('ulx', 'application/x-glulx', '', ''),
('gnumeric', 'application/x-gnumeric', '', ''),
('gramps', 'application/x-gramps-xml', '', ''),
('gtar', 'application/x-gtar', '', ''),
('hdf', 'application/x-hdf', '', ''),
('install', 'application/x-install-instructions', '', ''),
('iso', 'application/x-iso9660-image', '', ''),
('jnlp', 'application/x-java-jnlp-file', '', ''),
('latex', 'application/x-latex', '', ''),
('lzh', 'application/x-lzh-compressed', '', ''),
('lha', 'application/x-lzh-compressed', '', ''),
('mie', 'application/x-mie', '', ''),
('prc', 'application/x-mobipocket-ebook', '', ''),
('mobi', 'application/x-mobipocket-ebook', '', ''),
('application', 'application/x-ms-application', '', ''),
('lnk', 'application/x-ms-shortcut', '', ''),
('wmd', 'application/x-ms-wmd', '', ''),
('wmz', 'application/x-ms-wmz', '', ''),
('xbap', 'application/x-ms-xbap', '', ''),
('mdb', 'application/x-msaccess', '', ''),
('obd', 'application/x-msbinder', '', ''),
('crd', 'application/x-mscardfile', '', ''),
('clp', 'application/x-msclip', '', ''),
('exe', 'application/x-msdownload', '', ''),
('dll', 'application/x-msdownload', '', ''),
('com', 'application/x-msdownload', '', ''),
('bat', 'application/x-msdownload', '', 'far file-code'),
('msi', 'application/x-msdownload', '', ''),
('mvb', 'application/x-msmediaview', '', ''),
('m13', 'application/x-msmediaview', '', ''),
('m14', 'application/x-msmediaview', '', ''),
('wmf', 'application/x-msmetafile', '', ''),
('emf', 'application/x-msmetafile', '', ''),
('emz', 'application/x-msmetafile', '', ''),
('mny', 'application/x-msmoney', '', ''),
('pub', 'application/x-mspublisher', '', ''),
('scd', 'application/x-msschedule', '', ''),
('trm', 'application/x-msterminal', '', ''),
('wri', 'application/x-mswrite', '', ''),
('nc', 'application/x-netcdf', '', ''),
('cdf', 'application/x-netcdf', '', ''),
('nzb', 'application/x-nzb', '', ''),
('p12', 'application/x-pkcs12', '', ''),
('pfx', 'application/x-pkcs12', '', ''),
('p7b', 'application/x-pkcs7-certificates', '', ''),
('spc', 'application/x-pkcs7-certificates', '', ''),
('p7r', 'application/x-pkcs7-certreqresp', '', ''),
('rar', 'application/x-rar-compressed', 'mime-type-archive.png', 'far file-archive'),
('ris', 'application/x-research-info-systems', '', ''),
('sh', 'application/x-sh', '', 'far file-code'),
('shar', 'application/x-shar', '', ''),
('swf', 'application/x-shockwave-flash', '', ''),
('xap', 'application/x-silverlight-app', '', ''),
('sql', 'text/x-sql', '', 'far file-code'),
('sit', 'application/x-stuffit', '', ''),
('sitx', 'application/x-stuffitx', '', ''),
('srt', 'application/x-subrip', '', ''),
('sv4cpio', 'application/x-sv4cpio', '', ''),
('sv4crc', 'application/x-sv4crc', '', ''),
('t3', 'application/x-t3vm-image', '', ''),
('gam', 'application/x-tads', '', ''),
('tar', 'application/x-tar', 'mime-type-archive.png', 'far file-archive'),
('tcl', 'application/x-tcl', '', ''),
('tex', 'application/x-tex', '', ''),
('tfm', 'application/x-tex-tfm', '', ''),
('texinfo', 'application/x-texinfo', '', ''),
('texi', 'application/x-texinfo', '', ''),
('obj', 'application/x-tgif', '', ''),
('ustar', 'application/x-ustar', '', ''),
('src', 'application/x-wais-source', '', 'far file-code'),
('der', 'application/x-x509-ca-cert', '', ''),
('crt', 'application/x-x509-ca-cert', '', ''),
('fig', 'application/x-xfig', '', ''),
('xlf', 'application/x-xliff+xml', '', ''),
('xpi', 'application/x-xpinstall', '', ''),
('xz', 'application/x-xz', '', ''),
('z1', 'application/x-zmachine', '', ''),
('z2', 'application/x-zmachine', '', ''),
('z3', 'application/x-zmachine', '', ''),
('z4', 'application/x-zmachine', '', ''),
('z5', 'application/x-zmachine', '', ''),
('z6', 'application/x-zmachine', '', ''),
('z7', 'application/x-zmachine', '', ''),
('z8', 'application/x-zmachine', '', ''),
('xaml', 'application/xaml+xml', '', ''),
('xdf', 'application/xcap-diff+xml', '', ''),
('xenc', 'application/xenc+xml', '', ''),
('xhtml', 'application/xhtml+xml', '', 'far file-code'),
('xht', 'application/xhtml+xml', '', ''),
('xml', 'application/xml', '', 'far file-code'),
('xsl', 'application/xml', '', 'far file-code'),
('dtd', 'application/xml-dtd', '', 'far file-code'),
('xop', 'application/xop+xml', '', ''),
('xpl', 'application/xproc+xml', '', ''),
('xslt', 'application/xslt+xml', '', 'far file-code'),
('xspf', 'application/xspf+xml', '', ''),
('mxml', 'application/xv+xml', '', ''),
('xhvml', 'application/xv+xml', '', ''),
('xvml', 'application/xv+xml', '', ''),
('xvm', 'application/xv+xml', '', ''),
('yang', 'application/yang', '', ''),
('yin', 'application/yin+xml', '', ''),
('zip', 'application/zip', 'mime-type-archive.png', 'far file-archive'),
('adp', 'audio/adpcm', 'mime-type-audio.png', 'far file-audio'),
('au', 'audio/basic', 'mime-type-audio.png', 'far file-audio'),
('snd', 'audio/basic', 'mime-type-audio.png', 'far file-audio'),
('mid', 'audio/midi', 'mime-type-audio.png', 'far file-audio'),
('midi', 'audio/midi', 'mime-type-audio.png', 'far file-audio'),
('kar', 'audio/midi', 'mime-type-audio.png', 'far file-audio'),
('rmi', 'audio/midi', 'mime-type-audio.png', 'far file-audio'),
('m4a', 'audio/mp4', 'mime-type-audio.png', 'far file-audio'),
('mp4a', 'audio/mp4', 'mime-type-audio.png', 'far file-audio'),
('m4p', 'audio/mp4a-latm', 'mime-type-audio.png', 'far file-audio'),
('mpga', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('mp2', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('mp2a', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('mp3', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('m2a', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('m3a', 'audio/mpeg', 'mime-type-audio.png', 'far file-audio'),
('oga', 'audio/ogg', 'mime-type-audio.png', 'far file-audio'),
('ogg', 'audio/ogg', 'mime-type-audio.png', 'far file-audio'),
('spx', 'audio/ogg', 'mime-type-audio.png', 'far file-audio'),
('s3m', 'audio/s3m', 'mime-type-audio.png', 'far file-audio'),
('sil', 'audio/silk', 'mime-type-audio.png', 'far file-audio'),
('uva', 'audio/vnd.dece.audio', 'mime-type-audio.png', 'far file-audio'),
('uvva', 'audio/vnd.dece.audio', 'mime-type-audio.png', 'far file-audio'),
('eol', 'audio/vnd.digital-winds', 'mime-type-audio.png', 'far file-audio'),
('dra', 'audio/vnd.dra', 'mime-type-audio.png', 'far file-audio'),
('dts', 'audio/vnd.dts', 'mime-type-audio.png', 'far file-audio'),
('dtshd', 'audio/vnd.dts.hd', 'mime-type-audio.png', 'far file-audio'),
('lvp', 'audio/vnd.lucent.voice', 'mime-type-audio.png', 'far file-audio'),
('pya', 'audio/vnd.ms-playready.media.pya', 'mime-type-audio.png', 'far file-audio'),
('ecelp4800', 'audio/vnd.nuera.ecelp4800', 'mime-type-audio.png', 'far file-audio'),
('ecelp7470', 'audio/vnd.nuera.ecelp7470', 'mime-type-audio.png', 'far file-audio'),
('ecelp9600', 'audio/vnd.nuera.ecelp9600', 'mime-type-audio.png', 'far file-audio'),
('rip', 'audio/vnd.rip', 'mime-type-audio.png', 'far file-audio'),
('weba', 'audio/webm', 'mime-type-audio.png', 'far file-audio'),
('aac', 'audio/x-aac', 'mime-type-audio.png', 'far file-audio'),
('aif', 'audio/x-aiff', 'mime-type-audio.png', 'far file-audio'),
('aiff', 'audio/x-aiff', 'mime-type-audio.png', 'far file-audio'),
('aifc', 'audio/x-aiff', 'mime-type-audio.png', 'far file-audio'),
('caf', 'audio/x-caf', 'mime-type-audio.png', 'far file-audio'),
('flac', 'audio/x-flac', 'mime-type-audio.png', 'far file-audio'),
('mka', 'audio/x-matroska', 'mime-type-audio.png', 'far file-audio'),
('m3u', 'audio/x-mpegurl', 'mime-type-audio.png', 'far file-audio'),
('wax', 'audio/x-ms-wax', 'mime-type-audio.png', 'far file-audio'),
('wma', 'audio/x-ms-wma', 'mime-type-audio.png', 'far file-audio'),
('ram', 'audio/x-pn-realaudio', 'mime-type-audio.png', 'far file-audio'),
('ra', 'audio/x-pn-realaudio', 'mime-type-audio.png', 'far file-audio'),
('rmp', 'audio/x-pn-realaudio-plugin', 'mime-type-audio.png', 'far file-audio'),
('wav', 'audio/x-wav', 'mime-type-audio.png', 'far file-audio'),
('xm', 'audio/xm', 'mime-type-audio.png', 'far file-audio'),
('cdx', 'chemical/x-cdx', 'mime-type-vector.png', ''),
('cif', 'chemical/x-cif', '', ''),
('cmdf', 'chemical/x-cmdf', '', ''),
('cml', 'chemical/x-cml', '', ''),
('csml', 'chemical/x-csml', '', ''),
('xyz', 'chemical/x-xyz', '', ''),
('bmp', 'image/bmp', 'mime-type-image.png', 'far file-image'),
('cgm', 'image/cgm', 'mime-type-image.png', 'far file-image'),
('g3', 'image/g3fax', 'mime-type-image.png', 'far file-image'),
('gif', 'image/gif', 'mime-type-image.png', 'far file-image'),
('ief', 'image/ief', 'mime-type-image.png', 'far file-image'),
('jp2', 'image/jp2', 'mime-type-image.png', 'far file-image'),
('jpeg', 'image/jpeg', 'mime-type-image.png', 'far file-image'),
('jpg', 'image/jpeg', 'mime-type-image.png', 'far file-image'),
('jpe', 'image/jpeg', 'mime-type-image.png', 'far file-image'),
('ktx', 'image/ktx', 'mime-type-image.png', 'far file-image'),
('pict', 'image/pict', 'mime-type-image.png', 'far file-image'),
('pic', 'image/pict', 'mime-type-image.png', 'far file-image'),
('pct', 'image/pict', 'mime-type-image.png', 'far file-image'),
('png', 'image/png', 'mime-type-png.png', 'far file-image'),
('btif', 'image/prs.btif', 'mime-type-image.png', 'far file-image'),
('sgi', 'image/sgi', 'mime-type-image.png', 'far file-image');
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('svg', 'image/svg+xml', 'mime-type-image.png', 'far file-image'),
('svgz', 'image/svg+xml', 'mime-type-image.png', 'far file-image'),
('tiff', 'image/tiff', 'mime-type-image.png', 'far file-image'),
('tif', 'image/tiff', 'mime-type-image.png', 'far file-image'),
('psd', 'image/vnd.adobe.photoshop', 'mime-type-psd.png', 'far file-image'),
('uvi', 'image/vnd.dece.graphic', 'mime-type-image.png', 'far file-image'),
('uvvi', 'image/vnd.dece.graphic', 'mime-type-image.png', 'far file-image'),
('uvg', 'image/vnd.dece.graphic', 'mime-type-image.png', 'far file-image'),
('uvvg', 'image/vnd.dece.graphic', 'mime-type-image.png', 'far file-image'),
('sub', 'image/vnd.dvb.subtitle', 'mime-type-image.png', 'far file-image'),
('djvu', 'image/vnd.djvu', 'mime-type-image.png', 'far file-image'),
('djv', 'image/vnd.djvu', 'mime-type-image.png', 'far file-image'),
('dwg', 'image/vnd.dwg', 'mime-type-image.png', 'far file-image'),
('dxf', 'image/vnd.dxf', 'mime-type-image.png', 'far file-image'),
('fbs', 'image/vnd.fastbidsheet', 'mime-type-image.png', 'far file-image'),
('fpx', 'image/vnd.fpx', 'mime-type-image.png', 'far file-image'),
('fst', 'image/vnd.fst', 'mime-type-image.png', 'far file-image'),
('mmr', 'image/vnd.fujixerox.edmics-mmr', 'mime-type-image.png', 'far file-image'),
('rlc', 'image/vnd.fujixerox.edmics-rlc', 'mime-type-image.png', 'far file-image'),
('mdi', 'image/vnd.ms-modi', 'mime-type-image.png', 'far file-image'),
('wdp', 'image/vnd.ms-photo', 'mime-type-image.png', 'far file-image'),
('npx', 'image/vnd.net-fpx', 'mime-type-image.png', 'far file-image'),
('wbmp', 'image/vnd.wap.wbmp', 'mime-type-image.png', 'far file-image'),
('xif', 'image/vnd.xiff', 'mime-type-image.png', 'far file-image'),
('webp', 'image/webp', 'mime-type-image.png', 'far file-image'),
('3ds', 'image/x-3ds', 'mime-type-image.png', 'far file-image'),
('ras', 'image/x-cmu-raster', 'mime-type-image.png', 'far file-image'),
('cmx', 'image/x-cmx', 'mime-type-image.png', 'far file-image'),
('fh', 'image/x-freehand', 'mime-type-image.png', 'far file-image'),
('fhc', 'image/x-freehand', 'mime-type-image.png', 'far file-image'),
('fh4', 'image/x-freehand', 'mime-type-image.png', 'far file-image'),
('fh5', 'image/x-freehand', 'mime-type-image.png', 'far file-image'),
('fh7', 'image/x-freehand', 'mime-type-image.png', 'far file-image'),
('ico', 'image/x-icon', 'mime-type-image.png', 'far file-image'),
('pntg', 'image/x-macpaint', 'mime-type-image.png', 'far file-image'),
('pnt', 'image/x-macpaint', 'mime-type-image.png', 'far file-image'),
('mac', 'image/x-macpaint', 'mime-type-image.png', 'far file-image'),
('sid', 'image/x-mrsid-image', 'mime-type-image.png', 'far file-image'),
('pcx', 'image/x-pcx', 'mime-type-image.png', 'far file-image'),
('pnm', 'image/x-portable-anymap', 'mime-type-image.png', 'far file-image'),
('pbm', 'image/x-portable-bitmap', 'mime-type-image.png', 'far file-image'),
('pgm', 'image/x-portable-graymap', 'mime-type-image.png', 'far file-image'),
('ppm', 'image/x-portable-pixmap', 'mime-type-image.png', 'far file-image'),
('qtif', 'image/x-quicktime', 'mime-type-image.png', 'far file-image'),
('qti', 'image/x-quicktime', 'mime-type-image.png', 'far file-image'),
('rgb', 'image/x-rgb', 'mime-type-image.png', 'far file-image'),
('tga', 'image/x-tga', 'mime-type-image.png', 'far file-image'),
('xbm', 'image/x-xbitmap', 'mime-type-image.png', 'far file-image'),
('xpm', 'image/x-xpixmap', 'mime-type-image.png', 'far file-image'),
('xwd', 'image/x-xwindowdump', 'mime-type-image.png', 'far file-image'),
('eml', 'message/rfc822', '', ''),
('mime', 'message/rfc822', '', ''),
('igs', 'model/iges', '', ''),
('iges', 'model/iges', '', ''),
('msh', 'model/mesh', '', ''),
('mesh', 'model/mesh', '', ''),
('silo', 'model/mesh', '', ''),
('dae', 'model/vnd.collada+xml', '', ''),
('dwf', 'model/vnd.dwf', '', ''),
('gdl', 'model/vnd.gdl', '', ''),
('gtw', 'model/vnd.gtw', '', ''),
('mts', 'model/vnd.mts', '', ''),
('vtu', 'model/vnd.vtu', '', ''),
('wrl', 'model/vrml', '', ''),
('vrml', 'model/vrml', '', ''),
('x3db', 'model/x3d+binary', '', ''),
('x3dbz', 'model/x3d+binary', '', ''),
('x3dv', 'model/x3d+vrml', '', ''),
('x3dvz', 'model/x3d+vrml', '', ''),
('x3d', 'model/x3d+xml', '', ''),
('x3dz', 'model/x3d+xml', '', ''),
('manifest', 'text/cache-manifest', '', 'far file-alt'),
('appcache', 'text/cache-manifest', '', 'far file-alt'),
('ics', 'text/calendar', '', 'far file-alt'),
('ifb', 'text/calendar', '', 'far file-alt'),
('css', 'text/css', '', 'far file-code'),
('csv', 'text/csv', 'mime-type-spreadsheet.png', 'far file-excel'),
('html', 'text/html', '', 'far file-code'),
('htm', 'text/html', '', 'far file-code'),
('n3', 'text/n3', '', 'far file-alt'),
('txt', 'text/plain', 'mime-type-document.png', 'far file-alt'),
('text', 'text/plain', '', 'far file-alt'),
('conf', 'text/plain', '', 'far file-alt'),
('def', 'text/plain', '', 'far file-alt'),
('list', 'text/plain', '', 'far file-alt'),
('log', 'text/plain', '', 'far file-alt'),
('in', 'text/plain', '', 'far file-alt'),
('dsc', 'text/prs.lines.tag', '', 'far file-alt'),
('rtx', 'text/richtext', '', 'far file-alt'),
('sgml', 'text/sgml', '', 'far file-alt'),
('sgm', 'text/sgml', '', 'far file-alt'),
('tsv', 'text/tab-separated-values', '', 'far file-alt'),
('t', 'text/troff', '', 'far file-alt'),
('tr', 'text/troff', '', 'far file-alt'),
('roff', 'text/troff', '', 'far file-alt'),
('man', 'text/troff', '', 'far file-alt'),
('me', 'text/troff', '', 'far file-alt'),
('ms', 'text/troff', '', 'far file-alt'),
('ttl', 'text/turtle', '', 'far file-code'),
('uri', 'text/uri-list', '', 'far file-alt'),
('uris', 'text/uri-list', '', 'far file-alt'),
('urls', 'text/uri-list', '', 'far file-alt'),
('address-card', 'text/vcard', '', 'far file-alt'),
('curl', 'text/vnd.curl', '', 'far file-alt'),
('dcurl', 'text/vnd.curl.dcurl', '', 'far file-alt'),
('scurl', 'text/vnd.curl.scurl', '', 'far file-alt'),
('mcurl', 'text/vnd.curl.mcurl', '', 'far file-alt'),
('fly', 'text/vnd.fly', '', 'far file-alt'),
('flx', 'text/vnd.fmi.flexstor', '', 'far file-alt'),
('gv', 'text/vnd.graphviz', '', 'far file-alt'),
('3dml', 'text/vnd.in3d.3dml', '', 'far file-alt'),
('spot', 'text/vnd.in3d.spot', '', 'far file-alt'),
('jad', 'text/vnd.sun.j2me.app-descriptor', '', 'far file-alt'),
('wml', 'text/vnd.wap.wml', '', 'far file-alt'),
('wmls', 'text/vnd.wap.wmlscript', '', 'far file-alt'),
('s', 'text/x-asm', '', 'far file-alt'),
('asm', 'text/x-asm', '', 'far file-code'),
('c', 'text/x-c', '', 'far file-code'),
('far closed-captioning', 'text/x-c', '', 'far file-code'),
('cxx', 'text/x-c', '', 'far file-code'),
('cpp', 'text/x-c', '', 'far file-code'),
('h', 'text/x-c', '', 'far file-code'),
('hh', 'text/x-c', '', 'far file-code'),
('dic', 'text/x-c', '', 'far file-alt'),
('f', 'text/x-fortran', '', 'far file-code'),
('for', 'text/x-fortran', '', 'far file-code'),
('f77', 'text/x-fortran', '', 'far file-alt'),
('f90', 'text/x-fortran', '', 'far file-alt'),
('java', 'text/x-java-source', '', 'far file-code'),
('opml', 'text/x-opml', '', 'far file-alt'),
('p', 'text/x-pascal', '', 'far file-alt'),
('pas', 'text/x-pascal', '', 'far file-code'),
('php', 'application/x-httpd-php', '', 'far file-code'),
('coffee', 'text/x-coffeescript', '', 'far file-code'),
('lsp', 'text/x-common-lisp', '', 'far file-code'),
('lisp', 'text/x-common-lisp', '', 'far file-code'),
('diff', 'text/x-diff', '', 'far file-code'),
('go', 'text/x-go', '', 'far file-code'),
('lua', 'text/x-lua', '', 'far file-code'),
('pl', 'text/x-perl', '', 'far file-code'),
('prl', 'text/x-perl', '', 'far file-code'),
('perl', 'text/x-perl', '', 'far file-code'),
('py', 'text/x-python', '', 'far file-code'),
('nginx', 'text/nginx', '', 'far file-code'),
('ini', 'text/x-ini', '', 'far file-alt'),
('rb', 'text/x-ruby', '', 'far file-code'),
('sass', 'text/x-sass', '', 'far file-code'),
('bash', 'text/x-sh', '', 'far file-code'),
('swift', 'text/x-swift', '', 'far file-code'),
('vb', 'text/x-vb', '', 'far file-code'),
('vbs', 'text/vbscript', '', 'far file-code'),
('vue', 'text/x-vue', '', 'far file-code'),
('yaml', 'text/x-yaml', '', 'far file-alt'),
('md', 'text/x-markdown', '', 'far file-alt'),
('xq', 'application/xquery', '', 'far file-code'),
('xquery', 'application/xquery', '', 'far file-code'),
('ps1', 'application/x-powershell', '', 'far file-code'),
('aps', 'application/x-aspx', '', ''),
('jsp', 'application/x-jsp', '', 'far file-code'),
('nfo', 'text/x-nfo', '', 'far file-alt'),
('etx', 'text/x-setext', '', 'far file-alt'),
('sfv', 'text/x-sfv', '', 'far file-alt'),
('uu', 'text/x-uuencode', '', 'far file-alt'),
('vcs', 'text/x-vcalendar', '', 'far file-alt'),
('vcf', 'text/x-vcard', '', 'far file-alt'),
('3gp', 'video/3gpp', 'mime-type-video.png', 'far file-video'),
('3g2', 'video/3gpp2', 'mime-type-video.png', 'far file-video'),
('h261', 'video/h261', 'mime-type-video.png', 'far file-video'),
('h263', 'video/h263', 'mime-type-video.png', 'far file-video'),
('h264', 'video/h264', 'mime-type-video.png', 'far file-video'),
('jpgv', 'video/jpeg', 'mime-type-video.png', 'far file-video'),
('jpm', 'video/jpm', 'mime-type-video.png', 'far file-video'),
('jpgm', 'video/jpm', 'mime-type-video.png', 'far file-video'),
('mj2', 'video/mj2', 'mime-type-video.png', 'far file-video'),
('mjp2', 'video/mj2', 'mime-type-video.png', 'far file-video'),
('ts', 'video/mp2t', 'mime-type-video.png', 'far file-video'),
('mp4', 'video/mp4', 'mime-type-video.png', 'far file-video'),
('mp4v', 'video/mp4', 'mime-type-video.png', 'far file-video'),
('mpg4', 'video/mp4', 'mime-type-video.png', 'far file-video'),
('m4v', 'video/mp4', 'mime-type-video.png', 'far file-video'),
('mpeg', 'video/mpeg', 'mime-type-video.png', 'far file-video'),
('mpg', 'video/mpeg', 'mime-type-video.png', 'far file-video'),
('mpe', 'video/mpeg', 'mime-type-video.png', 'far file-video'),
('m1v', 'video/mpeg', 'mime-type-video.png', 'far file-video'),
('m2v', 'video/mpeg', 'mime-type-video.png', 'far file-video'),
('ogv', 'video/ogg', 'mime-type-video.png', 'far file-video'),
('qt', 'video/quicktime', 'mime-type-video.png', 'far file-video'),
('mov', 'video/quicktime', 'mime-type-video.png', 'far file-video'),
('uvh', 'video/vnd.dece.hd', 'mime-type-video.png', 'far file-video'),
('uvvh', 'video/vnd.dece.hd', 'mime-type-video.png', 'far file-video'),
('uvm', 'video/vnd.dece.mobile', 'mime-type-video.png', 'far file-video'),
('uvvm', 'video/vnd.dece.mobile', 'mime-type-video.png', 'far file-video'),
('uvp', 'video/vnd.dece.pd', 'mime-type-video.png', 'far file-video'),
('uvvp', 'video/vnd.dece.pd', 'mime-type-video.png', 'far file-video');
INSERT INTO `sys_storage_mime_types` (`ext`, `mime_type`, `icon`, `icon_font`) VALUES
('uvs', 'video/vnd.dece.sd', 'mime-type-video.png', 'far file-video'),
('uvvs', 'video/vnd.dece.sd', 'mime-type-video.png', 'far file-video'),
('uvv', 'video/vnd.dece.video', 'mime-type-video.png', 'far file-video'),
('uvvv', 'video/vnd.dece.video', 'mime-type-video.png', 'far file-video'),
('dvb', 'video/vnd.dvb.file', 'mime-type-video.png', 'far file-video'),
('fvt', 'video/vnd.fvt', 'mime-type-video.png', 'far file-video'),
('mxu', 'video/vnd.mpegurl', 'mime-type-video.png', 'far file-video'),
('m4u', 'video/vnd.mpegurl', 'mime-type-video.png', 'far file-video'),
('pyv', 'video/vnd.ms-playready.media.pyv', 'mime-type-video.png', 'far file-video'),
('uvu', 'video/vnd.uvvu.mp4', 'mime-type-video.png', 'far file-video'),
('uvvu', 'video/vnd.uvvu.mp4', 'mime-type-video.png', 'far file-video'),
('viv', 'video/vnd.vivo', 'mime-type-video.png', 'far file-video'),
('dv', 'video/x-dv', 'mime-type-video.png', 'far file-video'),
('dif', 'video/x-dv', 'mime-type-video.png', 'far file-excel'),
('webm', 'video/webm', 'mime-type-video.png', 'far file-video'),
('f4v', 'video/x-f4v', 'mime-type-video.png', 'far file-video'),
('fli', 'video/x-fli', 'mime-type-video.png', 'far file-video'),
('flv', 'video/x-flv', 'mime-type-video.png', 'far file-video'),
('mkv', 'video/x-matroska', 'mime-type-video.png', 'far file-video'),
('mk3d', 'video/x-matroska', 'mime-type-video.png', 'far file-video'),
('mks', 'video/x-matroska', 'mime-type-video.png', 'far file-video'),
('mng', 'video/x-mng', 'mime-type-video.png', 'far file-video'),
('asf', 'video/x-ms-asf', 'mime-type-video.png', 'far file-video'),
('asx', 'video/x-ms-asf', 'mime-type-video.png', 'far file-video'),
('vob', 'video/x-ms-vob', 'mime-type-video.png', 'far file-video'),
('wm', 'video/x-ms-wm', 'mime-type-video.png', 'far file-video'),
('wmv', 'video/x-ms-wmv', 'mime-type-video.png', 'far file-video'),
('wmx', 'video/x-ms-wmx', 'mime-type-video.png', 'far file-video'),
('wvx', 'video/x-ms-wvx', 'mime-type-video.png', 'far file-video'),
('avi', 'video/x-msvideo', 'mime-type-video.png', 'far file-video'),
('movie', 'video/x-sgi-movie', 'mime-type-video.png', 'far file-video'),
('smv', 'video/x-smv', 'mime-type-video.png', 'far file-video'),
('ice', 'x-conference/x-cooltalk', '', '');

-- Forms

UPDATE `sys_form_inputs` SET `checker_func` = 'Preg', `checker_params` = 'a:1:{s:4:"preg";s:38:"~^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}~";}' WHERE `object` = 'sys_account' AND `name` = 'password';

-- Menu templates

DELETE FROM `sys_menu_templates` WHERE `template` IN('menu_profile_stats.html', 'menu_interactive.html');

SET @iMax = (SELECT MAX(`id`) FROM `sys_menu_templates`);
UPDATE `sys_menu_templates` SET `id` = @iMax + 1 WHERE `id` = 21;
UPDATE `sys_menu_templates` SET `id` = @iMax + 2 WHERE `id` = 22;

INSERT INTO `sys_menu_templates` (`id`, `template`, `title`, `visible`) VALUES
(21, 'menu_profile_stats.html', '_sys_menu_template_title_profile_stats', 0),
(22, 'menu_interactive.html', '_sys_menu_template_title_interactive', 1);

-- Menus

UPDATE `sys_objects_menu` SET `template_id` = 21 WHERE `object` = 'sys_profile_stats' AND `template_id` = 6;

DELETE FROM `sys_objects_menu` WHERE `object` = 'sys_create_post';
INSERT INTO `sys_objects_menu` (`object`, `title`, `set_name`, `module`, `template_id`, `deletable`, `active`, `override_class_name`, `override_class_file`) VALUES
('sys_create_post', '_sys_menu_title_create_post', 'sys_add_content_links', 'system', 22, 0, 1, 'BxTemplMenuCreatePost', '');

-- Menu items

UPDATE `sys_menu_items` SET `icon` = 'tachometer-alt' WHERE `set_name` = 'sys_account_notifications' AND `name` = 'dashboard';
UPDATE `sys_menu_items` SET `icon` = 'sign-out-alt' WHERE `set_name` = 'sys_account_notifications' AND `name` = 'logout';

UPDATE `sys_menu_items` SET `icon` = 'tachometer-alt' WHERE `set_name` = 'sys_account_dashboard' AND `name` = 'dashboard';

UPDATE `sys_menu_items` SET `icon` = 'pencil-alt' WHERE `set_name` = 'sys_cmts_item_manage' AND `name` = 'item-edit';

DELETE FROM `sys_menu_items` WHERE `set_name` = 'sys_cmts_item_actions' AND `name` IN('item-vote', 'item-score', 'item-reply', 'item-more');
INSERT INTO `sys_menu_items`(`set_name`, `module`, `name`, `title_system`, `title`, `link`, `onclick`, `target`, `icon`, `addon`, `submenu_object`, `submenu_popup`, `visible_for_levels`, `active`, `copyable`, `editable`, `order`) VALUES 
('sys_cmts_item_actions', 'system', 'item-vote', '_sys_menu_item_title_system_cmts_item_vote', '_sys_menu_item_title_cmts_item_vote', 'javascript:void(0)', '', '', '', '', '', 0, 2147483647, 1, 0, 1, 1),
('sys_cmts_item_actions', 'system', 'item-score', '_sys_menu_item_title_system_cmts_item_score', '_sys_menu_item_title_cmts_item_score', 'javascript:void(0)', '', '', '', '', '', 0, 2147483647, 0, 0, 1, 2),
('sys_cmts_item_actions', 'system', 'item-reply', '_sys_menu_item_title_system_cmts_item_reply', '_sys_menu_item_title_cmts_item_reply', 'javascript:void(0)', 'javascript:{reply_onclick}', '_self', 'reply', '', '', 0, 2147483647, 1, 0, 1, 3),
('sys_cmts_item_actions', 'system', 'item-more', '_sys_menu_item_title_system_cmts_item_more', '_sys_menu_item_title_cmts_item_more', 'javascript:void(0)', 'bx_menu_popup(''sys_cmts_item_manage'', this, {''id'':''sys_cmts_item_manage_{cmt_system}_{cmt_id}''}, {cmt_system:''{cmt_system}'', cmt_object_id:{cmt_object_id}, cmt_id:{cmt_id}});', '', 'ellipsis-h', '', 'sys_cmts_item_manage', 1, 2147483647, 1, 0, 1, 4);

UPDATE `sys_menu_items` SET `icon` = 'fab facebook-f' WHERE `set_name` = 'sys_social_sharing' AND `name` = 'social-sharing-facebook';
UPDATE `sys_menu_items` SET `icon` = 'fab google-plus-g' WHERE `set_name` = 'sys_social_sharing' AND `name` = 'social-sharing-googleplus';
UPDATE `sys_menu_items` SET `icon` = 'fab twitter' WHERE `set_name` = 'sys_social_sharing' AND `name` = 'social-sharing-twitter';
UPDATE `sys_menu_items` SET `icon` = 'fab pinterest' WHERE `set_name` = 'sys_social_sharing' AND `name` = 'social-sharing-pinterest';

DELETE FROM `sys_menu_items` WHERE `set_name` = 'sys_account_dashboard_manage_tools' AND `name` = 'cmts-administration';
INSERT INTO `sys_menu_items`(`set_name`, `module`, `name`, `title_system`, `title`, `link`, `onclick`, `target`, `icon`, `addon`, `submenu_object`, `visible_for_levels`, `active`, `copyable`, `order`) VALUES 
('sys_account_dashboard_manage_tools', 'system', 'cmts-administration', '_sys_menu_item_title_system_cmts_administration', '_sys_menu_item_title_cmts_administration', 'page.php?i=cmts-administration', '', '', '', 'a:2:{s:6:"module";s:6:"system";s:6:"method";s:27:"get_menu_addon_manage_tools";}', '', 192, 1, 0, 1);

DELETE FROM `sys_menu_items` WHERE `set_name` = 'sys_profile_stats' AND `name` = 'profile-stats-profile';
INSERT INTO `sys_menu_items` (`set_name`, `module`, `name`, `title_system`, `title`, `link`, `onclick`, `target`, `icon`, `addon`, `submenu_object`, `visible_for_levels`, `active`, `copyable`, `order`) VALUES
('sys_profile_stats', 'system', 'profile-stats-profile', '_sys_menu_item_title_system_profile', '_sys_menu_item_title_profile', '{member_url}', '', '', 'user', 'a:4:{s:6:"module";s:6:"system";s:6:"method";s:27:"get_menu_addon_profile_edit";s:6:"params";a:0:{}s:5:"class";s:20:"TemplServiceProfiles";}', '', 2147483646, 1, 0, 0);

-- GRIDS: moderation tools

DELETE FROM `sys_objects_grid` WHERE `object` = 'sys_cmts_administration';
INSERT INTO `sys_objects_grid` (`object`, `source_type`, `source`, `table`, `field_id`, `field_order`, `field_active`, `paginate_url`, `paginate_per_page`, `paginate_simple`, `paginate_get_start`, `paginate_get_per_page`, `filter_fields`, `filter_fields_translatable`, `filter_mode`, `sorting_fields`, `sorting_fields_translatable`, `visible_for_levels`, `override_class_name`, `override_class_file`) VALUES
('sys_cmts_administration', 'Sql', '', '', 'cmt_id', 'cmt_time', '', '', 20, NULL, 'start', '', 'cmt_text', '', 'like', 'reports', '', 192, 'BxTemplCmtsGridAdministration', '');

DELETE FROM `sys_grid_fields` WHERE `object` = 'sys_cmts_administration';
INSERT INTO `sys_grid_fields` (`object`, `name`, `title`, `width`, `translatable`, `chars_limit`, `params`, `order`) VALUES
('sys_cmts_administration', 'checkbox', '_sys_select', '2%', 0, '0', '', 1),
('sys_cmts_administration', 'reports', '_sys_txt_reports_title', '5%', 0, '0', '', 2),
('sys_cmts_administration', 'cmt_text', '_sys_cmts_administration_grid_column_title_adm_cmt_text', '33%', 0, '25', '', 3),
('sys_cmts_administration', 'cmt_time', '_sys_cmts_administration_grid_column_title_adm_cmt_time', '20%', 1, '25', '', 4),
('sys_cmts_administration', 'cmt_author_id', '_sys_cmts_administration_grid_column_title_adm_cmt_author_id', '20%', 0, '25', '', 5),
('sys_cmts_administration', 'actions', '', '20%', 0, '', '', 6);

DELETE FROM `sys_grid_actions` WHERE `object` = 'sys_cmts_administration';
INSERT INTO `sys_grid_actions` (`object`, `type`, `name`, `title`, `icon`, `icon_only`, `confirm`, `order`) VALUES
('sys_cmts_administration', 'bulk', 'delete', '_sys_cmts_administration_grid_action_title_adm_delete', '', 0, 1, 1),
('sys_cmts_administration', 'single', 'delete', '_sys_cmts_administration_grid_action_title_adm_delete', 'remove', 1, 1, 1);

-- Pages

DELETE FROM `sys_objects_page` WHERE `object` = 'sys_cmts_administration';
INSERT INTO `sys_objects_page` (`object`, `uri`, `title_system`, `title`, `module`, `layout_id`, `visible_for_levels`, `visible_for_levels_editable`, `url`, `meta_description`, `meta_keywords`, `meta_robots`, `cache_lifetime`, `cache_editable`, `deletable`, `override_class_name`, `override_class_file`) VALUES
('sys_cmts_administration' ,'cmts-administration', '_sys_page_title_system_cmts_administration', '_sys_page_title_cmts_administration', 'system', 5, 192, 1, 'page.php?i=cmts-administration', '', '', '', 0, 1, 0, '', '');

-- Pages types

CREATE TABLE IF NOT EXISTS `sys_pages_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `template` varchar(255) NOT NULL,
  `order` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

TRUNCATE TABLE `sys_pages_types`;
INSERT INTO `sys_pages_types` (`id`, `title`, `template`, `order`) VALUES
(1, '_sys_page_type_default', 'default.html', 1),
(2, '_sys_page_type_default_wo_hf', 'page_2.html', 2);

-- Pages blocks

DELETE FROM `sys_pages_blocks` WHERE `module` = 'system' AND `title_system` IN('_sys_page_block_title_sys_create_post_public', '_sys_page_block_title_sys_create_post_context');
SET @iBlockOrder = IFNULL((SELECT `order` FROM `sys_pages_blocks` WHERE `object` = '' AND `cell_id` = 0 ORDER BY `order` DESC LIMIT 1), 0);
INSERT INTO `sys_pages_blocks` (`object`, `cell_id`, `module`, `title_system`, `title`, `designbox_id`, `visible_for_levels`, `type`, `content`, `deletable`, `copyable`, `active`, `order`) VALUES
('', 0, 'system', '_sys_page_block_title_sys_create_post_public', '_sys_page_block_title_create_post_public', 3, 2147483647, 'service', 'a:4:{s:6:"module";s:6:"system";s:6:"method";s:20:"get_create_post_form";s:6:"params";a:0:{}s:5:"class";s:13:"TemplServices";}', 0, 1, 1, @iBlockOrder + 1),
('', 0, 'system', '_sys_page_block_title_sys_create_post_context', '_sys_page_block_title_create_post_context', 3, 2147483647, 'service', 'a:4:{s:6:"module";s:6:"system";s:6:"method";s:20:"get_create_post_form";s:6:"params";a:1:{i:0;s:12:"{profile_id}";}s:5:"class";s:13:"TemplServices";}', 0, 1, 1, @iBlockOrder + 2);

DELETE FROM `sys_pages_blocks` WHERE `object` = 'sys_cmts_administration' AND `title_system` IN('_sys_page_block_title_system_cmts_administration');
INSERT INTO `sys_pages_blocks` (`object`, `cell_id`, `module`, `title_system`, `title`, `designbox_id`, `visible_for_levels`, `type`, `content`, `deletable`, `copyable`, `active`, `order`) VALUES
('sys_cmts_administration', 1, 'system', '_sys_page_block_title_system_cmts_administration', '_sys_page_block_title_cmts_administration', 11, 192, 'service', 'a:4:{s:6:"module";s:6:"system";s:6:"method";s:12:"manage_tools";s:6:"params";a:1:{i:0;s:14:"administration";}s:5:"class";s:17:"TemplCmtsServices";}', 0, 1, 1, 1);

-- ICONS

UPDATE `sys_menu_items` SET `icon` = 'file-alt col-red3' WHERE `icon` = 'file-text col-red3';
UPDATE `sys_menu_items` SET `icon` = 'far clock col-green1' WHERE `icon` = 'clock-o col-green1';
UPDATE `sys_menu_items` SET `icon` = 'users col-red2' WHERE `icon` = 'group col-red2';
UPDATE `sys_menu_items` SET `icon` = 'users col-blue3' WHERE `icon` = 'group col-blue3';
UPDATE `sys_menu_items` SET `icon` = 'far comments col-blue2' WHERE `icon` = 'comments-o col-blue2';
UPDATE `sys_menu_items` SET `icon` = 'far file col-red3' WHERE `icon` = 'file-o col-red3';
UPDATE `sys_menu_items` SET `icon` = 'far envelope' WHERE `icon` = 'envelope-o';
UPDATE `sys_menu_items` SET `icon` = 'far trash-alt' WHERE `icon` = 'trash-o';
UPDATE `sys_menu_items` SET `icon` = 'pencil-alt' WHERE `icon` = 'pencil';
UPDATE `sys_menu_items` SET `icon` = 'thumbtack' WHERE `icon` = 'thumb-tack';
UPDATE `sys_menu_items` SET `icon` = 'far smile' WHERE `icon` = 'smile-o';
UPDATE `sys_menu_items` SET `icon` = 'video' WHERE `icon` = 'video-camera';


UPDATE `sys_grid_actions` SET `icon` = 'pencil-alt' WHERE `icon` = 'pencil';
UPDATE `sys_grid_actions` SET `icon` = 'far check-square' WHERE `icon` = 'check-square-o';
UPDATE `sys_grid_actions` SET `icon` = 'unlink' WHERE `icon` = 'chain-broken';


UPDATE `sys_statistics` SET `icon` = 'file-alt col-red3' WHERE `icon` = 'file-text col-red3';
UPDATE `sys_statistics` SET `icon` = 'users col-red2' WHERE `icon` = 'group col-red2';
UPDATE `sys_statistics` SET `icon` = 'far comments col-blue2' WHERE `icon` = 'comments-o col-blue2';
UPDATE `sys_statistics` SET `icon` = 'far file col-red3' WHERE `icon` = 'file-o col-red3';


UPDATE `sys_objects_auths` SET `Icon` = 'sign-in-alt' WHERE `Icon` = 'sign-in';
UPDATE `sys_objects_auths` SET `Icon` = 'fab facebook-square' WHERE `Icon` = 'facebook-square';
UPDATE `sys_objects_auths` SET `Icon` = 'fab google-plus-square' WHERE `Icon` = 'google-plus-square';
UPDATE `sys_objects_auths` SET `Icon` = 'fab linkedin-in' WHERE `Icon` = 'linkedin';
UPDATE `sys_objects_auths` SET `Icon` = 'fab twitter' WHERE `Icon` = 'twitter';


-- Last step is to update current version

UPDATE `sys_modules` SET `version` = '9.0.0-RC9' WHERE (`version` = '9.0.0.RC8' OR `version` = '9.0.0-RC8') AND `name` = 'system';

