tinymce.addI18n('es_AR',{
"Cut": "Cortar",
"Heading 5": "Encabezado 5",
"Header 2": "Cabecera 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Tu navegador no soporta el acceso directo al portapapeles. Por favor, utiliza los atajos de teclados Ctrl+X\/C\/V.",
"Heading 4": "Encabezado 4",
"Div": "Div",
"Heading 2": "Encabezado 2",
"Paste": "Pegar",
"Close": "Cerrar",
"Font Family": "Fuente",
"Pre": "Pre",
"Align right": "Alinear a Derecha",
"New document": "Nuevo documento",
"Blockquote": "Cita de bloque",
"Numbered list": "Lista numerada",
"Heading 1": "Encabezado 1",
"Headings": "Encabezados",
"Increase indent": "Incrementar indentaci\u00f3n",
"Formats": "Formatos",
"Headers": "Cabeceras",
"Select all": "Seleccionar todo",
"Header 3": "Cabecera 3",
"Blocks": "Bloques",
"Undo": "Deshacer",
"Strikethrough": "Tachado",
"Bullet list": "Lista de Vi\u00f1etas",
"Header 1": "Cabecera 1",
"Superscript": "Super\u00edndice",
"Clear formatting": "Limpiar formateado",
"Font Sizes": "Tama\u00f1o de Fuente",
"Subscript": "Sub\u00edndice",
"Header 6": "Cabecera 6",
"Redo": "Rehacer",
"Paragraph": "P\u00e1rrafo",
"Ok": "Ok",
"Bold": "Negrita",
"Code": "C\u00f3digo",
"Italic": "It\u00e1lica",
"Align center": "Alinear al Centro",
"Header 5": "Cabecera 5",
"Heading 6": "Encabezado 6",
"Heading 3": "Encabezado 3",
"Decrease indent": "Disminuir indentaci\u00f3n",
"Header 4": "Cabecera 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Pegar est\u00e1 ahora en modo de texto plano. El contenido no ser\u00e1 pegado como texto plano hasta que desactives esta opci\u00f3n.",
"Underline": "Subrayado",
"Cancel": "Cancelar",
"Justify": "Justificar",
"Inline": "En l\u00ednea",
"Copy": "Copiar",
"Align left": "Alinear a Izquierda",
"Visual aids": "Ayudas Visuales",
"Special character": "Caracter Especial",
"Source code": "C\u00f3digo Fuente",
"Emoticons": "Emoticones",
"Fullscreen": "Pantalla Completa",
"Horizontal line": "L\u00ednea Horizontal",
"Horizontal space": "Espacio Horizontal",
"B": "B",
"Insert\/edit image": "Insertar\/Editar Imagen",
"General": "General",
"Advanced": "Avanzado",
"G": "G",
"R": "R",
"Source": "Fuente",
"Border": "Borde",
"Constrain proportions": "Restricciones de proporci\u00f3n",
"Vertical space": "Espacio Vertical",
"Image description": "Descripci\u00f3n",
"Style": "Estilo",
"Dimensions": "Dimensiones",
"Insert image": "Insertar Imagen",
"Insert date\/time": "Insertar Fecha\/hora",
"Page break": "Salto de p\u00e1gina",
"Preview": "Previzualizaci\u00f3n",
"Print": "Imprimir",
"Save": "Guardar",
"Show blocks": "Mostrar bloques",
"Show invisible characters": "Mostrar caracteres invisibles",
"Words: {0}": "Palabras:{0}"
});