<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twilio\\' => array($vendorDir . '/twilio/sdk/src/Twilio'),
    'Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'Spatie\\CalendarLinks\\' => array($vendorDir . '/spatie/calendar-links/src'),
    'Snipe\\BanBuilder\\' => array($vendorDir . '/snipe/banbuilder/src'),
    'Sample\\' => array($vendorDir . '/paypal/paypal-checkout-sdk/samples'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src', $vendorDir . '/psr/http-factory/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'PayPalHttp\\' => array($vendorDir . '/paypal/paypalhttp/lib/PayPalHttp'),
    'PayPalCheckoutSdk\\' => array($vendorDir . '/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'MatthiasMullie\\PathConverter\\' => array($vendorDir . '/matthiasmullie/path-converter/src'),
    'MatthiasMullie\\Minify\\' => array($vendorDir . '/matthiasmullie/minify/src'),
    'Intervention\\Image\\' => array($vendorDir . '/intervention/image/src/Intervention/Image'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Facebook\\' => array($vendorDir . '/facebook/graph-sdk/src/Facebook'),
    'Embera\\' => array($vendorDir . '/mpratt/embera/src/Embera'),
    'ChargeBee\\' => array($vendorDir . '/chargebee/chargebee-php/lib'),
    'AvtoDev\\Composer\\Cleanup\\' => array($vendorDir . '/avto-dev/composer-cleanup-plugin/src'),
    'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\' => array($vendorDir . '/akeeba/s3/src'),
);
