<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'cd93af16a1e273b377937e63f3987d34a9722148',
        'name' => 'unaio/una',
        'dev' => true,
    ),
    'versions' => array(
        'achingbrain/php5-akismet' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../achingbrain/php5-akismet',
            'aliases' => array(),
            'reference' => 'master',
            'dev_requirement' => false,
        ),
        'akeeba/s3' => array(
            'pretty_version' => 'dev-development',
            'version' => 'dev-development',
            'type' => 'library',
            'install_path' => __DIR__ . '/../akeeba/s3',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '0c20807b1bfb9d955f9464c26b63f23fc17614ab',
            'dev_requirement' => false,
        ),
        'avto-dev/composer-cleanup-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../avto-dev/composer-cleanup-plugin',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '75187ca4854265174021765e3b67cb973dc37723',
            'dev_requirement' => false,
        ),
        'bshaffer/oauth2-server-php' => array(
            'pretty_version' => 'v1.12.1',
            'version' => '1.12.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bshaffer/oauth2-server-php',
            'aliases' => array(),
            'reference' => '2bfaf9d7bbebe2ba1c1deb48e756ba0b3af4e985',
            'dev_requirement' => false,
        ),
        'chargebee/chargebee-php' => array(
            'pretty_version' => 'v3.7.0',
            'version' => '3.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chargebee/chargebee-php',
            'aliases' => array(),
            'reference' => '22d5eba6f874939e0f7e3ab13efc112d48236c5e',
            'dev_requirement' => false,
        ),
        'curl/cacert' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../curl/cacert',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '6598f3860c2698fe2f0f1bc98212fc01d0a1893c',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'dev_requirement' => false,
        ),
        'ffmpeg/ffmpeg' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ffmpeg/ffmpeg',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.5',
            'version' => '7.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '1dd98b0564cb3f6bd16ce683cb755f94c10fbd82',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '13388f00956b1503577598873fffb5ae994b5737',
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'v0.8.11',
            'version' => '0.8.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(),
            'reference' => 'fc11a53db4b66da555a6a11fce294f574a8374f9',
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.68',
            'version' => '1.3.68.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'reference' => 'c00fb02f71b2ef0a5f53fe18c5a8b9aa30f48297',
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.26',
            'version' => '2.0.26.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'reference' => 'd0f4fd8550ca07bd2efb55211c8f66b73db77f99',
            'dev_requirement' => false,
        ),
        'paypal/paypal-checkout-sdk' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypal-checkout-sdk',
            'aliases' => array(),
            'reference' => '19992ce7051ff9e47e643f28abb8cc1b3e5f1812',
            'dev_requirement' => false,
        ),
        'paypal/paypalhttp' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypalhttp',
            'aliases' => array(),
            'reference' => '7b09c89c80828e842c79230e7f156b61fbb68d25',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.3',
            'version' => '6.6.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => '9400f305a898f194caff5521f64e5dfa926626f3',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'snipe/banbuilder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../snipe/banbuilder',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '621d6d857400983d0fd6cd291f105a835a317748',
            'dev_requirement' => false,
        ),
        'spatie/calendar-links' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/calendar-links',
            'aliases' => array(),
            'reference' => 'bb96f1db8478009ad8f206a3bafb2b9aa6b648c3',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v7.128.0',
            'version' => '7.128.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => 'c704949c49b72985c76cc61063aa26fefbd2724e',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'tpyo/amazon-s3-php-class' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tpyo/amazon-s3-php-class',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '7c62b0e9b7d956a04e377ca236979a78dbac4e66',
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '5.42.2',
            'version' => '5.42.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'reference' => '0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
            'dev_requirement' => false,
        ),
        'unaio/amazon-s3-php-class-hmac-v2' => array(
            'pretty_version' => '0.6',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unaio/amazon-s3-php-class-hmac-v2',
            'aliases' => array(),
            'reference' => '3687dec0af7be2cb11f21828aa4b12d20c4c5935',
            'dev_requirement' => false,
        ),
        'unaio/una' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'cd93af16a1e273b377937e63f3987d34a9722148',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'dev_requirement' => false,
        ),
    ),
);
