const { theme } = require('app/design/tailwind/theme')
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    '../../packages/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    // Card component density classes
    'u-card-base-compact',
    'u-card-base-default', 
    'u-card-base-relaxed',
    'u-card-header-compact',
    'u-card-header-default',
    'u-card-header-relaxed',
    'u-card-title-compact',
    'u-card-title-default',
    'u-card-title-relaxed',
    'u-card-description-compact',
    'u-card-description-default',
    'u-card-description-relaxed',
    'u-card-content-compact',
    'u-card-content-default',
    'u-card-content-relaxed',
    'u-card-footer-compact',
    'u-card-footer-default',
    'u-card-footer-relaxed',
    'u-card-icon-compact',
    'u-card-icon-default',
    'u-card-icon-relaxed',
    // Block component density classes
    'u-block-base-compact',
    'u-block-base-default', 
    'u-block-base-relaxed',
    'u-block-header-compact',
    'u-block-header-default',
    'u-block-header-relaxed',
    'u-block-name-compact',
    'u-block-name-default',
    'u-block-name-relaxed',
    'u-block-title-compact',
    'u-block-title-default',
    'u-block-title-relaxed',
    'u-block-description-compact',
    'u-block-description-default',
    'u-block-description-relaxed',
    'u-block-content-compact',
    'u-block-content-default',
    'u-block-content-relaxed',
    'u-block-footer-compact',
    'u-block-footer-default',
    'u-block-footer-relaxed',
    'u-block-icon-compact',
    'u-block-icon-default',
    'u-block-icon-relaxed',
    'u-block-actions-compact',
    'u-block-actions-default',
    'u-block-actions-relaxed',
    // Panel component density classes
    'u-panel-base-compact',
    'u-panel-base-default',
    'u-panel-base-relaxed',
    'u-panel-handler-compact',
    'u-panel-handler-default',
    'u-panel-handler-relaxed',
    'u-panel-group-compact',
    'u-panel-group-default',
    'u-panel-group-relaxed',
    // Content padding density classes
    'u-content-padding-compact',
    'u-content-padding-default',
    'u-content-padding-relaxed',
    // Density-aware padding utilities
    'p-sm',
    'p-md',
    'p-lg',
    'px-sm',
    'px-md',
    'px-lg',
    'py-sm',
    'py-md',
    'py-lg',
    'pt-sm',
    'pt-md',
    'pt-lg',
    'pb-sm',
    'pb-md',
    'pb-lg',
    // Density-aware gap utilities
    'gap-sm',
    'gap-md',
    'gap-lg',
    // Badge component density classes
    'u-badge-base-compact',
    'u-badge-base-default',
    'u-badge-base-relaxed',
    'u-badge-default-compact',
    'u-badge-default-default',
    'u-badge-default-relaxed',
    'u-badge-secondary-compact',
    'u-badge-secondary-default',
    'u-badge-secondary-relaxed',
    'u-badge-destructive-compact',
    'u-badge-destructive-default',
    'u-badge-destructive-relaxed',
    'u-badge-accent-compact',
    'u-badge-accent-default',
    'u-badge-accent-relaxed',
    'u-badge-outline-compact',
    'u-badge-outline-default',
    'u-badge-outline-relaxed',
    'u-badge-text-compact',
    'u-badge-text-default',
    'u-badge-text-relaxed',
    'u-badge-text-default-compact',
    'u-badge-text-default-default',
    'u-badge-text-default-relaxed',
    'u-badge-text-secondary-compact',
    'u-badge-text-secondary-default',
    'u-badge-text-secondary-relaxed',
    'u-badge-text-destructive-compact',
    'u-badge-text-destructive-default',
    'u-badge-text-destructive-relaxed',
    'u-badge-text-accent-compact',
    'u-badge-text-accent-default',
    'u-badge-text-accent-relaxed',
    'u-badge-text-outline-compact',
    'u-badge-text-outline-default',
    'u-badge-text-outline-relaxed',
    // Table component density classes
    'u-table-base-compact',
    'u-table-base-default',
    'u-table-base-relaxed',
    'u-table-header-compact',
    'u-table-header-default',
    'u-table-header-relaxed',
    'u-table-body-compact',
    'u-table-body-default',
    'u-table-body-relaxed',
    'u-table-footer-compact',
    'u-table-footer-default',
    'u-table-footer-relaxed',
    'u-table-row-compact',
    'u-table-row-default',
    'u-table-row-relaxed',
    'u-table-head-compact',
    'u-table-head-default',
    'u-table-head-relaxed',
    'u-table-cell-compact',
    'u-table-cell-default',
    'u-table-cell-relaxed',
    'u-table-head-text-compact',
    'u-table-head-text-default',
    'u-table-head-text-relaxed',
    'u-table-cell-text-compact',
    'u-table-cell-text-default',
    'u-table-cell-text-relaxed',
    // Controls
    'u-controls-switcher-track-base',
    'u-controls-switcher-track-sm',
    'u-controls-switcher-thumb-base',
    'u-controls-switcher-thumb-sm',
    'u-controls-switcher-thumb-active-base',
    'u-controls-switcher-thumb-active-sm',
  ],
  theme: {
    ...theme,
  },
  darkMode: ['class', '[theme="dark"]'],
  important: 'html',
  presets: [require("nativewind/preset")],
  plugins: [],
  future: {hoverOnlyWhenSupported: true}
}

