
import {componentsMap} from 'app/ui/workers/_map';
import { appSetting } from 'app/lib/util'
import { useMemo } from 'react'

export default function ElementAsyncWorker(props) {
    const asyncWorkers = useMemo(() => appSetting('async_workers', 'list'), []);

    // Memoize the content generated by mapping asyncWorkers
    const newContent = useMemo(() => {
        return asyncWorkers.map((worker, index) => {
            const WorkerComponent = componentsMap[worker];
            return WorkerComponent ? <WorkerComponent key={index} /> : null;
        });
    }, [asyncWorkers]);

    return <>{newContent}</>;
}

