import { List, ArrowLeft, House, WarningCircle, ChatsCircle, ArrowRight, ChatCircleText, 
    Plus, MagnifyingGlass, User, Compass, Bell, Bookmarks, Link, UsersThree, CalendarCheck, 
    NoteBlank, Chats, Users, Info, Question, AddressBook, Pencil, ArrowCircleLeft, ArrowCircleRight, 
    ChatTeardropDots, Smiley, ShareNetwork, UserCircle, DotsThreeOutlineVertical, File, SealCheck, DotsThreeOutline,
	UserSwitch, Gear, SignOut, Files, UsersFour, CaretDoubleRight
}  
from "@phosphor-icons/react";

export const IconSet = {
	List: List,
	ArrowLeft: ArrowLeft,
	House: House,
	WarningCircle: WarningCircle,
	ChatsCircle: ChatsCircle,
	ArrowRight: ArrowRight,
	ChatCircleText: ChatCircleText,
	Plus: Plus,
	MagnifyingGlass: MagnifyingGlass,
	User: User,
	Compass: Compass,
	Bell: Bell,
	Bookmarks: Bookmarks,
	Link: Link,
	UsersThree: UsersThree,
	CalendarCheck: CalendarCheck,
	NoteBlank: NoteBlank,
	Chats: Chats,
	Users: Users,
	Info: Info,
	Question: Question,
	AddressBook: AddressBook,
	Pencil: Pencil,
	ArrowCircleLeft: ArrowCircleLeft,
	ArrowCircleRight: ArrowCircleRight,
	ChatTeardropDots: ChatTeardropDots,
	Smiley: Smiley,
	ShareNetwork: ShareNetwork,
	UserCircle: UserCircle,
	DotsThreeOutlineVertical: DotsThreeOutlineVertical,
	File: File,
	SealCheck: SealCheck,
	DotsThreeOutline: DotsThreeOutline,
	UserSwitch: UserSwitch,
	Gear: Gear,
	SignOut: SignOut,
	Files: Files, 
	UsersFour: UsersFour,
	CaretDoubleRight: CaretDoubleRight
}