'use client'

import { List, ArrowLeft, House, WarningCircle, ChatsCircle, ArrowRight, ChatCircleText, 
    Plus, MagnifyingGlass, User, Compass, Bell, Bookmarks, Link, UsersThree, CalendarCheck, 
    NoteBlank, Chats, Users, Info, Question, AddressBook, Pencil, ArrowCircleLeft, ArrowCircleRight, 
    ChatTeardropDots, Smiley, UserCircle, DotsThreeOutlineVertical, File, DotsThreeOutline,
	UserSwitch, Gear, SignOut, SignIn, Files, UsersFour, CaretDoubleRight, ArrowFatLineDown, TextB, TextItalic, TextStrikethrough,
	TextHOne, TextHTwo, TextHThree, ListBullets, ListNumbers, Quotes, ArrowUUpLeft, ArrowUUpRight, Image, Code,
	ImageSquare, PaperPlaneRight, ArrowFatUp, ArrowFatDown, SortAscending, ArrowBendLeftUp, ThumbsUp, FilePlus,	MonitorPlay, X, UserCirclePlus, RocketLaunch,
	ArrowsClockwise, Graph, ChatsTeardrop, MagicWand, Student, Handshake, At, CaretUp, CaretDown, CaretLeft, ChatCenteredText, Clipboard, CirclesFour,FileAudio, 
	DotsThreeVertical, ChatCircle, Calendar, UserPlus, Fire, Rows, Share, CheckCircle, IntersectThree, Cake, IdentificationBadge, Heart, ChartBar
}  
from "phosphor-react-native";

export const IconSet = {
	ChartBar: ChartBar,
	Heart: Heart,
	IdentificationBadge: IdentificationBadge,
	Cake: Cake,
	IntersectThree: IntersectThree,
	Rows: Rows,
	Fire: Fire,
	UserPlus: UserPlus,
	ChatCircle: ChatCircle,
	Calendar: Calendar,
	DotsThreeVertical: DotsThreeVertical,
	CirclesFour: CirclesFour,
	Clipboard: Clipboard,
	ChatCenteredText: ChatCenteredText,
	Handshake: Handshake,
	Student: Student,
	MagicWand: MagicWand,
	ChatsTeardrop: ChatsTeardrop,
	Graph: Graph,
	ArrowsClockwise: ArrowsClockwise,
	RocketLaunch: RocketLaunch,
	UserCirclePlus: UserCirclePlus,
	List: List,
	ArrowLeft: ArrowLeft,
	House: House,
	WarningCircle: WarningCircle,
	ChatsCircle: ChatsCircle,
	ArrowRight: ArrowRight,
	ChatCircleText: ChatCircleText,
	Plus: Plus,
	MagnifyingGlass: MagnifyingGlass,
	User: User,
	Compass: Compass,
	Bell: Bell,
	Bookmarks: Bookmarks,
	Link: Link,
	UsersThree: UsersThree,
	CalendarCheck: CalendarCheck,
	NoteBlank: NoteBlank,
	Chats: Chats,
	Users: Users,
	Info: Info,
	Question: Question,
	AddressBook: AddressBook,
	Pencil: Pencil,
	ArrowCircleLeft: ArrowCircleLeft,
	ArrowCircleRight: ArrowCircleRight,
	ChatTeardropDots: ChatTeardropDots,
	Smiley: Smiley,
	ShareFat: Share,
	UserCircle: UserCircle,
	DotsThreeOutlineVertical: DotsThreeOutlineVertical,
	File: File,
	SealCheck: CheckCircle,
	DotsThreeOutline: DotsThreeOutline,
	UserSwitch: UserSwitch,
	Gear: Gear,
	SignOut: SignOut,
	SignIn: SignIn,
	Files: Files, 
	UsersFour: UsersFour,
	CaretDoubleRight: CaretDoubleRight,
	ArrowFatLineDown: ArrowFatLineDown,
	TextB: TextB, 
	FileAudio: FileAudio,
	TextItalic: TextItalic, 
	TextStrikethrough: TextStrikethrough,
	TextHOne: TextHOne, 
	TextHTwo: TextHTwo, 
	TextHThree: TextHThree, 
	ListBullets:ListBullets,
	ListNumbers: ListNumbers,
	Quotes: Quotes, 
	ArrowUUpLeft: ArrowUUpLeft, 
	ArrowUUpRight: ArrowUUpRight,
	Image: Image,
	Code: Code,
	ImageSquare: ImageSquare, 
	PaperPlaneRight: PaperPlaneRight,
	ArrowFatUp: ArrowFatUp,
	ArrowFatDown: ArrowFatDown,
	SortAscending: SortAscending,
	ArrowBendLeftUp: ArrowBendLeftUp,
	ThumbsUp: ThumbsUp,
	FilePlus: FilePlus,
	MonitorPlay:MonitorPlay,
	X:X,
	At: At,
	CaretUp: CaretUp,
	CaretDown: CaretDown,
	CaretLeft: CaretLeft
}