<?php return array(
    'root' => array(
        'name' => 'unacms/una',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'b4b055f6d42d11000fb07916204ec2a52a0fef3b',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'achingbrain/php5-akismet' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'reference' => 'master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../achingbrain/php5-akismet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'akeeba/s3' => array(
            'pretty_version' => 'dev-development',
            'version' => 'dev-development',
            'reference' => '111fdfc7d2a9f9cebedf07a0300f24942f25b42d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../akeeba/s3',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'avto-dev/composer-cleanup-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '75187ca4854265174021765e3b67cb973dc37723',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../avto-dev/composer-cleanup-plugin',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'aws/aws-crt-php' => array(
            'pretty_version' => 'v1.2.7',
            'version' => '1.2.7.0',
            'reference' => 'd71d9906c7bb63a28295447ba12e74723bd3730e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-crt-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php' => array(
            'pretty_version' => '3.388.7',
            'version' => '3.388.7.0',
            'reference' => '9ad7cc3619513bb7379e2f1dc8f6763cc54dcb28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bshaffer/oauth2-server-php' => array(
            'pretty_version' => 'v1.14.2',
            'version' => '1.14.2.0',
            'reference' => '1c715c2d2f71254d1c683b8c89a0f16b61ccd0d6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bshaffer/oauth2-server-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chargebee/chargebee-php' => array(
            'pretty_version' => 'v3.51.0',
            'version' => '3.51.0.0',
            'reference' => '34746cfc45f838f735c888b00803a874b821e77d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chargebee/chargebee-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'reference' => '049509fef80032cb3f051595029ab75b49a3c2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'curl/cacert' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../curl/cacert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'elastic/transport' => array(
            'pretty_version' => 'v9.0.1',
            'version' => '9.0.1.0',
            'reference' => '3488b9d070e220f2a1ebdb500e6c588069f1897f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elastic/transport',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v9.4.0',
            'version' => '9.4.0.0',
            'reference' => '47f3edae4f6f2ecf507fe574d359839668f69525',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'enshrined/svg-sanitize' => array(
            'pretty_version' => '0.22.0',
            'version' => '0.22.0.0',
            'reference' => '0afa95ea74be155a7bcd6c6fb60c276c39984500',
            'type' => 'library',
            'install_path' => __DIR__ . '/../enshrined/svg-sanitize',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4e433a8d57078645b55d21fd12c887d3ba6ca01e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => '903161be81e9f497cc42fb7db982404a4e6441b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => 'b97f46088940671100012482577eeb59f26a13b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.19.0',
            'version' => '4.19.0.0',
            'reference' => 'b287d2a16aceffbf6e0295559b39662612b77fcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ffmpeg/ffmpeg' => array(
            'pretty_version' => '6.1.1',
            'version' => '6.1.1.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../ffmpeg/ffmpeg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.14.2',
            'version' => '7.14.2.0',
            'reference' => 'fa88c57803501ad0770f5cddb1e60525d49da9a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.5.1',
            'version' => '2.5.1.0',
            'reference' => '9ad1e4fc607446a055b95870c7f668e93b5cff29',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.12.5',
            'version' => '2.12.5.0',
            'reference' => '9365d578a9fd1552ad6ca9c3cb530708526feb09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.4.1',
            ),
        ),
        'html2text/html2text' => array(
            'pretty_version' => '4.3.2',
            'version' => '4.3.2.0',
            'reference' => '3b443cbe302b52eb5806a21a9dbd79524203970a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../html2text/html2text',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'http-interop/http-factory-guzzle' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'c2c859ceb05c3f42e710b60555f4c35b6a4a3995',
            'type' => 'library',
            'install_path' => __DIR__ . '/../http-interop/http-factory-guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'inspector-apm/inspector-php' => array(
            'pretty_version' => '3.18.0',
            'version' => '3.18.0.0',
            'reference' => '0eb86241dc91d34c6d8d84716b6d491997af1443',
            'type' => 'library',
            'install_path' => __DIR__ . '/../inspector-apm/inspector-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'knplabs/github-api' => array(
            'pretty_version' => 'v3.16.0',
            'version' => '3.16.0.0',
            'reference' => '25d7bafd6b0dd088d4850aef7fcc74dc4fba8b28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../knplabs/github-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'v0.8.11',
            'version' => '0.8.11.0',
            'reference' => 'fc11a53db4b66da555a6a11fce294f574a8374f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.75',
            'version' => '1.3.75.0',
            'reference' => '76ba4a5f555fd7bf4aa408af608e991569076671',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'reference' => 'b321dd6749f0bf7189444158a3ce785cc16d69b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.42',
            'version' => '2.0.42.0',
            'reference' => 'afa728339c6f078c803c9277a5054ca241b3c469',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => '2.9.2',
            'version' => '2.9.2.0',
            'reference' => '2157c5e50e813ec6a96c1eed3be7f64a20fb32a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neuron-core/neuron-ai' => array(
            'pretty_version' => '3.15.23',
            'version' => '3.15.23.0',
            'reference' => '83f64636516509ae7736be027a954921dc72f4b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neuron-core/neuron-ai',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nyholm/psr7' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'reference' => 'a71f2b11690f4b24d099d6b16690a90ae14fc6f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'open-telemetry/api' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '7c029c4a6fd457094a20569bf98f93d95e9a7559',
            'type' => 'library',
            'install_path' => __DIR__ . '/../open-telemetry/api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'open-telemetry/context' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '3c414b246e0dabb7d6145404e6a5e4536ca18d07',
            'type' => 'library',
            'install_path' => __DIR__ . '/../open-telemetry/context',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'opensearch-project/opensearch-php' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '6bcff126ffd8f54ca33a0dd659128cbc5d3b2bcd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opensearch-project/opensearch-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paypal/paypal-checkout-sdk' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '19992ce7051ff9e47e643f28abb8cc1b3e5f1812',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypal-checkout-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paypal/paypalhttp' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '7b09c89c80828e842c79230e7f156b61fbb68d25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypalhttp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/cache-plugin' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '1443d3882c4c18556fe9b409f664ebc8c021940c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/cache-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/client-common' => array(
            'pretty_version' => '2.7.3',
            'version' => '2.7.3.0',
            'reference' => 'dcc6de29c90dd74faab55f71b79d89409c4bf0c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/client-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.20.0',
            'version' => '1.20.0.0',
            'reference' => '82fe4c73ef3363caed49ff8dd1539ba06044910d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '5cad731844891a4c282f3f3e1b582c46839d22f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.16.2',
            'version' => '1.16.2.0',
            'reference' => '06dd5e8562f84e641bf929bfe699ee0f5ce8080a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/multipart-stream-builder' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'reference' => '10086e6de6f53489cca5ecc45b6f468604d3460e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/multipart-stream-builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/promise' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'fc85b1fba37c169a69a07ef0d5a8075770cc1f83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => '1bc1716a507a65e039d4ac9d9adebbbd0d346e15',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
                2 => '^1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '3.0.0',
            ),
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => '7.2.8',
            'version' => '7.2.8.0',
            'reference' => '4aa139ed2a2a805cd265449b691198beee1309d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => '23444f53a813a3296c1368bb104793ce8d88f04a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'snipe/banbuilder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5e76a97b3ff80e2beaae75ac140c38573ea027a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../snipe/banbuilder',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'spatie/calendar-links' => array(
            'pretty_version' => '1.11.1',
            'version' => '1.11.1.0',
            'reference' => 'bf4645d6a2d8eb32248a5b0b7da7976a13e5e2b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/calendar-links',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v19.4.1',
            'version' => '19.4.1.0',
            'reference' => '095384404587d07de2ad1154c389c4051c5ed92f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.7.1',
            'version' => '3.7.1.0',
            'reference' => 'f3202fa1b5097b0af062dc978b32ecf63404e31d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v7.4.11',
            'version' => '7.4.11.0',
            'reference' => 'd721ea61b4a5fba8c5b6e7c1feda19efea144b50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => 'v7.4.8',
            'version' => '7.4.8.0',
            'reference' => '2888fcdc4dc2fd5f7c7397be78631e8af12e02b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '141046a8f9477948ff284fa65be2095baafb94f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.38.2',
            'version' => '1.38.2.0',
            'reference' => 'd3d318bad5e7a1bfbd026009c8bfb8d8f99ae6b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => 'dfb55726c3a76ea3b6459fcfda1ec2d80a682411',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php82' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => '002dc0cfe5fd4ed6033d48f27d4f19a486c4b04b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php82',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v7.4.14',
            'version' => '7.4.14.0',
            'reference' => 'f8f328665ace2370d1e10645b807ba1646dc7dcc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tpyo/amazon-s3-php-class' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '7c62b0e9b7d956a04e377ca236979a78dbac4e66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tpyo/amazon-s3-php-class',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '8.11.6',
            'version' => '8.11.6.0',
            'reference' => '57754efb0998086007ec9a63874fd85def5afb7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typesense/typesense-php' => array(
            'pretty_version' => 'v6.0.0',
            'version' => '6.0.0.0',
            'reference' => 'e113f90449e159316a433a5509205939f271c5e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typesense/typesense-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unacms/amazon-s3-php-class-hmac-v2' => array(
            'pretty_version' => '0.6',
            'version' => '0.6.0.0',
            'reference' => '3687dec0af7be2cb11f21828aa4b12d20c4c5935',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unacms/amazon-s3-php-class-hmac-v2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unacms/una' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'b4b055f6d42d11000fb07916204ec2a52a0fef3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'reference' => 'f3e9516585fb28e5119a050e32c5a1708d9899a7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
