<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '568cee1270931708ab20fd776d4ccac37f7f467b',
        'name' => 'unaio/una',
        'dev' => true,
    ),
    'versions' => array(
        'achingbrain/php5-akismet' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../achingbrain/php5-akismet',
            'aliases' => array(),
            'reference' => 'master',
            'dev_requirement' => false,
        ),
        'akeeba/s3' => array(
            'pretty_version' => 'dev-development',
            'version' => 'dev-development',
            'type' => 'library',
            'install_path' => __DIR__ . '/../akeeba/s3',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'deeafb9e3f041c3ce851cd6abbe0fb30e6e4060d',
            'dev_requirement' => false,
        ),
        'avto-dev/composer-cleanup-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../avto-dev/composer-cleanup-plugin',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '75187ca4854265174021765e3b67cb973dc37723',
            'dev_requirement' => false,
        ),
        'bshaffer/oauth2-server-php' => array(
            'pretty_version' => 'v1.14.1',
            'version' => '1.14.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bshaffer/oauth2-server-php',
            'aliases' => array(),
            'reference' => '096db2c86a7d67a2ba45e72be7d208c342694542',
            'dev_requirement' => false,
        ),
        'chargebee/chargebee-php' => array(
            'pretty_version' => 'v3.37.0',
            'version' => '3.37.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chargebee/chargebee-php',
            'aliases' => array(),
            'reference' => '11b3d9407ed9886fee49fdda072200e62053ecc3',
            'dev_requirement' => false,
        ),
        'curl/cacert' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../curl/cacert',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '999fcf788675b65b5344e2744443fc4d5f76cc14',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.18.0',
            'version' => '4.18.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => 'cb56001e54359df7ae76dc522d08845dc741621b',
            'dev_requirement' => false,
        ),
        'ffmpeg/ffmpeg' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ffmpeg/ffmpeg',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.9.2',
            'version' => '7.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'd281ed313b989f213357e3be1a179f02196ac99b',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'f9c436286ab2892c7db7be8c8da4ef61ccf7b455',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'a70f5c95fb43bc83f07c9c948baa0dc1829bf201',
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'v0.8.11',
            'version' => '0.8.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(),
            'reference' => 'fc11a53db4b66da555a6a11fce294f574a8374f9',
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.73',
            'version' => '1.3.73.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'reference' => 'cb7a9297b4ab070909cefade30ee95054d4ae87a',
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.41',
            'version' => '2.0.41.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'reference' => '069305b9252a428ba4ae6eb58d3dc8c6d9be5cd0',
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'reference' => 'a673d5f310477027cead2e2f2b6db5d8368157cb',
            'dev_requirement' => false,
        ),
        'paypal/paypal-checkout-sdk' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypal-checkout-sdk',
            'aliases' => array(),
            'reference' => '19992ce7051ff9e47e643f28abb8cc1b3e5f1812',
            'dev_requirement' => false,
        ),
        'paypal/paypalhttp' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypalhttp',
            'aliases' => array(),
            'reference' => '7b09c89c80828e842c79230e7f156b61fbb68d25',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.3',
            'version' => '6.9.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => '2f5c94fe7493efc213f643c23b1b1c249d40f47e',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'dev_requirement' => false,
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => '7.2.6',
            'version' => '7.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'reference' => 'd89e9997191d18fb0fe03a956fa3ccfe0af524ea',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'snipe/banbuilder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../snipe/banbuilder',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '5e76a97b3ff80e2beaae75ac140c38573ea027a0',
            'dev_requirement' => false,
        ),
        'spatie/calendar-links' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/calendar-links',
            'aliases' => array(),
            'reference' => 'da41e7edae84859d3d598b0b3ce3233c843c3e46',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v7.128.0',
            'version' => '7.128.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => 'c704949c49b72985c76cc61063aa26fefbd2724e',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '74c71c939a79f7d5bf3c1ce9f5ea37ba0114c6f6',
            'dev_requirement' => false,
        ),
        'tpyo/amazon-s3-php-class' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tpyo/amazon-s3-php-class',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '7c62b0e9b7d956a04e377ca236979a78dbac4e66',
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '8.3.8',
            'version' => '8.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'reference' => 'd05c08d0b9ed017f61ebbc31bc4e5f4d758a0326',
            'dev_requirement' => false,
        ),
        'unaio/amazon-s3-php-class-hmac-v2' => array(
            'pretty_version' => '0.6',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unaio/amazon-s3-php-class-hmac-v2',
            'aliases' => array(),
            'reference' => '3687dec0af7be2cb11f21828aa4b12d20c4c5935',
            'dev_requirement' => false,
        ),
        'unaio/una' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '568cee1270931708ab20fd776d4ccac37f7f467b',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v5.1.2',
            'version' => '5.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => '39b1fbbdd3d95c5279f231d2298f3866fa869fcd',
            'dev_requirement' => false,
        ),
    ),
);
