SET @sName = 'bx_forum';


-- PAGES
DELETE FROM `sys_objects_page` WHERE `object` IN ('bx_forum_new', 'bx_forum_top', 'bx_forum_popular', 'bx_forum_updated', 'bx_forum_partaken');
DELETE FROM `sys_pages_blocks` WHERE `object` IN ('bx_forum_new', 'bx_forum_top', 'bx_forum_popular', 'bx_forum_updated', 'bx_forum_partaken');

UPDATE `sys_pages_blocks` SET `title_system`='_bx_forum_page_block_title_popular_entries_view_extended', `title`='_bx_forum_page_block_title_popular_entries' WHERE `module`=@sName AND `title`='_bx_forum_page_block_title_popular_entries_view_extended';
UPDATE `sys_pages_blocks` SET `title_system`='_bx_forum_page_block_title_latest_entries_view_gallery', `title`='_bx_forum_page_block_title_latest_entries', `content`='a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:13:\"browse_latest\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:7:\"gallery\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}' WHERE `module`=@sName AND `title`='_bx_forum_page_block_title_latest_entries';
UPDATE `sys_pages_blocks` SET `title_system`='_bx_forum_page_block_title_new_entries_view_gallery', `title`='_bx_forum_page_block_title_new_entries', `content`='a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:10:\"browse_new\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:7:\"gallery\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}' WHERE `module`=@sName AND `title`='_bx_forum_page_block_title_new_entries';
UPDATE `sys_pages_blocks` SET `title_system`='_bx_forum_page_block_title_top_entries_view_extended', `title`='_bx_forum_page_block_title_top_entries' WHERE `module`=@sName AND `title`='_bx_forum_page_block_title_top_entries_view_extended';

DELETE FROM `sys_pages_blocks` WHERE `module`=@sName AND `title` IN ('_bx_forum_page_block_title_popular_entries_view_full', '_bx_forum_page_block_title_latest_entries_view_full', '_bx_forum_page_block_title_new_entries_view_full', '_bx_forum_page_block_title_top_entries_view_full');

DELETE FROM `sys_pages_blocks` WHERE `module`=@sName AND `title_system` IN ('_bx_forum_page_block_title_popular_entries_view_showcase', '_bx_forum_page_block_title_popular_entries_view_gallery', '_bx_forum_page_block_title_featured_entries_view_extended', '_bx_forum_page_block_title_featured_entries_view_gallery');
DELETE FROM `sys_pages_blocks` WHERE `module`=@sName AND `title_system` IN ('_bx_forum_page_block_title_latest_entries_view_extended', '_bx_forum_page_block_title_latest_entries_view_showcase', '_bx_forum_page_block_title_new_entries_view_extended', '_bx_forum_page_block_title_new_entries_view_showcase');
DELETE FROM `sys_pages_blocks` WHERE `module`=@sName AND `title_system` IN ('_bx_forum_page_block_title_top_entries_view_showcase', '_bx_forum_page_block_title_top_entries_view_gallery', '_bx_forum_page_block_title_partaken_entries');
SET @iBlockOrder = (SELECT `order` FROM `sys_pages_blocks` WHERE `object` = '' AND `cell_id` = 0 ORDER BY `order` DESC LIMIT 1);
INSERT INTO `sys_pages_blocks`(`object`, `cell_id`, `module`, `title_system`, `title`, `designbox_id`, `visible_for_levels`, `type`, `content`, `deletable`, `copyable`, `order`) VALUES 
('', 0, @sName, '_bx_forum_page_block_title_popular_entries_view_showcase', '_bx_forum_page_block_title_popular_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:14:\"browse_popular\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:8:\"showcase\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 1),
('', 0, @sName, '_bx_forum_page_block_title_popular_entries_view_gallery', '_bx_forum_page_block_title_popular_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:14:\"browse_popular\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:7:\"gallery\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 2),
('', 0, @sName, '_bx_forum_page_block_title_featured_entries_view_extended', '_bx_forum_page_block_title_featured_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:15:\"browse_featured\";s:6:\"params\";a:1:{i:0;s:8:\"extended\";}}', 0, 1, IFNULL(@iBlockOrder, 0) + 3),
('', 0, @sName, '_bx_forum_page_block_title_featured_entries_view_gallery', '_bx_forum_page_block_title_featured_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:15:\"browse_featured\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:7:\"gallery\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 4),
('', 0, @sName, '_bx_forum_page_block_title_latest_entries_view_extended', '_bx_forum_page_block_title_latest_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:13:\"browse_latest\";s:6:\"params\";a:1:{i:0;s:8:\"extended\";}}', 0, 1, IFNULL(@iBlockOrder, 0) + 5),
('', 0, @sName, '_bx_forum_page_block_title_latest_entries_view_showcase', '_bx_forum_page_block_title_latest_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:13:\"browse_latest\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:8:\"showcase\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 6),
('', 0, @sName, '_bx_forum_page_block_title_new_entries_view_extended', '_bx_forum_page_block_title_new_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:10:\"browse_new\";s:6:\"params\";a:1:{i:0;s:8:\"extended\";}}', 0, 1, IFNULL(@iBlockOrder, 0) + 7),
('', 0, @sName, '_bx_forum_page_block_title_new_entries_view_showcase', '_bx_forum_page_block_title_new_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:10:\"browse_new\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:8:\"showcase\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 8),
('', 0, @sName, '_bx_forum_page_block_title_top_entries_view_showcase', '_bx_forum_page_block_title_top_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:10:\"browse_top\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:8:\"showcase\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 9),
('', 0, @sName, '_bx_forum_page_block_title_top_entries_view_gallery', '_bx_forum_page_block_title_top_entries', 11, 2147483647, 'service', 'a:3:{s:6:\"module\";s:8:\"bx_forum\";s:6:\"method\";s:10:\"browse_top\";s:6:\"params\";a:3:{s:9:\"unit_view\";s:7:\"gallery\";s:13:\"empty_message\";b:0;s:13:\"ajax_paginate\";b:0;}}', 0, 1, IFNULL(@iBlockOrder, 0) + 10),
('', 0, @sName, '_bx_forum_page_block_title_partaken_entries', '_bx_forum_page_block_title_partaken_entries', 11, 2147483647, 'service', 'a:2:{s:6:"module";s:8:"bx_forum";s:6:"method";s:15:"browse_partaken";}', 0, 1, IFNULL(@iBlockOrder, 0) + 11);


-- MENUS
UPDATE `sys_menu_items` SET `title_system`='_sys_menu_item_title_system_sm_scores', `title`='_sys_menu_item_title_sm_scores' WHERE `set_name`='bx_forum_snippet_meta_main' AND `name`='score';
