<?php

$aFilesDelete = array(
    'plugins/chargebee/chargebee-php/lib/ChargeBee/Models/InvoiceCreatedCreditNote.php',
    'plugins/chargebee/chargebee-php/lib/ChargeBee/Models/QuotedSubscriptionDiscount.php',
    'plugins/chargebee/chargebee-php/lib/ChargeBee/Curl.php',
    'plugins/guzzlehttp/psr7/vendor-bin',
    'plugins/mpratt/embera/src/Embera/Provider/CocoCorp.php',
    'plugins/mpratt/embera/src/Embera/Provider/Kidoju.php',
    'plugins/mpratt/embera/src/Embera/Provider/Minerva.php',
    'plugins/mpratt/embera/src/Embera/Provider/ModeloIO.php',
    'plugins/mpratt/embera/src/Embera/Provider/Oz.php',
    'plugins/mpratt/embera/src/Embera/Provider/Pixdor.php',
    'plugins/mpratt/embera/src/Embera/Provider/PolariShare.php',
    'plugins/mpratt/embera/src/Embera/Provider/Present.php',
    'plugins/mpratt/embera/src/Embera/Provider/Raindrop.php',
    'plugins/mpratt/embera/src/Embera/Provider/Shortnote.php',
    'plugins/mpratt/embera/src/Embera/Provider/Spotful.php',
    'plugins/mpratt/embera/src/Embera/Provider/TourHero.php',
    'plugins/mpratt/embera/src/Embera/Provider/Typlog.php',
    'plugins/mpratt/embera/src/Embera/Provider/Uppy.php',
    'plugins_public/dropzone',
    'studio/template/css/settings.css',
    'studio/template/badge_item_icon_preview.html',
    'studio/template/nav_item_icon_preview.html',
    'studio/template/prm_level_icon_preview.html',
    'studio/template/settings.html',
    'studio/template/stg_create_mix.html',
    'studio/template/stg_import_mix.html',
    'template/form_field_labels.html',
    'template/menu_main_submenu_bar.html',
    'template/menu_main_submenu_empty.html',
    'template/privacy_users_select_popup.html',
//	'plugins/phpmailer/Exception.php',
//	'plugins/phpmailer/LICENSE',
//	'plugins/phpmailer/PHPMailer.php',
//	'plugins/phpmailer/README.md',
//	'plugins/phpmailer/SMTP.php',
//	'plugins/phpmailer/VERSION',
);

