<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'a4fffc2982117ae2bb66060ab0b6cac518c5541f',
        'name' => 'unaio/una',
        'dev' => true,
    ),
    'versions' => array(
        'achingbrain/php5-akismet' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../achingbrain/php5-akismet',
            'aliases' => array(),
            'reference' => 'master',
            'dev_requirement' => false,
        ),
        'akeeba/s3' => array(
            'pretty_version' => 'dev-development',
            'version' => 'dev-development',
            'type' => 'library',
            'install_path' => __DIR__ . '/../akeeba/s3',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '982d78d9f35c15bbfeff42a5f2a6e6ac4fd60f48',
            'dev_requirement' => false,
        ),
        'avto-dev/composer-cleanup-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../avto-dev/composer-cleanup-plugin',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '75187ca4854265174021765e3b67cb973dc37723',
            'dev_requirement' => false,
        ),
        'bshaffer/oauth2-server-php' => array(
            'pretty_version' => 'v1.14.1',
            'version' => '1.14.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bshaffer/oauth2-server-php',
            'aliases' => array(),
            'reference' => '096db2c86a7d67a2ba45e72be7d208c342694542',
            'dev_requirement' => false,
        ),
        'chargebee/chargebee-php' => array(
            'pretty_version' => 'v3.23.0',
            'version' => '3.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chargebee/chargebee-php',
            'aliases' => array(),
            'reference' => 'e821b81adf4b6334c0705f1e13471abbe41e94db',
            'dev_requirement' => false,
        ),
        'curl/cacert' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../curl/cacert',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '77947eda2fdaf06b181c63a7db13e38968306aee',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.17.0',
            'version' => '4.17.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => 'bbc513d79acf6691fa9cf10f192c90dd2957f18c',
            'dev_requirement' => false,
        ),
        'ffmpeg/ffmpeg' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ffmpeg/ffmpeg',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.8.1',
            'version' => '7.8.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '41042bc7ab002487b876a0683fc8dce04ddce104',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'bbff78d96034045e58e13dedd6ad91b5d1253223',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '45b30f99ac27b5ca93cb4831afe16285f57b8221',
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'v0.8.11',
            'version' => '0.8.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(),
            'reference' => 'fc11a53db4b66da555a6a11fce294f574a8374f9',
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.71',
            'version' => '1.3.71.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'reference' => 'ae42a47d7fecc1fbb7277b2f2d84c37a33edc3b1',
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.36',
            'version' => '2.0.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'reference' => '661452ae5933ce458161faea578a59280428ca8c',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'reference' => 'e592a3e06d1fa0d43988c7c7d9948ca836f644b6',
            'dev_requirement' => false,
        ),
        'paypal/paypal-checkout-sdk' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypal-checkout-sdk',
            'aliases' => array(),
            'reference' => '19992ce7051ff9e47e643f28abb8cc1b3e5f1812',
            'dev_requirement' => false,
        ),
        'paypal/paypalhttp' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypalhttp',
            'aliases' => array(),
            'reference' => '7b09c89c80828e842c79230e7f156b61fbb68d25',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => '039de174cd9c17a8389754d3b877a2ed22743e18',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => '7.2.4',
            'version' => '7.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'reference' => 'de2f72296808f9cafa6a4462b15a768ff130cddb',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'snipe/banbuilder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../snipe/banbuilder',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '5e76a97b3ff80e2beaae75ac140c38573ea027a0',
            'dev_requirement' => false,
        ),
        'spatie/calendar-links' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/calendar-links',
            'aliases' => array(),
            'reference' => '654fc0174e6279539b9bf0abdc3339e34c5286d7',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v7.128.0',
            'version' => '7.128.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => 'c704949c49b72985c76cc61063aa26fefbd2724e',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'tpyo/amazon-s3-php-class' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tpyo/amazon-s3-php-class',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '7c62b0e9b7d956a04e377ca236979a78dbac4e66',
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '5.42.2',
            'version' => '5.42.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'reference' => '0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
            'dev_requirement' => false,
        ),
        'unaio/amazon-s3-php-class-hmac-v2' => array(
            'pretty_version' => '0.6',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unaio/amazon-s3-php-class-hmac-v2',
            'aliases' => array(),
            'reference' => '3687dec0af7be2cb11f21828aa4b12d20c4c5935',
            'dev_requirement' => false,
        ),
        'unaio/una' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'a4fffc2982117ae2bb66060ab0b6cac518c5541f',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => '7c814ca156716e7b46ad84ac038bf298ff91cbb4',
            'dev_requirement' => false,
        ),
    ),
);
