<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '03918c88d24fcbc3ab5e91cb1b15c42540fd59c4',
        'name' => 'unaio/una',
        'dev' => true,
    ),
    'versions' => array(
        'achingbrain/php5-akismet' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../achingbrain/php5-akismet',
            'aliases' => array(),
            'reference' => 'master',
            'dev_requirement' => false,
        ),
        'akeeba/s3' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../akeeba/s3',
            'aliases' => array(),
            'reference' => '96208915514b19e7789ea053c6a109b212864001',
            'dev_requirement' => false,
        ),
        'avto-dev/composer-cleanup-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../avto-dev/composer-cleanup-plugin',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '75187ca4854265174021765e3b67cb973dc37723',
            'dev_requirement' => false,
        ),
        'bshaffer/oauth2-server-php' => array(
            'pretty_version' => 'v1.11.1',
            'version' => '1.11.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bshaffer/oauth2-server-php',
            'aliases' => array(),
            'reference' => '5a0c8000d4763b276919e2106f54eddda6bc50fa',
            'dev_requirement' => false,
        ),
        'chargebee/chargebee-php' => array(
            'pretty_version' => 'v3.5.2',
            'version' => '3.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chargebee/chargebee-php',
            'aliases' => array(),
            'reference' => '46bfcbea2b341fc0da04c5944e481506d5ef29bf',
            'dev_requirement' => false,
        ),
        'curl/cacert' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../curl/cacert',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '6598f3860c2698fe2f0f1bc98212fc01d0a1893c',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'dev_requirement' => false,
        ),
        'ffmpeg/ffmpeg' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ffmpeg/ffmpeg',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.2',
            'version' => '7.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'ac1ec1cd9b5624694c3a40be801d94137afb12b4',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'c94a94f120803a18554c1805ef2e539f8285f9a2',
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.1',
            'version' => '2.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'reference' => '744ebba495319501b873a4e48787759c72e3fb8c',
            'dev_requirement' => false,
        ),
        'lusitanian/oauth' => array(
            'pretty_version' => 'v0.8.11',
            'version' => '0.8.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lusitanian/oauth',
            'aliases' => array(),
            'reference' => 'fc11a53db4b66da555a6a11fce294f574a8374f9',
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.66',
            'version' => '1.3.66.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'reference' => '45fd3b0f1dfa2c965857c6d4a470bea52adc31a6',
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.25',
            'version' => '2.0.25.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'reference' => '001d2a83e5a209432fdfb4f7f3b47c24c87a7892',
            'dev_requirement' => false,
        ),
        'paypal/paypal-checkout-sdk' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypal-checkout-sdk',
            'aliases' => array(),
            'reference' => '19992ce7051ff9e47e643f28abb8cc1b3e5f1812',
            'dev_requirement' => false,
        ),
        'paypal/paypalhttp' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/paypalhttp',
            'aliases' => array(),
            'reference' => '7b09c89c80828e842c79230e7f156b61fbb68d25',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.0',
            'version' => '6.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'e43bac82edc26ca04b36143a48bde1c051cfd5b1',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'recurly/recurly-client' => array(
            'pretty_version' => '2.10.7',
            'version' => '2.10.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../recurly/recurly-client',
            'aliases' => array(),
            'reference' => 'f60e9247b56617c9d5a9c6368b701a17b957992b',
            'dev_requirement' => false,
        ),
        'snipe/banbuilder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../snipe/banbuilder',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '621d6d857400983d0fd6cd291f105a835a317748',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v7.122.0',
            'version' => '7.122.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => 'c58179aa4cad16240a6e65dbf29c2bfd4ae0c033',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'tpyo/amazon-s3-php-class' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tpyo/amazon-s3-php-class',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '3f720a0144843c214b9444e626119dbe12ecc180',
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '5.42.2',
            'version' => '5.42.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'reference' => '0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
            'dev_requirement' => false,
        ),
        'unaio/amazon-s3-php-class-hmac-v2' => array(
            'pretty_version' => '0.5',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unaio/amazon-s3-php-class-hmac-v2',
            'aliases' => array(),
            'reference' => 'main',
            'dev_requirement' => false,
        ),
        'unaio/una' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '03918c88d24fcbc3ab5e91cb1b15c42540fd59c4',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'dev_requirement' => false,
        ),
    ),
);
