-- SETTINGS
SET @iCategId = (SELECT `id` FROM `sys_options_categories` WHERE `name`='bx_froala_general' LIMIT 1);
DELETE FROM `sys_options` WHERE `name` IN ('bx_froala_option_toolbar_mini_mobile', 'bx_froala_option_toolbar_standard_mobile', 'bx_froala_option_toolbar_full_mobile');
INSERT INTO `sys_options` (`name`, `value`, `category_id`, `caption`, `type`, `extra`, `check`, `check_params`, `check_error`, `order`) VALUES
('bx_froala_option_toolbar_mini_mobile', "{'moreText': {'buttons': ['bold', 'italic', 'underline','quote'],'buttonsVisible': 0},'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly'],'buttonsVisible': 0},'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen'],'align': 'right','buttonsVisible': 0}}", @iCategId, '_bx_froala_option_toolbar_mini_mobile', 'digit', '', '', '', '', 21),
('bx_froala_option_toolbar_standard_mobile', "{'moreText': {'buttons': ['bold', 'italic', 'underline', 'clearFormatting'],'buttonsVisible': 0},'moreParagraph': {'buttons': ['alignLeft', 'alignCenter', 'alignRight', 'formatOL', 'formatUL', 'paragraphFormat', 'outdent', 'indent', 'quote'],'buttonsVisible': 0},'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly'],'buttonsVisible': 0},'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen', 'html'],'align': 'right','buttonsVisible': 2}}", @iCategId, '_bx_froala_option_toolbar_standard_mobile', 'digit', '', '', '', '', 23),
('bx_froala_option_toolbar_full_mobile', "{'moreText': {'buttons': ['bold', 'italic', 'underline', 'strikeThrough', 'clearFormatting'], 'buttonsVisible': 0}, 'moreParagraph': {'buttons': ['alignLeft', 'alignCenter', 'alignRight', 'formatOL', 'formatUL', 'paragraphFormat', 'paragraphStyle', 'outdent', 'indent', 'quote'], 'buttonsVisible': 0}, 'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly', 'insertHR'], 'buttonsVisible': 0}, 'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen', 'html'], 'align': 'right', 'buttonsVisible': 2}}", @iCategId, '_bx_froala_option_toolbar_full_mobile', 'digit', '', '', '', '', 25);

UPDATE `sys_options` SET `value`="{'moreText': {'buttons': ['bold', 'italic', 'underline','quote'],'buttonsVisible': 2},'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly'],'buttonsVisible': 2},'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen'],'align': 'right','buttonsVisible': 0}}" WHERE `name`='bx_froala_option_toolbar_mini';
UPDATE `sys_options` SET `value`="{'moreText': {'buttons': ['bold', 'italic', 'underline', 'clearFormatting'],'buttonsVisible': 4},'moreParagraph': {'buttons': ['alignLeft', 'alignCenter', 'alignRight', 'formatOL', 'formatUL', 'paragraphFormat', 'outdent', 'indent', 'quote']},'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly'],'buttonsVisible': 2},'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen', 'html'],'align': 'right','buttonsVisible': 2}}" WHERE `name`='bx_froala_option_toolbar_standard';
UPDATE `sys_options` SET `value`="{'moreText': {'buttons': ['bold', 'italic', 'underline', 'strikeThrough', 'clearFormatting'], 'buttonsVisible': 5}, 'moreParagraph': {'buttons': ['alignLeft', 'alignCenter', 'alignRight', 'formatOL', 'formatUL', 'paragraphFormat', 'paragraphStyle', 'outdent', 'indent', 'quote']}, 'moreRich': {'buttons': ['insertLink', 'insertImage','emoticons', 'embedly', 'insertHR'], 'buttonsVisible': 5}, 'moreMisc': {'buttons': ['undo', 'redo', 'fullscreen', 'html'], 'align': 'right', 'buttonsVisible': 2}}" WHERE `name`='bx_froala_option_toolbar_full';
