<?php

$aLangContent = array(
    '_payment_pcaption_payment_result' => 'Payment Result',
    '_payment_bcaption_payment_result' => 'Payment Result',
    '_payment_details_return_url' => 'Data return URL',
    '_payment_txt_username_administrator' => 'Administrator',
    '_payment_pp_prc_type_dsc' => 'The type in which data is to be processed. In IPN mode use URL like the following http://www.your-site.com/your-path/m/payment/act_finalize_checkout/paypal as notify URL in your PayPal account',
    '_payment_pp_err_no_data_given' => 'No data given.',
    '_payment_pp_err_no_vendor_given' => 'Unknown vendor.',
    '_payment_pp_err_not_completed' => 'Payment is not completed.',
    '_payment_pp_err_wrong_business' => 'Wrong receiver email.',
    '_payment_pp_err_wrong_transaction' => 'Transaction verification failed.',
    '_payment_pp_err_wrong_verification_status' => 'No verification status received.',
    '_payment_pp_err_wrong_amount' => 'Wrong amount.',
    '_payment_pp_err_wrong_custom_data' => 'Incorrect custom data.',
    '_payment_pp_err_already_processed' => 'The payment is already processed.',
    '_payment_pp_msg_verified' => 'Successfully verified.',
    '_payment_2co_active_cpt' => 'Active',
    '_payment_2co_active_dsc' => 'Activate(Deactivate) provider',
    '_payment_2co_mode_cpt' => 'Mode',
    '_payment_2co_mode_dsc' => 'Mode to process paymments',
    '_payment_2co_mode_live' => 'live',
    '_payment_2co_mode_test' => 'test',
    '_payment_2co_account_id_cpt' => 'Account number',
    '_payment_2co_account_id_dsc' => 'Your 2Checkout vendor account number',
    '_payment_2co_payment_method_cpt' => 'Payment Method',
    '_payment_2co_payment_method_dsc' => 'This will set the default selection on the payment method step during the checkout process',
    '_payment_2co_payment_method_cc' => 'Credit Card(CC)',
    '_payment_2co_payment_method_ck' => 'Check(CK)',
    '_payment_2co_payment_method_al' => 'Acculynk PIN-debit(AL)',
    '_payment_2co_payment_method_ppi' => 'PayPal(PPI)',
    '_payment_2co_secret_word_cpt' => 'Secret Word',
    '_payment_2co_secret_word_dsc' => 'Secret word is used to calculate a check hash',
    '_payment_2co_err_no_vendor_given' => 'Unknown vendor',
    '_payment_2co_err_no_data_given' => 'No data given.',
    '_payment_2co_err_wrong_key' => 'Check key is incorrect.',
    '_payment_2co_err_wrong_payment' => 'Wrong payment amount.',
    '_payment_2co_err_already_processed' => 'The payment is already processed',
    '_payment_2co_msg_verified' => 'Successfully verified.',
);

?>
