SET @sName = 'bx_lucid';


-- MIXES
SET @iMixId = (SELECT `id` FROM `sys_options_mixes` WHERE `type`=@sName AND `name`='Light-Mix' LIMIT 1);

UPDATE `sys_options_mixes2options` SET `value`='1.0rem' WHERE `option`='bx_lucid_menu_account_font_size' AND `mix_id`=@iMixId;
UPDATE `sys_options_mixes2options` SET `value`='1.0rem' WHERE `option`='bx_lucid_menu_main_font_size' AND `mix_id`=@iMixId;
UPDATE `sys_options_mixes2options` SET `value`='div.bx-market-unit-cover div.bx-base-text-unit-no-thumb {\r\n border-width: 0px;\r\n}\r\n.bx-menu-object-UNA-Submenu {\r\nline-height: 3rem;\r\n    height: 2.5rem;\r\n}\r\nbody .bx-menu-object-UNA-Submenu .sys-icon {\r\nvertical-align:bottom;\r\n}\r\n\r\n/*--- Menus ---*/\r\n.bx-popup .bx-menu-ver li,\r\n.bx-popup .bx-menu-custom-ver li,\r\n.bx-menu-floating-blocks li {\r\nborder-radius: 0.25rem;\r\nfont-size: 0.875rem;\r\nfont-weight: 600;\r\n}\r\n\r\n.bx-popup .bx-menu-ver li a,\r\n.bx-popup .bx-menu-ver li a .sys-icon,\r\n.bx-popup .bx-menu-custom-ver li a,\r\n.bx-popup .bx-menu-custom-ver li a .sys-icon,\r\n.bx-menu-floating-blocks  li a,\r\n.bx-menu-floating-blocks li a .sys-icon:not(.sys-colored) {\r\ncolor:  rgba(60, 80, 90, 0.8);\r\n}\r\n.bx-menu-floating-blocks li a:hover,\r\n.bx-menu-floating-blocks li a:hover .sys-icon,\r\n.bx-popup .bx-menu-ver li a:hover,\r\n.bx-popup .bx-menu-ver li a:hover .sys-icon,\r\n.bx-popup .bx-menu-custom-ver li a:hover,\r\n.bx-popup .bx-menu-custom-ver li a:hover .sys-icon,\r\n.bx-menu-custom.bx-menu-custom-hor.bx-menu-more-auto .bx-menu-submenu-more-auto .bx-menu-item a:hover {\r\ncolor: rgba(64, 169, 255, 1);\r\n}\r\n\r\n/*--- Auto More  Menus ---*/\r\n.bx-menu-main-submenu.bx-menu-more-auto .bx-menu-submenu-more-auto .bx-menu-item .bx-btn,\r\n.bx-menu-custom.bx-menu-custom-hor.bx-menu-more-auto .bx-menu-submenu-more-auto .bx-menu-item a,\r\n.bx-menu-custom.bx-menu-custom-hor.bx-menu-more-auto .bx-menu-submenu-more-auto .bx-menu-item .bx-btn {\r\nfont-weight: 600;\r\ncolor:  rgba(60, 80, 90, 0.8);\r\n}\r\n\r\n/*--- Froala ---*/\r\n.bx-form-value .bx-form-input-wrapper-textarea.bx-form-input-wrapper-html {\r\n	-webkit-box-sizing: border-box;\r\n    -moz-box-sizing: border-box;\r\n    -ms-box-sizing: border-box;\r\n    box-sizing: border-box;\r\n        border: 1px solid rgba(50, 100, 180, 0.2);\r\n-webkit-border-radius: 4px;\r\n    -moz-border-radius: 4px;\r\n    border-radius: 4px;\r\nbackground-clip: padding-box;\r\nbackground-color: rgba(255, 255, 255, 0.9);\r\n    -webkit-box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0);\r\n    -moz-box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0);\r\n    box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0);\r\n}\r\n.bx-form-input-wrapper-textarea:not(.fr-fullscreen-wrapper) .fr-box.fr-basic   .fr-toolbar,\r\n.bx-form-input-wrapper-textarea:not(.fr-fullscreen-wrapper)  .fr-box.fr-basic   .fr-wrapper,\r\n.bx-form-input-wrapper-textarea:not(.fr-fullscreen-wrapper)  .fr-box.fr-basic .second-toolbar {\r\nborder-width: 0;\r\nbackground-color: transparent;\r\n}\r\n.bx-form-input-wrapper-textarea  .fr-box.fr-basic   .fr-wrapper .fr-element, \r\n.bx-form-input-wrapper-textarea  .fr-box.fr-basic   .fr-wrapper .fr-placeholder {\r\npadding-top: 0;\r\npadding-bottom:  0;\r\n}' WHERE `option`='bx_lucid_styles_custom' AND `mix_id`=@iMixId;
