SET @sName = 'bx_protean';


-- SETTINGS
SET @iCategoryId = (SELECT `id` FROM `sys_options_categories` WHERE `name`=CONCAT(@sName, '_styles_general') LIMIT 1);
DELETE FROM `sys_options` WHERE `name`=CONCAT(@sName, '_general_item_bg_color_disabled');
INSERT INTO `sys_options`(`category_id`, `name`, `caption`, `value`, `type`, `extra`, `check`, `check_params`, `check_error`, `order`) VALUES
(@iCategoryId, CONCAT(@sName, '_general_item_bg_color_disabled'), '_bx_protean_stg_cpt_option_general_item_bg_color_disabled', 'rgba(221, 221, 221, 1.0)', 'rgba', '', '', '', '', 3);

SET @iCategoryId = (SELECT `id` FROM `sys_options_categories` WHERE `name`=CONCAT(@sName, '_styles_form') LIMIT 1);
DELETE FROM `sys_options` WHERE `name`=CONCAT(@sName, '_form_input_editor_skin');
INSERT INTO `sys_options`(`category_id`, `name`, `caption`, `value`, `type`, `extra`, `check`, `check_params`, `check_error`, `order`) VALUES
(@iCategoryId, CONCAT(@sName, '_form_input_editor_skin'), '_bx_protean_stg_cpt_option_form_input_editor_skin', '', 'select', 'a:2:{s:6:"module";s:10:"bx_protean";s:6:"method";s:34:"get_options_form_input_editor_skin";}', '', '', '', 11);

UPDATE `sys_options` SET `value`='93.75%' WHERE `name`=CONCAT(@sName, '_vpt_font_size_scale');
UPDATE `sys_options` SET `value`='85%' WHERE `name`=CONCAT(@sName, '_vpm_font_size_scale');


-- MIXES
UPDATE `sys_options_mixes` SET `active`='0', `published`='0' WHERE `name`='Neat-Mix';

SET @iMixId = (SELECT `id` FROM `sys_options_mixes` WHERE `type`=@sName AND `name`='Neat-Mix' LIMIT 1);
UPDATE `sys_options_mixes2options` SET `value`='rgba(255, 255, 255, 1)' WHERE `option`='bx_protean_card_bg_color' AND `mix_id`=@iMixId;
UPDATE `sys_options_mixes2options` SET `value`='rgba(255, 255, 255, 0.5)' WHERE `option`='bx_protean_card_bg_color_hover' AND `mix_id`=@iMixId;
UPDATE `sys_options_mixes2options` SET `value`='93.75%' WHERE `option`='bx_protean_vpt_font_size_scale' AND `mix_id`=@iMixId;


DELETE FROM `tm`, `tmo` 
USING `sys_options_mixes` AS `tm`, `sys_options_mixes2options` AS `tmo`
WHERE `tm`.`id` = `tmo`.`mix_id` AND `tm`.`type`=@sName AND `tm`.`name`='Protean-Light-Mix';

INSERT INTO `sys_options_mixes` (`type`, `category`, `name`, `title`, `active`, `published`, `editable`) VALUES
(@sName, '', 'Protean-Light-Mix', 'Light Mix', 1, 1, 0);
SET @iMixId = LAST_INSERT_ID();

INSERT INTO `sys_options_mixes2options` (`option`, `mix_id`, `value`) VALUES
('bx_protean_block_bg_color', @iMixId, 'rgba(252, 253, 254, 1)'),
('bx_protean_block_bg_image', @iMixId, '0'),
('bx_protean_block_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_block_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_block_bg_image_size', @iMixId, 'cover'),
('bx_protean_block_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_block_border_radius', @iMixId, '5px'),
('bx_protean_block_border_size', @iMixId, '1px'),
('bx_protean_block_content_padding', @iMixId, '1rem'),
('bx_protean_block_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_block_title_bg_color', @iMixId, 'rgba(252, 253, 254, 0)'),
('bx_protean_block_title_border_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_block_title_border_radius', @iMixId, '4px 4px 0px 0px'),
('bx_protean_block_title_border_size', @iMixId, '0px'),
('bx_protean_block_title_div_bg_color', @iMixId, 'rgba(255, 255, 255, 0)'),
('bx_protean_block_title_div_height', @iMixId, '0px'),
('bx_protean_block_title_font_color', @iMixId, 'rgba(40, 60, 80, 0.9)'),
('bx_protean_block_title_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_block_title_font_size', @iMixId, '1.25rem'),
('bx_protean_block_title_font_weight', @iMixId, '500'),
('bx_protean_block_title_padding', @iMixId, '0.2rem 1rem 0.2rem 1rem'),
('bx_protean_body_bg_color', @iMixId, 'rgb(229, 229, 229)'),
('bx_protean_body_bg_image', @iMixId, '0'),
('bx_protean_body_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_body_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_body_bg_image_size', @iMixId, 'cover'),
('bx_protean_body_icon_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_body_icon_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_body_link_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_body_link_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_button_lg_bg_color_hover', @iMixId, 'rgba(243, 244, 245, 0.8)'),
('bx_protean_button_lg_border_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_lg_border_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_border_radius', @iMixId, '5px'),
('bx_protean_button_lg_border_size', @iMixId, '1px'),
('bx_protean_button_lg_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_lg_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_button_lg_font_shadow', @iMixId, 'none'),
('bx_protean_button_lg_font_size', @iMixId, '1rem'),
('bx_protean_button_lg_font_weight', @iMixId, '400'),
('bx_protean_button_lg_height', @iMixId, '2rem'),
('bx_protean_button_lg_shadow', @iMixId, 'none'),
('bx_protean_button_sm_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_button_sm_bg_color_hover', @iMixId, 'rgba(243, 244, 245, 0.8)'),
('bx_protean_button_sm_border_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_sm_border_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_sm_border_radius', @iMixId, '3px'),
('bx_protean_button_sm_border_size', @iMixId, '1px'),
('bx_protean_button_sm_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_sm_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_sm_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_button_sm_font_shadow', @iMixId, 'none'),
('bx_protean_button_sm_font_size', @iMixId, '0.75rem'),
('bx_protean_button_sm_font_weight', @iMixId, '400'),
('bx_protean_button_sm_height', @iMixId, '1.5rem'),
('bx_protean_button_sm_shadow', @iMixId, 'none'),
('bx_protean_card_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_card_bg_color_hover', @iMixId, 'rgba(255, 255, 255, 0.8)'),
('bx_protean_card_bg_image', @iMixId, '0'),
('bx_protean_card_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_card_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_card_bg_image_size', @iMixId, 'cover'),
('bx_protean_card_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_card_border_radius', @iMixId, '5px'),
('bx_protean_card_border_size', @iMixId, '1px'),
('bx_protean_card_content_padding', @iMixId, '1rem'),
('bx_protean_card_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_cover_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_cover_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_cover_border_radius', @iMixId, '0px'),
('bx_protean_cover_border_size', @iMixId, '0px 1px 0px 1px'),
('bx_protean_cover_content_padding', @iMixId, '2rem 3rem 2rem 3rem'),
('bx_protean_cover_font_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_cover_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_cover_font_size', @iMixId, '2.0rem'),
('bx_protean_cover_font_weight', @iMixId, '700'),
('bx_protean_cover_height', @iMixId, '30vh'),
('bx_protean_cover_icon_border_color', @iMixId, 'rgba(208, 208, 208, 1)'),
('bx_protean_cover_icon_border_radius', @iMixId, '3px'),
('bx_protean_cover_icon_border_size', @iMixId, '1px'),
('bx_protean_cover_icon_shadow', @iMixId, 'none'),
('bx_protean_cover_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_cover_text_align', @iMixId, 'center'),
('bx_protean_cover_text_shadow', @iMixId, '0px 1px 3px rgba(0, 0, 0, .3)'),
('bx_protean_font_color_contrasted', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_contrasted_h1', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_contrasted_h2', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_contrasted_h3', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_default', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_font_color_default_h1', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_font_color_default_h2', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_font_color_default_h3', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_font_color_grayed', @iMixId, 'rgba(51, 68, 85, 0.5)'),
('bx_protean_font_color_grayed_h1', @iMixId, 'rgba(17, 34, 51, 0.5)'),
('bx_protean_font_color_grayed_h2', @iMixId, 'rgba(17, 34, 51, 0.5)'),
('bx_protean_font_color_grayed_h3', @iMixId, 'rgba(17, 34, 51, 0.5)'),
('bx_protean_font_color_large', @iMixId, 'rgba(40, 60, 80, 0.9)'),
('bx_protean_font_color_link_h1', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h1_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_font_color_link_h2', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h2_hover', @iMixId, 'rgba(68, 136, 255, 0.5)'),
('bx_protean_font_color_link_h3', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h3_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_font_color_middle', @iMixId, 'rgba(40, 60, 80, 0.9)'),
('bx_protean_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_font_size_default', @iMixId, '15px'),
('bx_protean_font_size_h1', @iMixId, '30px'),
('bx_protean_font_size_h2', @iMixId, '24px'),
('bx_protean_font_size_h3', @iMixId, '18px'),
('bx_protean_font_size_large', @iMixId, '16px'),
('bx_protean_font_size_middle', @iMixId, '14px'),
('bx_protean_font_size_small', @iMixId, '12px'),
('bx_protean_font_weight_h1', @iMixId, '700'),
('bx_protean_font_weight_h2', @iMixId, '700'),
('bx_protean_font_weight_h3', @iMixId, '700'),
('bx_protean_footer_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_footer_bg_image', @iMixId, '0'),
('bx_protean_footer_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_footer_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_footer_bg_image_size', @iMixId, 'cover'),
('bx_protean_footer_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_footer_border_size', @iMixId, '1px'),
('bx_protean_footer_content_padding', @iMixId, '1rem'),
('bx_protean_footer_font_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_footer_icon_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_footer_icon_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_footer_link_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_footer_link_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_footer_shadow', @iMixId, 'none'),
('bx_protean_form_input_bg_color', @iMixId, 'rgba(245, 250, 255, 0.5)'),
('bx_protean_form_input_bg_color_active', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_form_input_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_form_input_border_color_active', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_form_input_border_size', @iMixId, '1px'),
('bx_protean_form_input_font_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_form_input_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_form_input_font_size', @iMixId, '1rem'),
('bx_protean_form_input_height', @iMixId, '2.5rem'),
('bx_protean_form_input_shadow', @iMixId, 'inset 0px 0px 2px 1px rgba(0, 0, 0, 0.01)'),
('bx_protean_form_input_editor_skin', @iMixId, 'gray'),
('bx_protean_general_item_bg_color_active', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_general_item_bg_color_disabled', @iMixId, 'rgba(233, 234, 235, 1)'),
('bx_protean_general_item_bg_color_hover', @iMixId, 'rgba(243, 244, 245, 0.8)'),
('bx_protean_header_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_header_bg_image', @iMixId, '0'),
('bx_protean_header_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_header_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_header_bg_image_size', @iMixId, 'cover'),
('bx_protean_header_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_header_border_size', @iMixId, '1px'),
('bx_protean_header_content_padding', @iMixId, '0.5rem 0px 0.5rem 0px'),
('bx_protean_header_height', @iMixId, '4rem'),
('bx_protean_header_icon_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_header_icon_color_hover', @iMixId, 'rgba(51, 68, 85, 0.8)'),
('bx_protean_header_link_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_header_link_color_hover', @iMixId, 'rgba(51, 68, 85, 0.8)'),
('bx_protean_header_shadow', @iMixId, 'none'),
('bx_protean_menu_account_bg_color', @iMixId, 'rgba(255, 255, 255, 0.95)'),
('bx_protean_menu_account_bg_image', @iMixId, '0'),
('bx_protean_menu_account_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_account_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_account_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_account_border_color', @iMixId, 'rgba(208, 208, 208, 1)'),
('bx_protean_menu_account_border_size', @iMixId, '0px'),
('bx_protean_menu_account_content_padding', @iMixId, '0px'),
('bx_protean_menu_account_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_account_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_account_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_account_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_account_font_shadow', @iMixId, 'none'),
('bx_protean_menu_account_font_size', @iMixId, '1.0rem'),
('bx_protean_menu_account_font_weight', @iMixId, '400'),
('bx_protean_menu_account_shadow', @iMixId, 'none'),
('bx_protean_menu_main_bg_color', @iMixId, 'rgba(255, 255, 255, 0.9)'),
('bx_protean_menu_main_bg_image', @iMixId, '0'),
('bx_protean_menu_main_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_main_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_main_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_main_border_color', @iMixId, 'rgba(208, 208, 208, 1)'),
('bx_protean_menu_main_border_size', @iMixId, '0px'),
('bx_protean_menu_main_content_padding', @iMixId, '0px'),
('bx_protean_menu_main_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_main_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_main_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_main_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_main_font_shadow', @iMixId, 'none'),
('bx_protean_menu_main_font_size', @iMixId, '1.125rem'),
('bx_protean_menu_main_font_weight', @iMixId, '400'),
('bx_protean_menu_main_shadow', @iMixId, 'none'),
('bx_protean_menu_page_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_menu_page_bg_image', @iMixId, '0'),
('bx_protean_menu_page_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_page_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_page_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_page_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_page_border_size', @iMixId, '1px'),
('bx_protean_menu_page_content_padding', @iMixId, '0px'),
('bx_protean_menu_page_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_page_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_page_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_page_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_page_font_shadow', @iMixId, 'none'),
('bx_protean_menu_page_font_size', @iMixId, '1.2rem'),
('bx_protean_menu_page_font_weight', @iMixId, '400'),
('bx_protean_menu_page_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_menu_slide_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_menu_slide_bg_image', @iMixId, '0'),
('bx_protean_menu_slide_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_slide_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_slide_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_slide_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_slide_border_size', @iMixId, '1px 0px 1px 0px'),
('bx_protean_menu_slide_content_padding', @iMixId, '1.25rem'),
('bx_protean_menu_slide_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_slide_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_slide_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_slide_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_slide_font_shadow', @iMixId, 'none'),
('bx_protean_menu_slide_font_size', @iMixId, '1.0rem'),
('bx_protean_menu_slide_font_weight', @iMixId, '400'),
('bx_protean_menu_slide_shadow', @iMixId, 'none'),
('bx_protean_page_width', @iMixId, '1024'),
('bx_protean_popup_bg_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_popup_bg_image', @iMixId, '0'),
('bx_protean_popup_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_popup_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_popup_bg_image_size', @iMixId, 'cover'),
('bx_protean_popup_border_color', @iMixId, 'rgba(119, 136, 153, 0.3)'),
('bx_protean_popup_border_radius', @iMixId, '5px'),
('bx_protean_popup_border_size', @iMixId, '1px'),
('bx_protean_popup_content_padding', @iMixId, '1.25rem'),
('bx_protean_popup_menu_shadow', @iMixId, 'none'),
('bx_protean_popup_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_popup_title_bg_color', @iMixId, 'rgba(40, 60, 80, 0.9)'),
('bx_protean_popup_title_font_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_popup_title_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_popup_title_font_size', @iMixId, '1.5rem'),
('bx_protean_popup_title_padding', @iMixId, '1.25rem'),
('bx_protean_site_logo', @iMixId, '0'),
('bx_protean_site_logo_alt', @iMixId, ''),
('bx_protean_site_logo_height', @iMixId, '48'),
('bx_protean_site_logo_width', @iMixId, '240'),
('bx_protean_styles_custom', @iMixId, 'div.bx-base-pofile-cover {\r\nborder: 1px solid rgba(136, 153, 170, 0.3);\r\nborder-bottom-width: 0;\r\n}\r\n\r\n\r\ndiv.bx-market-unit-cover div.bx-base-text-unit-no-thumb {\r\nborder-width: 0px;\r\n}\r\n\r\n\r\n.bx-def-font {\r\nline-height:18px;\r\nline-height:1.2rem;\r\n}\r\nh1,\r\n.bx-def-font-h1 {\r\nline-height:36px;\r\nline-height:2.4rem;\r\n}\r\nh2,\r\n.bx-def-font-h2 {\r\nline-height:29px;\r\nline-height:1.92rem;\r\n}\r\nh3,\r\n.bx-def-font-h3 {\r\nline-height:22px;\r\nline-height:1.44rem;\r\n}\r\n'),
('bx_protean_vpm_font_size_scale', @iMixId, '85%'),
('bx_protean_vpt_font_size_scale', @iMixId, '93.75%');

DELETE FROM `tm`, `tmo` 
USING `sys_options_mixes` AS `tm`, `sys_options_mixes2options` AS `tmo`
WHERE `tm`.`id` = `tmo`.`mix_id` AND `tm`.`type`=@sName AND `tm`.`name`='Protean-Dark-Mix';

INSERT INTO `sys_options_mixes` (`type`, `category`, `name`, `title`, `active`, `published`, `editable`) VALUES
(@sName, '', 'Protean-Dark-Mix', 'Dark Mix', 0, 1, 0);
SET @iMixId = LAST_INSERT_ID();

INSERT INTO `sys_options_mixes2options` (`option`, `mix_id`, `value`) VALUES
('bx_protean_block_bg_color', @iMixId, 'rgba(34, 51, 68, 1)'),
('bx_protean_block_bg_image', @iMixId, '0'),
('bx_protean_block_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_block_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_block_bg_image_size', @iMixId, 'cover'),
('bx_protean_block_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_block_border_radius', @iMixId, '5px'),
('bx_protean_block_border_size', @iMixId, '1px'),
('bx_protean_block_content_padding', @iMixId, '1rem'),
('bx_protean_block_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_block_title_bg_color', @iMixId, 'rgba(255, 255, 255, 0)'),
('bx_protean_block_title_border_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_block_title_border_radius', @iMixId, '4px 4px 0px 0px'),
('bx_protean_block_title_border_size', @iMixId, '0px'),
('bx_protean_block_title_div_bg_color', @iMixId, 'rgba(255, 255, 255, 0)'),
('bx_protean_block_title_div_height', @iMixId, '0px'),
('bx_protean_block_title_font_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_block_title_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_block_title_font_size', @iMixId, '1.25rem'),
('bx_protean_block_title_font_weight', @iMixId, '500'),
('bx_protean_block_title_padding', @iMixId, '0.2rem 1rem 0.2rem 1rem'),
('bx_protean_body_bg_color', @iMixId, 'rgb(17, 34, 51)'),
('bx_protean_body_bg_image', @iMixId, '0'),
('bx_protean_body_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_body_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_body_bg_image_size', @iMixId, 'cover'),
('bx_protean_body_icon_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_body_icon_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_body_link_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_body_link_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_button_lg_bg_color_hover', @iMixId, 'rgba(51, 68, 85, 0.8)'),
('bx_protean_button_lg_border_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_lg_border_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_border_radius', @iMixId, '5px'),
('bx_protean_button_lg_border_size', @iMixId, '1px'),
('bx_protean_button_lg_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_lg_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_lg_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_button_lg_font_shadow', @iMixId, 'none'),
('bx_protean_button_lg_font_size', @iMixId, '1rem'),
('bx_protean_button_lg_font_weight', @iMixId, '400'),
('bx_protean_button_lg_height', @iMixId, '2rem'),
('bx_protean_button_lg_shadow', @iMixId, 'none'),
('bx_protean_button_sm_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_button_sm_bg_color_hover', @iMixId, 'rgba(51, 68, 85, 0.8)'),
('bx_protean_button_sm_border_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_sm_border_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_sm_border_radius', @iMixId, '2px'),
('bx_protean_button_sm_border_size', @iMixId, '1px'),
('bx_protean_button_sm_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_button_sm_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_button_sm_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_button_sm_font_shadow', @iMixId, 'none'),
('bx_protean_button_sm_font_size', @iMixId, '0.75rem'),
('bx_protean_button_sm_font_weight', @iMixId, '400'),
('bx_protean_button_sm_height', @iMixId, '1.5rem'),
('bx_protean_button_sm_shadow', @iMixId, 'none'),
('bx_protean_card_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_card_bg_color_hover', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_card_bg_image', @iMixId, '0'),
('bx_protean_card_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_card_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_card_bg_image_size', @iMixId, 'cover'),
('bx_protean_card_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_card_border_radius', @iMixId, '5px'),
('bx_protean_card_border_size', @iMixId, '1px'),
('bx_protean_card_content_padding', @iMixId, '1rem'),
('bx_protean_card_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_cover_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_cover_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_cover_border_radius', @iMixId, '0px'),
('bx_protean_cover_border_size', @iMixId, '0px 1px 0px 1px'),
('bx_protean_cover_content_padding', @iMixId, '2rem 3rem 2rem 3rem'),
('bx_protean_cover_font_color', @iMixId, 'rgba(255, 255, 255, 1)'),
('bx_protean_cover_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_cover_font_size', @iMixId, '2.0rem'),
('bx_protean_cover_font_weight', @iMixId, '700'),
('bx_protean_cover_height', @iMixId, '30vh'),
('bx_protean_cover_icon_border_color', @iMixId, 'rgba(208, 208, 208, 1)'),
('bx_protean_cover_icon_border_radius', @iMixId, '3px'),
('bx_protean_cover_icon_border_size', @iMixId, '1px'),
('bx_protean_cover_icon_shadow', @iMixId, 'none'),
('bx_protean_cover_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_cover_text_align', @iMixId, 'center'),
('bx_protean_cover_text_shadow', @iMixId, '0px 1px 3px rgba(0, 0, 0, .3)'),
('bx_protean_font_color_contrasted', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_font_color_contrasted_h1', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_font_color_contrasted_h2', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_font_color_contrasted_h3', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_font_color_default', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_default_h1', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_default_h2', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_default_h3', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_font_color_grayed', @iMixId, 'rgba(243, 244, 245, 0.5)'),
('bx_protean_font_color_grayed_h1', @iMixId, 'rgba(243, 244, 245, 0.5)'),
('bx_protean_font_color_grayed_h2', @iMixId, 'rgba(243, 244, 245, 0.5)'),
('bx_protean_font_color_grayed_h3', @iMixId, 'rgba(243, 244, 245, 0.5)'),
('bx_protean_font_color_link_h1', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h1_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_font_color_link_h2', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h2_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_font_color_link_h3', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_font_color_link_h3_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_font_size_default', @iMixId, '15px'),
('bx_protean_font_size_h1', @iMixId, '30px'),
('bx_protean_font_size_h2', @iMixId, '24px'),
('bx_protean_font_size_h3', @iMixId, '20px'),
('bx_protean_font_size_large', @iMixId, '16px'),
('bx_protean_font_size_middle', @iMixId, '14px'),
('bx_protean_font_size_small', @iMixId, '12px'),
('bx_protean_font_weight_h1', @iMixId, '700'),
('bx_protean_font_weight_h2', @iMixId, '700'),
('bx_protean_font_weight_h3', @iMixId, '500'),
('bx_protean_footer_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_footer_bg_image', @iMixId, '0'),
('bx_protean_footer_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_footer_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_footer_bg_image_size', @iMixId, 'cover'),
('bx_protean_footer_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_footer_border_size', @iMixId, '1px'),
('bx_protean_footer_content_padding', @iMixId, '1rem'),
('bx_protean_footer_font_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_footer_icon_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_footer_icon_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_footer_link_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_footer_link_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_footer_shadow', @iMixId, 'none'),
('bx_protean_form_input_bg_color', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_form_input_bg_color_active', @iMixId, 'rgba(34, 51, 68, 1)'),
('bx_protean_form_input_border_color', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_form_input_border_color_active', @iMixId, 'rgba(17, 34, 51, 1)'),
('bx_protean_form_input_border_size', @iMixId, '2px'),
('bx_protean_form_input_font_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_form_input_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_form_input_font_size', @iMixId, '1rem'),
('bx_protean_form_input_height', @iMixId, '2.5rem'),
('bx_protean_form_input_shadow', @iMixId, 'none'),
('bx_protean_form_input_editor_skin', @iMixId, 'dark'),
('bx_protean_general_item_bg_color_active', @iMixId, 'rgba(34, 51, 68, 1)'),
('bx_protean_general_item_bg_color_disabled', @iMixId, 'rgba(233, 234, 235, 1)'),
('bx_protean_general_item_bg_color_hover', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_header_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_header_bg_image', @iMixId, '0'),
('bx_protean_header_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_header_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_header_bg_image_size', @iMixId, 'cover'),
('bx_protean_header_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_header_border_size', @iMixId, '1px'),
('bx_protean_header_content_padding', @iMixId, '0.5rem 0px 0.5rem 0px'),
('bx_protean_header_height', @iMixId, '4rem'),
('bx_protean_header_icon_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_header_icon_color_hover', @iMixId, 'rgba(243, 244, 245, 0.8)'),
('bx_protean_header_link_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_header_link_color_hover', @iMixId, 'rgba(243, 244, 245, 0.8)'),
('bx_protean_header_shadow', @iMixId, 'none'),
('bx_protean_menu_account_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_account_bg_image', @iMixId, '0'),
('bx_protean_menu_account_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_account_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_account_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_account_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_account_border_size', @iMixId, '0px'),
('bx_protean_menu_account_content_padding', @iMixId, '0px'),
('bx_protean_menu_account_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_account_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_account_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_account_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_account_font_shadow', @iMixId, 'none'),
('bx_protean_menu_account_font_size', @iMixId, '1rem'),
('bx_protean_menu_account_font_weight', @iMixId, '400'),
('bx_protean_menu_account_shadow', @iMixId, 'none'),
('bx_protean_menu_main_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_main_bg_image', @iMixId, '0'),
('bx_protean_menu_main_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_main_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_main_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_main_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_main_border_size', @iMixId, '0px'),
('bx_protean_menu_main_content_padding', @iMixId, '0px'),
('bx_protean_menu_main_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_main_font_color_active', @iMixId, 'rgba(252, 253, 254, 1)'),
('bx_protean_menu_main_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_main_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_main_font_shadow', @iMixId, 'none'),
('bx_protean_menu_main_font_size', @iMixId, '1.125rem'),
('bx_protean_menu_main_font_weight', @iMixId, '400'),
('bx_protean_menu_main_shadow', @iMixId, 'none'),
('bx_protean_menu_page_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_page_bg_image', @iMixId, '0'),
('bx_protean_menu_page_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_page_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_page_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_page_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_page_border_size', @iMixId, '1px'),
('bx_protean_menu_page_content_padding', @iMixId, '0px'),
('bx_protean_menu_page_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_page_font_color_active', @iMixId, 'rgba(252, 253, 254, 1)'),
('bx_protean_menu_page_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_page_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_page_font_shadow', @iMixId, 'none'),
('bx_protean_menu_page_font_size', @iMixId, '1.2rem'),
('bx_protean_menu_page_font_weight', @iMixId, '400'),
('bx_protean_menu_page_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_menu_slide_bg_color', @iMixId, 'rgba(34, 51, 68, 0.9)'),
('bx_protean_menu_slide_bg_image', @iMixId, '0'),
('bx_protean_menu_slide_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_menu_slide_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_menu_slide_bg_image_size', @iMixId, 'cover'),
('bx_protean_menu_slide_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_menu_slide_border_size', @iMixId, '1px 0px 1px 0px'),
('bx_protean_menu_slide_content_padding', @iMixId, '1.25rem'),
('bx_protean_menu_slide_font_color', @iMixId, 'rgba(68, 136, 255, 1)'),
('bx_protean_menu_slide_font_color_active', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_menu_slide_font_color_hover', @iMixId, 'rgba(68, 136, 255, 0.8)'),
('bx_protean_menu_slide_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_menu_slide_font_shadow', @iMixId, 'none'),
('bx_protean_menu_slide_font_size', @iMixId, '1.0rem'),
('bx_protean_menu_slide_font_weight', @iMixId, '400'),
('bx_protean_menu_slide_shadow', @iMixId, 'none'),
('bx_protean_page_width', @iMixId, '1024'),
('bx_protean_popup_bg_color', @iMixId, 'rgba(51, 68, 85, 1)'),
('bx_protean_popup_bg_image', @iMixId, '0'),
('bx_protean_popup_bg_image_attachment', @iMixId, 'scroll'),
('bx_protean_popup_bg_image_repeat', @iMixId, 'no-repeat'),
('bx_protean_popup_bg_image_size', @iMixId, 'cover'),
('bx_protean_popup_border_color', @iMixId, 'rgba(136, 153, 170, 0.3)'),
('bx_protean_popup_border_radius', @iMixId, '5px'),
('bx_protean_popup_border_size', @iMixId, '1px'),
('bx_protean_popup_content_padding', @iMixId, '1.25rem'),
('bx_protean_popup_shadow', @iMixId, '0px 0px 3px 0px rgba(51, 68, 85, 0.1)'),
('bx_protean_popup_title_bg_color', @iMixId, 'rgba(255, 255, 255, 0)'),
('bx_protean_popup_title_font_color', @iMixId, 'rgba(243, 244, 245, 1)'),
('bx_protean_popup_title_font_family', @iMixId, '\"Helvetica Neue\", sans-serif'),
('bx_protean_popup_title_font_size', @iMixId, '1.5rem'),
('bx_protean_popup_title_padding', @iMixId, '1.25rem'),
('bx_protean_site_logo', @iMixId, '0'),
('bx_protean_site_logo_alt', @iMixId, ''),
('bx_protean_site_logo_height', @iMixId, '48'),
('bx_protean_site_logo_width', @iMixId, '240'),
('bx_protean_styles_custom', @iMixId, 'div.bx-base-pofile-cover {\r\nborder: 1px solid rgba(136, 153, 170, 0.3);\r\nborder-bottom-width: 0;\r\n}\r\n\r\n\r\ndiv.bx-market-unit-cover div.bx-base-text-unit-no-thumb {\r\nborder-width: 0px;\r\n}\r\n\r\n.sys-cpf-header,\r\n.sys-cpf-title,\r\n.sys-cpf-submenu-cnt ul li {\r\nborder-bottom-color: rgba(136, 153, 170, 0.3);\r\n}\r\n\r\n.sys-cpf-submenu-cnt ul li.bx-menu-inter-act {\r\nborder-bottom-color: rgb(17, 34, 51);\r\n}\r\n\r\n\r\n.bx-def-font {\r\nline-height:18px;\r\nline-height:1.2rem;\r\n}\r\nh1,\r\n.bx-def-font-h1 {\r\nline-height:36px;\r\nline-height:2.4rem;\r\n}\r\nh2,\r\n.bx-def-font-h2 {\r\nline-height:29px;\r\nline-height:1.92rem;\r\n}\r\nh3,\r\n.bx-def-font-h3 {\r\nline-height:22px;\r\nline-height:1.44rem;\r\n}\r\n\r\n.bx-def-label {\r\nbackground-color: rgba(245, 250, 255, 0.5);\r\n}\r\n.bx-def-label,\r\n.bx-def-label a,\r\n.bx-def-label .sys-icon {\r\ncolor: rgba(51, 68, 85, 1);\r\n}\r\n\r\n/*--- Informers ---*/\r\n.bx-informer-msg-info {\r\nbackground-color: rgba(60, 164, 85, 1.0);\r\n}\r\n.bx-informer-msg-alert {\r\nbackground-color: rgba(230, 115, 55, 1.0);\r\n}\r\n.bx-informer-msg-error {\r\nbackground-color: rgba(200, 64, 64, 1.0);\r\n}\r\n\r\n\r\n/*--- Menus ---*/\r\n.bx-menu-notif li.bx-menu-tab-active a, \r\n.bx-menu-verlit li.bx-menu-tab-active a, \r\n.bx-menu-ver li.bx-menu-tab-active a,\r\n.bx-menu-hor li.bx-menu-tab-active a {\r\ncolor: rgba(252, 253, 254, 1);\r\n}\r\n\r\n/*--- Forms ---*/\r\n.bx-form-value .bx-form-input-autotoken b {\r\ncolor: rgba(243, 244, 245, 1);\r\n}\r\n.bx-popup .dropzone {\r\nbackground-color: rgba(17, 34, 51, 1);\r\n}\r\n\r\n/*--- Timeline ---*/\r\ndiv.bx-tl-view-timeline div.bx-tl-items:before,\r\ndiv.bx-tl-view-timeline div.bx-tl-item-circle {\r\nbackground-color: rgba(51, 68, 85, 1);\r\n}\r\ndiv.bx-tl-il-embed {\r\npadding: 0.5rem;\r\nbackground-color: rgba(255, 255, 255, 0.8);\r\nborder-radius:  5px;\r\n}\r\n'),
('bx_protean_vpm_font_size_scale', @iMixId, '85%'),
('bx_protean_vpt_font_size_scale', @iMixId, '93.75%');
