<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
	'_sys_module_payflow' => 'PayPal PayFlow Pro',
	'_bx_pfw_pcpt_join' => 'Join',
	'_bx_pfw_bcpt_join' => 'Join',
	'_bx_pfw_chart' => 'Transactions',

	//--- Menus
	'_bx_pfw_admin_menu_sitem' => 'PayPal PayFlow Pro',

	//--- Administration
	'_bx_pfw_pcpt_administration' => 'PayPal PayFlow Pro',
	'_bx_pfw_bcpt_settings' => 'Settings',

	//--- Details
	'_bx_pfw_pcpt_details' => 'Payment Details',
	'_bx_pfw_bcpt_details' => 'Details',
	'_bx_pfw_details_submit' => 'Save',
	'_bx_pfw_po_active_cpt' => 'Active',
    '_bx_pfw_po_active_dsc' => 'Activate(Deactivate) provider',
    '_bx_pfw_po_mode_cpt' => 'Mode',
    '_bx_pfw_po_mode_dsc' => 'Mode to process payments',
    '_bx_pfw_po_mode_live' => 'live',
    '_bx_pfw_po_mode_test' => 'test',
	'_bx_pfw_po_partner_cpt' => 'Partner',
	'_bx_pfw_po_partner_dsc' => 'Your partner, usually "PayPal".',
	'_bx_pfw_po_vendor_cpt' => 'Merchant login',
	'_bx_pfw_po_vendor_dsc' => 'You merchant login in PayPal Manager',
	'_bx_pfw_po_user_cpt' => 'User login',
	'_bx_pfw_po_user_dsc' => 'The user should have Full privileges to manage API calls. "Merchant login" can be used but it is not recomended.',
	'_bx_pfw_po_password_cpt' => 'User password',
	'_bx_pfw_po_password_dsc' => 'Password for User account. If "Merchant" is used as "User" then use "Merchant" password here.',

	//--- Orders
	'_bx_pfw_pcpt_view_orders' => 'Order Administration',
	'_bx_pfw_bcpt_pending_orders' => 'Pending Orders',
	'_bx_pfw_bcpt_processed_orders' => 'Processed Orders',
	'_bx_pfw_bcpt_subscription_orders' => 'Subscriptions',
	'_bx_pfw_wcpt_manual_order' => 'Manual Order',
    '_bx_pfw_wcpt_order_info' => 'Order Info',
    '_bx_pfw_btn_settings' => 'Settings',
    '_bx_pfw_btn_orders_processed' => 'Processed',
    '_bx_pfw_btn_orders_pending' => 'Pending',
	'_bx_pfw_btn_process' => 'Process',
	'_bx_pfw_btn_cancel' => 'Cancel',
    '_bx_pfw_btn_report' => 'Report',
	'_bx_pfw_btn_add' => 'Add',
    '_bx_pfw_btn_manual_order' => 'Manual Order',
	'_bx_pfw_btn_unsubscribe' => 'Unsubscribe',
    '_bx_pfw_fcpt_module' => 'Items from',
    '_bx_pfw_fcpt_client' => 'Client',
    '_bx_pfw_fcpt_order' => 'Order',
	'_bx_pfw_ocpt_select' => 'Select one',
	'_bx_pfw_txt_date' => 'Date',
    '_bx_pfw_txt_client' => 'Client',
    '_bx_pfw_txt_seller' => 'Seller',
    '_bx_pfw_txt_order' => 'Order ID',
	'_bx_pfw_txt_order_profile' => 'Subscription ID',
    '_bx_pfw_txt_amount' => 'Amount',
    '_bx_pfw_txt_license' => 'License',
	'_bx_pfw_txt_subscription' => 'Subscription',
    '_bx_pfw_txt_action' => 'More',
	'_bx_pfw_txt_more_products' => 'products',
	'_bx_pfw_txt_more_items' => 'items',
    '_bx_pfw_txt_action_more' => 'More',
	'_bx_pfw_txt_processed_with' => 'Processed with',
    '_bx_pfw_txt_message' => 'Result',
    '_bx_pfw_txt_products' => 'Products',
	'_bx_pfw_txt_yes' => 'Yes',
	'_bx_pfw_txt_no' => 'No',

	//--- Cart
	'_bx_pfw_pcpt_view_cart' => 'Shopping cart',
	'_bx_pfw_pcpt_cart_history' => 'Cart History',
	'_bx_pfw_pcpt_receipt' => 'Receipt',
	'_bx_pfw_pcpt_credit_card' => 'Credit Card Details',
	'_bx_pfw_bcpt_cart_featured' => 'Site Cart',
    '_bx_pfw_bcpt_cart_common' => 'Members\' Carts',
    '_bx_pfw_bcpt_cart_history' => 'Cart History',
	'_bx_pfw_bcpt_receipt' => 'Receipt',
	'_bx_pfw_bcpt_credit_card' => 'Credit Card Details',
	'_bx_pfw_btn_history' => 'History',
	'_bx_pfw_btn_delete' => 'Delete',
    '_bx_pfw_btn_checkout' => 'Checkout',
    '_bx_pfw_btn_cart' => 'Cart',
	'_bx_pfw_btn_pay' => 'Pay',
	'_bx_pfw_btn_subscribe' => 'Subscribe',
	'_bx_pfw_fcpt_details_title' => 'Title',
	'_bx_pfw_fcpt_details_quantity' => 'Quantity',
	'_bx_pfw_fcpt_details_price' => 'Price',
	'_bx_pfw_fcpt_details_total' => 'Total',
	'_bx_pfw_txt_add_to_cart' => 'Add to Cart',
	'_bx_pfw_txt_shopping_cart' => '\'s cart',
	'_bx_pfw_txt_buyer_info' => 'Buyer',
	'_bx_pfw_txt_buyer_name' => 'Name',
	'_bx_pfw_txt_buyer_name_mask' => '{0} {1}',
	'_bx_pfw_txt_buyer_email' => 'Email',
	'_bx_pfw_txt_buyer_email_mask' => '{0} ({1})',
	'_bx_pfw_txt_products_info' => 'Products',
	'_bx_pfw_txt_subscription_info' => 'Subscription',
	'_bx_pfw_txt_subscription_duration_mask' => '(auto-renew in {0} days)',
	'_bx_pfw_txt_free' => 'free',

	//--- Errors, Warnings and Messages
	'_bx_pfw_pcpt_error' => 'Error occured',
	'_bx_pfw_pcpt_response' => 'Operation result',
	'_bx_pfw_pcpt_payment_result' => 'Payment result',
	'_bx_pfw_bcpt_payment_result' => 'Payment result',
	'_bx_pfw_msg_no_results' => 'Empty',
	'_bx_pfw_msg_accepted' => 'Payment was successfully accepted.',
	'_bx_pfw_msg_accepted_subscribed' => 'Subscription profile was created and the first payment was successfully accepted.',
	'_bx_pfw_msg_subscription_canceled' => 'Subscription profile was canceled.',
	'_bx_pfw_msg_successfully_done' => 'Operation was successfully done.',
	'_bx_pfw_inf_successfully_added' => 'The item was successfully added to your shopping cart',
	'_bx_pfw_inf_successfully_deleted' => 'The item was successfully deleted from your shopping cart',
	'_bx_pfw_inf_successfully_reported' => 'The order was successfully reported',
	'_bx_pfw_inf_successfully_processed_free' => 'Free item was successfully processed',
	'_bx_pfw_err_nothing_selected' => 'You need to select at least one item',
	'_bx_pfw_err_access_db' => 'Database access error.',
	'_bx_pfw_err_wrong_data' => 'Incorrect input data',
	'_bx_pfw_err_wrong_amount' => 'Incorrect payment amount',
	'_bx_pfw_err_required_login' => 'You need to login',
	'_bx_pfw_err_unknown' => 'An error occurred during the operation',
	'_bx_pfw_err_empty_order' => 'The order is empty',
	'_bx_pfw_err_empty_orders' => 'Fill in order numbers', 
	'_bx_pfw_err_unknown_vendor' => 'Unknown vendor',
	'_bx_pfw_err_incorrect_provider' => 'Incorrect or unavailable payment provider',
	'_bx_pfw_err_wrong_client' => 'Incorrect client\'s name',
	'_bx_pfw_err_purchase_from_yourself' => 'You cannot purchase your own item. It\'s just a bad luck thing, you know.',
	'_bx_pfw_err_wrong_order' => 'Incorrect order',
	'_bx_pfw_err_wrong_module' => 'Select where item is located',
	'_bx_pfw_err_empty_items' => 'There are no items selected',
	'_bx_pfw_err_wrong_quantity' => 'Incorrect quantity specified',
	'_bx_pfw_err_inactive_vendor' => 'The vendor status is not active',
	'_bx_pfw_err_not_accept_payments' => 'The vendor does not accept payments',
	'_bx_pfw_err_not_allowed' => 'Action is not allowed',
	'_bx_pfw_err_not_available' => 'Action is not available',
	'_bx_pfw_err_already_processed' => 'This payment has been already processed.',
	'_bx_pfw_err_not_processed' => 'This payment was not processed.',

	//--- Hosted Checkout Pages
	'_bx_pfw_cpt_hosted_checkout' => 'PayPal Hosted Checkout',
	'_bx_pfw_dsc_hosted_checkout' => 'Hosted Checkout with PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_hosted_checkout' => 'PayPal (credit card)',

	//--- Express Checkout
	'_bx_pfw_cpt_express_checkout' => 'PayPal Express Checkout',
	'_bx_pfw_dsc_express_checkout' => 'Express Checkout with PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_express_checkout' => 'PayPal',

	//--- Recurring Billing
	'_bx_pfw_cpt_recurring_billing' => 'PayPal Recurring Billing',
	'_bx_pfw_dsc_recurring_billing' => 'Recurring Billing with PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_recurring_billing' => 'PayPal (subscription)',
	'_bx_pfw_txt_subscription_for' => 'Subscription for "{0}"',
	'_bx_pfw_msg_one_item_only' => 'You may subscribe to only one item at a time. Please, select a single item in your shopping cart which you want to subscribe to.',
	'_bx_pfw_err_subscription_not_found' => 'Subscription profile was not found.',
	'_bx_pfw_err_subscription_not_prolonged' => 'Subscription profile was not prolonged.',
);
