<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
	'_sys_module_payflow' => 'PayPal PayFlow Pro',
	'_bx_pfw_pcpt_join' => 'Регистрация',
	'_bx_pfw_bcpt_join' => 'Регистрация',
	'_bx_pfw_chart' => 'Транзакции',

	//--- Menus
	'_bx_pfw_admin_menu_sitem' => 'PayPal PayFlow Pro',

	//--- Administration
	'_bx_pfw_pcpt_administration' => 'PayPal PayFlow Pro',
	'_bx_pfw_bcpt_settings' => 'Настройки',

	//--- Details
	'_bx_pfw_pcpt_details' => 'Детали платежей',
	'_bx_pfw_bcpt_details' => 'Детали',
	'_bx_pfw_details_submit' => 'Сохранить',
	'_bx_pfw_po_active_cpt' => 'Активировать',
    '_bx_pfw_po_active_dsc' => 'Активировать провайдера',
    '_bx_pfw_po_mode_cpt' => 'Режим',
    '_bx_pfw_po_mode_dsc' => 'Режим обработки платежей',
    '_bx_pfw_po_mode_live' => 'рабочий',
    '_bx_pfw_po_mode_test' => 'тестовый',
	'_bx_pfw_po_partner_cpt' => 'Партнер',
	'_bx_pfw_po_partner_dsc' => 'Ваш партнер, обычно "PayPal".',
	'_bx_pfw_po_vendor_cpt' => 'Торговый логин',
	'_bx_pfw_po_vendor_dsc' => 'Ваш торговый логин в PayPal Manager',
	'_bx_pfw_po_user_cpt' => 'Логин пользователя',
	'_bx_pfw_po_user_dsc' => 'Пользователь должен иметь все права на работу с API запросами. Можут быть использован "Торговый логин" (не рекомендуется).',
	'_bx_pfw_po_password_cpt' => 'Пароль пользователя',
	'_bx_pfw_po_password_dsc' => 'Пароль от аккаунта пользователя. Используйте пароль от торгового аккаунта, если торговый логин используется как логин пользователя.',

	//--- Orders
	'_bx_pfw_pcpt_view_orders' => 'Администрация заказов',
	'_bx_pfw_bcpt_pending_orders' => 'Обрабатываемые заказы',
	'_bx_pfw_bcpt_processed_orders' => 'Обработанные заказы',
	'_bx_pfw_bcpt_subscription_orders' => 'Подписки',
	'_bx_pfw_wcpt_manual_order' => 'Добавить вручную',
    '_bx_pfw_wcpt_order_info' => 'Информация о заказе',
    '_bx_pfw_btn_settings' => 'Настройки',
    '_bx_pfw_btn_orders_processed' => 'Обработано',
    '_bx_pfw_btn_orders_pending' => 'Ожидающие',
	'_bx_pfw_btn_process' => 'Обработать',
	'_bx_pfw_btn_cancel' => 'Отменить',
    '_bx_pfw_btn_report' => 'Пожаловаться',
	'_bx_pfw_btn_add' => 'Добавить',
    '_bx_pfw_btn_manual_order' => 'Добавить вручную',
	'_bx_pfw_btn_unsubscribe' => 'Отписаться',
    '_bx_pfw_fcpt_module' => 'Товары из',
    '_bx_pfw_fcpt_client' => 'Клиент',
    '_bx_pfw_fcpt_order' => 'Заказ',
	'_bx_pfw_ocpt_select' => 'Выберите',
	'_bx_pfw_txt_date' => 'Дата',
    '_bx_pfw_txt_client' => 'Клиент',
    '_bx_pfw_txt_seller' => 'Продавец',
    '_bx_pfw_txt_order' => 'Номер заказа',
	'_bx_pfw_txt_order_profile' => 'Номер подписки',
    '_bx_pfw_txt_amount' => 'Цена',
    '_bx_pfw_txt_license' => 'Лицензия',
	'_bx_pfw_txt_subscription' => 'Подписка',
    '_bx_pfw_txt_action' => 'Детали',
	'_bx_pfw_txt_more_products' => 'товар(а)',
	'_bx_pfw_txt_more_items' => 'шт',
    '_bx_pfw_txt_action_more' => 'Еще',
	'_bx_pfw_txt_processed_with' => 'Обработан',
    '_bx_pfw_txt_message' => 'Результат',
    '_bx_pfw_txt_products' => 'Товары',
	'_bx_pfw_txt_yes' => 'Да',
	'_bx_pfw_txt_no' => 'Нет',

	//--- Cart
	'_bx_pfw_pcpt_view_cart' => 'Корзина',
	'_bx_pfw_pcpt_cart_history' => 'История корзины',
	'_bx_pfw_pcpt_receipt' => 'Квитанция',
	'_bx_pfw_pcpt_credit_card' => 'Детали кредитной карты',
	'_bx_pfw_bcpt_cart_featured' => 'Корзина сайта',
    '_bx_pfw_bcpt_cart_common' => 'Корзины пользователей',
    '_bx_pfw_bcpt_cart_history' => 'История корзины',
	'_bx_pfw_bcpt_receipt' => 'Квитанция',
	'_bx_pfw_bcpt_credit_card' => 'Детали кредитной карты',
	'_bx_pfw_btn_history' => 'История',
	'_bx_pfw_btn_delete' => 'Удалить',
    '_bx_pfw_btn_checkout' => 'Оплатить',
    '_bx_pfw_btn_cart' => 'Корзина',
	'_bx_pfw_btn_pay' => 'Оплатить',
	'_bx_pfw_btn_subscribe' => 'Подписаться',
	'_bx_pfw_fcpt_details_title' => 'Наименование',
	'_bx_pfw_fcpt_details_quantity' => 'Количество',
	'_bx_pfw_fcpt_details_price' => 'Цена',
	'_bx_pfw_fcpt_details_total' => 'Итого',
	'_bx_pfw_txt_add_to_cart' => 'В корзину',
	'_bx_pfw_txt_shopping_cart' => ' корзина',
	'_bx_pfw_txt_buyer_info' => 'Покупатель',
	'_bx_pfw_txt_buyer_name' => 'Имя',
	'_bx_pfw_txt_buyer_name_mask' => '{0} {1}',
	'_bx_pfw_txt_buyer_email' => 'E-mail',
	'_bx_pfw_txt_buyer_email_mask' => '{0} ({1})',
	'_bx_pfw_txt_products_info' => 'Товары',
	'_bx_pfw_txt_subscription_info' => 'Подписка',
	'_bx_pfw_txt_subscription_duration_mask' => '(автообновление через {0} дней)',
	'_bx_pfw_txt_free' => 'бесплатно',

	//--- Errors, Warnings and Messages
	'_bx_pfw_pcpt_error' => 'Ошибка',
	'_bx_pfw_pcpt_response' => 'Результаты',
	'_bx_pfw_pcpt_payment_result' => 'Результаты',
	'_bx_pfw_bcpt_payment_result' => 'Результаты',
	'_bx_pfw_msg_no_results' => 'Пусто',
	'_bx_pfw_msg_accepted' => 'Платеж был успешно принят.',
	'_bx_pfw_msg_accepted_subscribed' => 'Профайл подписки был создан. Первый платеж был успешно принят.',
	'_bx_pfw_msg_subscription_canceled' => 'Профайл подписки был аннулирован.',
	'_bx_pfw_msg_successfully_done' => 'Операция была успешно выполнена.',
	'_bx_pfw_inf_successfully_added' => 'Товар был успешно добавлен в Вашу корзину.',
	'_bx_pfw_inf_successfully_deleted' => 'Товар был успешно удален из Вашей корзины.',
	'_bx_pfw_inf_successfully_reported' => 'Жалоба была принята.',
	'_bx_pfw_inf_successfully_processed_free' => 'Бесплатный товар был обработан.',
	'_bx_pfw_err_nothing_selected' => 'Вы должны выбрать как минимум один товар.',
	'_bx_pfw_err_access_db' => 'Ошибка доступа к базе даных.',
	'_bx_pfw_err_wrong_data' => 'Неверные входные данные.',
	'_bx_pfw_err_wrong_amount' => 'Неверная сумма платежа.',
	'_bx_pfw_err_required_login' => 'Вам нужно войти.',
	'_bx_pfw_err_unknown' => 'Произошла ошибка во время операции.',
	'_bx_pfw_err_empty_order' => 'Заказ пустой.',
	'_bx_pfw_err_empty_orders' => 'Заполните номера заказов.', 
	'_bx_pfw_err_unknown_vendor' => 'Неизвестный продавец.',
	'_bx_pfw_err_incorrect_provider' => 'Неправильная или недоступная платежная система.',
	'_bx_pfw_err_wrong_client' => 'Неправильное имя клиента.',
	'_bx_pfw_err_purchase_from_yourself' => 'Вы не можете купить свой собственный товар. Вам просто не повезло, знаете ли.',
	'_bx_pfw_err_wrong_order' => 'Неправильный номер заказа.',
	'_bx_pfw_err_wrong_module' => 'Выберите, где расположен товар.',
	'_bx_pfw_err_empty_items' => 'Нет выбранных товаров.',
	'_bx_pfw_err_wrong_quantity' => 'Указано неправильное количество.',
	'_bx_pfw_err_inactive_vendor' => 'У продавца неактивный статус.',
	'_bx_pfw_err_not_accept_payments' => 'Продавец не принимает платежи.',
	'_bx_pfw_err_not_allowed' => 'Выполнение действия не разрешено.',
	'_bx_pfw_err_not_available' => 'Действие не доступно.',
	'_bx_pfw_err_already_processed' => 'Платеж был уже обработан.',
	'_bx_pfw_err_not_processed' => 'Платеж не был обработан.',

	//--- Hosted Checkout Pages
	'_bx_pfw_cpt_hosted_checkout' => 'PayPal Hosted Checkout',
	'_bx_pfw_dsc_hosted_checkout' => 'Hosted Checkout в PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_hosted_checkout' => 'PayPal (Кредитная карта)',

	//--- Express Checkout
	'_bx_pfw_cpt_express_checkout' => 'PayPal Express Checkout',
	'_bx_pfw_dsc_express_checkout' => 'Express Checkout в PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_express_checkout' => 'PayPal',

	//--- Recurring Billing
	'_bx_pfw_cpt_recurring_billing' => 'PayPal Recurring Billing',
	'_bx_pfw_dsc_recurring_billing' => 'Recurring Billing в PayPal PayFlow Pro',
	'_bx_pfw_txt_cart_recurring_billing' => 'PayPal (Подписка)',
	'_bx_pfw_txt_subscription_for' => 'Подписка на "{0}"',
	'_bx_pfw_msg_one_item_only' => 'Единовременно можно оформить только одну подписку. Пожалуйста, выберите продукт, на который Вы хотели бы подписаться.',
	'_bx_pfw_err_subscription_not_found' => 'Профайл подписки не найден.',
	'_bx_pfw_err_subscription_not_prolonged' => 'Профайл подписки не был продлён.',
);
