<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_wall' => 'Timeline',
    '_wall_pc_view' => 'Timeline',
    '_wall_pc_view_account' => 'Friends Timeline',
    '_wall_pc_view_index' => 'Outline',
    '_wall_pc_post' => 'Post to Timeline',
    '_wall_pc_admin' => 'Timeline',
    '_wall_bc_settings' => 'Settings',
    '_wall_added_new' => 'added new',
    '_wall_edited_his_profile' => 'edited his profile',
    '_wall_edited_her_profile' => 'edited her profile',
    '_wall_edited_their_profile' => 'edited their profile',
    '_wall_edited_his_profile_status_message' => 'changed his profile status message',
    '_wall_edited_her_profile_status_message' => 'changed her profile status message',
    '_wall_edited_their_profile_status_message' => 'changed their profile status message',
    '_wall_added_new_comment_profile' => 'commented on a',
    '_wall_object_profile' => 'profile',
    '_wall_info' => 'info',
    '_wall_friends_with' => 'is now friends with',
    '_wall_today' => 'Today',
    '_wall_1_days_ago' => 'Yesterday',
    '_wall_n_days_ago' => '{0} days ago',
    '_wall_n_comments' => '{0} comments',
    '_wall_no_comments' => 'no comments',
    '_wall_write' => 'Write',
    '_wall_share_link' => 'Share a link',
    '_wall_add_photo' => 'Add a photo',
    '_wall_add_video' => 'Add a video',
    '_wall_add_music' => 'Add a sound',
    '_wall_post' => 'Submit',
    '_wall_wrote' => 'wrote',
    '_wall_link_url' => 'URL',
    '_Show N comments' => '<span>{0}</span> comments',
    '_Hide N comments' => '<span>{0}</span> comments',
    '_Comment to this comment' => 'Comment',
    '_wall_shared_link' => 'shared a link',
    '_wall_added_photo' => 'added a photo',
    '_wall_added_video' => 'added a video',
    '_wall_added_music' => 'added a sound',
    '_wall_photo_album' => '{0}\'s timeline photos',
    '_wall_sound_album' => '{0}\'s timeline sounds',
    '_wall_video_album' => '{0}\'s timeline videos',
    '_wall_top_smenu_item_wall' => 'Timeline',
    '_wall_top_smenu_item_my_wall' => 'Timeline',
    '_wall_page_caption' => '{0}\'s Timeline',
    '_wall_page_caption_my' => 'My Timeline',
    '_wall_anonymous' => 'Guest',
    '_wall_post_delete' => 'delete',
    '_wall_msg_no_results' => 'Empty',
    '_wall_msg_page_not_found' => 'Page not found',
    '_wall_rss_caption' => 'timeline',
    '_wall_msg_failed_post' => 'Wrong input data',
    '_wall_msg_not_allowed_post' => 'Your membership level does not allow you to post here',
    '_wall_msg_text_empty_message' => 'The message to be posted is empty',
    '_wall_msg_link_empty_link' => 'The link to be posted is empty',
    '_wall_admin_menu_sitem' => 'Timeline',
    '_mma_timeline_post_comment' => 'timeline post comment',
    '_mma_timeline_delete_comment' => 'timeline delete comment',
    '_sbs_txt_title_bx_wall' => 'Timeline',
    '_wall_sbs_main' => '{0}\'s timeline',
    '_wall_sbs_update' => '{0}\'s Timeline (new events)',
    '_wall_time_range' => 'Time range (days ago):',
    '_wall_load_more' => 'Load More',
    '_wall_spy_post' => '<a href="{profile_link}">{profile_nick}</a> posted on <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline',
    '_wall_spy_post_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline',
    '_bx_wall_chart' => 'Wall Events',
    '_wall_alert_module_profile' => 'Profile',
    '_wall_alert_module_friend' => 'Friend',
    '_wall_alert_action_add' => 'add item',
    '_wall_alert_action_create' => 'add item',
    '_wall_alert_action_change' => 'change item',
    '_wall_alert_action_edit' => 'change item',
    '_wall_alert_action_delete' => 'delete item',
    '_wall_alert_action_commentPost' => 'add comment',
    '_wall_alert_action_edit_status_message' => 'change status message',
    '_wall_alert_action_accept' => 'accept',
);
