<?php

$aFilesDelete = array(
    'template/menu_profile_stats.html',
    'template/css/timepicker-addon/jquery-ui-timepicker-addon.css',

    'template/css/jquery-ui/jquery-ui.css',
    'template/css/jquery-ui/images/animated-overlay.gif',
    'template/css/jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png',
    'template/css/jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png',

    'plugins/phpmailer/phpmailer/language/phpmailer.lang-ch.php',
    'plugins/recurly',
    'plugins_public/URI.js',

    'plugins_public/jquery-ui/i18n',
    'plugins_public/jquery-ui/jquery-ui.custom.min.js',
    'plugins_public/jquery-ui/jquery.ui.accordion.min.js',
    'plugins_public/jquery-ui/jquery.ui.autocomplete.min.js',
    'plugins_public/jquery-ui/jquery.ui.button.min.js',
    'plugins_public/jquery-ui/jquery.ui.core.min.js',
    'plugins_public/jquery-ui/jquery.ui.datepicker.min.js',
    'plugins_public/jquery-ui/jquery.ui.dialog.min.js',
    'plugins_public/jquery-ui/jquery.ui.draggable.min.js',
    'plugins_public/jquery-ui/jquery.ui.droppable.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-blind.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-bounce.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-clip.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-drop.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-explode.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-fade.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-fold.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-highlight.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-pulsate.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-scale.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-shake.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-slide.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect-transfer.min.js',
    'plugins_public/jquery-ui/jquery.ui.effect.min.js',
    'plugins_public/jquery-ui/jquery.ui.menu.min.js',
    'plugins_public/jquery-ui/jquery.ui.mouse.min.js',
    'plugins_public/jquery-ui/jquery.ui.position.min.js',
    'plugins_public/jquery-ui/jquery.ui.progressbar.min.js',
    'plugins_public/jquery-ui/jquery.ui.resizable.min.js',
    'plugins_public/jquery-ui/jquery.ui.selectable.min.js',
    'plugins_public/jquery-ui/jquery.ui.slider.min.js',
    'plugins_public/jquery-ui/jquery.ui.sortable.min.js',
    'plugins_public/jquery-ui/jquery.ui.spinner.min.js',
    'plugins_public/jquery-ui/jquery.ui.tabs.min.js',
    'plugins_public/jquery-ui/jquery.ui.tooltip.min.js',
    'plugins_public/jquery-ui/jquery.ui.widget.min.js',

//	'plugins/phpmailer/Exception.php',
//	'plugins/phpmailer/LICENSE',
//	'plugins/phpmailer/PHPMailer.php',
//	'plugins/phpmailer/README.md',
//	'plugins/phpmailer/SMTP.php',
//	'plugins/phpmailer/VERSION',
);

