<?php
/**
 * ItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SidneyAllen\XeroPHP;

/**
 * ItemTest Class Doc Comment
 *
 * @category    Class
 * @description Item
 * @package     SidneyAllen\XeroPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Item"
     */
    public function testItem()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "inventory_asset_account_code"
     */
    public function testPropertyInventoryAssetAccountCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_sold"
     */
    public function testPropertyIsSold()
    {
    }

    /**
     * Test attribute "is_purchased"
     */
    public function testPropertyIsPurchased()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "purchase_description"
     */
    public function testPropertyPurchaseDescription()
    {
    }

    /**
     * Test attribute "purchase_details"
     */
    public function testPropertyPurchaseDetails()
    {
    }

    /**
     * Test attribute "sales_details"
     */
    public function testPropertySalesDetails()
    {
    }

    /**
     * Test attribute "is_tracked_as_inventory"
     */
    public function testPropertyIsTrackedAsInventory()
    {
    }

    /**
     * Test attribute "total_cost_pool"
     */
    public function testPropertyTotalCostPool()
    {
    }

    /**
     * Test attribute "quantity_on_hand"
     */
    public function testPropertyQuantityOnHand()
    {
    }

    /**
     * Test attribute "updated_date_utc"
     */
    public function testPropertyUpdatedDateUtc()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "validation_errors"
     */
    public function testPropertyValidationErrors()
    {
    }
}
