<?php
/**
 * JournalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SidneyAllen\XeroPHP;

/**
 * JournalTest Class Doc Comment
 *
 * @category    Class
 * @description Journal
 * @package     SidneyAllen\XeroPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class JournalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Journal"
     */
    public function testJournal()
    {
    }

    /**
     * Test attribute "journal_id"
     */
    public function testPropertyJournalId()
    {
    }

    /**
     * Test attribute "journal_date"
     */
    public function testPropertyJournalDate()
    {
    }

    /**
     * Test attribute "journal_number"
     */
    public function testPropertyJournalNumber()
    {
    }

    /**
     * Test attribute "created_date_utc"
     */
    public function testPropertyCreatedDateUtc()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "source_type"
     */
    public function testPropertySourceType()
    {
    }

    /**
     * Test attribute "journal_lines"
     */
    public function testPropertyJournalLines()
    {
    }
}
