<?php
/**
 * PaymentServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SidneyAllen\XeroPHP;

/**
 * PaymentServiceTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentService
 * @package     SidneyAllen\XeroPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentService"
     */
    public function testPaymentService()
    {
    }

    /**
     * Test attribute "payment_service_id"
     */
    public function testPropertyPaymentServiceId()
    {
    }

    /**
     * Test attribute "payment_service_name"
     */
    public function testPropertyPaymentServiceName()
    {
    }

    /**
     * Test attribute "payment_service_url"
     */
    public function testPropertyPaymentServiceUrl()
    {
    }

    /**
     * Test attribute "pay_now_text"
     */
    public function testPropertyPayNowText()
    {
    }

    /**
     * Test attribute "payment_service_type"
     */
    public function testPropertyPaymentServiceType()
    {
    }

    /**
     * Test attribute "validation_errors"
     */
    public function testPropertyValidationErrors()
    {
    }
}
