<?php
/**
 * TenNinteyNineContactTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SidneyAllen\XeroPHP;

/**
 * TenNinteyNineContactTest Class Doc Comment
 *
 * @category    Class
 * @description TenNinteyNineContact
 * @package     SidneyAllen\XeroPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TenNinteyNineContactTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TenNinteyNineContact"
     */
    public function testTenNinteyNineContact()
    {
    }

    /**
     * Test attribute "box1"
     */
    public function testPropertyBox1()
    {
    }

    /**
     * Test attribute "box2"
     */
    public function testPropertyBox2()
    {
    }

    /**
     * Test attribute "box3"
     */
    public function testPropertyBox3()
    {
    }

    /**
     * Test attribute "box4"
     */
    public function testPropertyBox4()
    {
    }

    /**
     * Test attribute "box5"
     */
    public function testPropertyBox5()
    {
    }

    /**
     * Test attribute "box6"
     */
    public function testPropertyBox6()
    {
    }

    /**
     * Test attribute "box7"
     */
    public function testPropertyBox7()
    {
    }

    /**
     * Test attribute "box8"
     */
    public function testPropertyBox8()
    {
    }

    /**
     * Test attribute "box9"
     */
    public function testPropertyBox9()
    {
    }

    /**
     * Test attribute "box10"
     */
    public function testPropertyBox10()
    {
    }

    /**
     * Test attribute "box11"
     */
    public function testPropertyBox11()
    {
    }

    /**
     * Test attribute "box13"
     */
    public function testPropertyBox13()
    {
    }

    /**
     * Test attribute "box14"
     */
    public function testPropertyBox14()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "federal_tax_id_type"
     */
    public function testPropertyFederalTaxIdType()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "street_address"
     */
    public function testPropertyStreetAddress()
    {
    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {
    }

    /**
     * Test attribute "contact_id"
     */
    public function testPropertyContactId()
    {
    }
}
