<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'BooneEx Events';

$aLangContent = array(
    '_sbs_txt_title_bx_events' => 'Events',
    '_bx_events' => 'Events',
    '_bx_events_single' => 'event',
    '_bx_events_plural' => 'events',
    '_bx_events_action_events_home' => 'Events Home',
    '_bx_events_action_remove_from_featured' => 'Remove From Featured',
    '_bx_events_action_add_to_featured' => 'Add To Featured',
    '_bx_events_action_create_event' => 'Create Event',
    '_bx_events_action_my_events' => 'My Events',
    '_bx_events_action_title_delete' => 'Delete',
    '_bx_events_action_title_edit' => 'Edit',
    '_bx_events_action_title_invite' => 'Invite',
    '_bx_events_action_title_leave' => 'Leave',
    '_bx_events_action_title_join' => 'Join',
    '_bx_events_action_title_share' => 'Share',
    '_bx_events_action_title_broadcast' => 'Broadcast',
    '_bx_events_action_manage_fans' => 'Manage participants',
    '_bx_events_action_upload_photos' => 'Add Photos',
    '_bx_events_action_upload_videos' => 'Add Videos',
    '_bx_events_action_upload_sounds' => 'Add Sounds',
    '_bx_events_action_upload_files' => 'Add Files',
    '_bx_events_add_new_event_admin' => 'Create Event',
    '_bx_events_user_unknown' => 'Unknown',
    '_bx_events_admin' => 'admin',
    '_bx_events_admin_activate' => 'Activate',
    '_bx_events_admin_delete' => 'Delete',
    '_bx_events_admin_events' => 'Admin Events',
    '_bx_events_admin_home' => 'Home',
    '_bx_events_administration' => 'Events Administration',
    '_bx_events_administration_create_event' => 'Create Event',
    '_bx_events_administration_settings' => 'Settings',
    '_bx_events_administration_admin_events' => 'Admin Events',
    '_bx_events_all_countries' => 'All Countries',
    '_bx_events_allow_comments_all' => 'All',
    '_bx_events_allow_comments_friends' => 'Friends Only',
    '_bx_events_allow_comments_none' => 'Nobody',
    '_bx_events_allow_comments_participants' => 'Participants Only',
    '_bx_events_allow_rate_all' => 'All',
    '_bx_events_allow_rate_friends' => 'Friends Only',
    '_bx_events_allow_rate_none' => 'Nobody',
    '_bx_events_allow_rate_participants' => 'Participants Only',
    '_bx_events_calendar' => 'Calendar ',
    '_bx_events_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_join' => '<a href="{profile_link}">{profile_nick}</a> joined event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated event <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on event <a href="{entry_url}">{entry_title}</a>',

    '_bx_events_sbs_change' => 'information was updated',
    '_bx_events_sbs_comment' => 'new comment arrived',
    '_bx_events_sbs_rate' => 'rating was updated',
    '_bx_events_sbs_join' => 'new participant',

    '_bx_events_caption_add' => 'Create Event',
    '_bx_events_caption_allow_comments' => 'Allow to view and post comments',
    '_bx_events_caption_allow_rate' => 'Allow rating',
    '_bx_events_caption_allow_view_participants' => 'Allow viewinging participants',
    '_bx_events_caption_author_id' => 'Author ID',
    '_bx_events_caption_browse_by_author' => 'Browse Events By Author: ',
    '_bx_events_caption_browse_by_author_joined_events' => 'Browse Author Joined Events: ',
    '_bx_events_caption_browse_by_country' => 'Browse Events By Country: ',
    '_bx_events_caption_browse_by_category' => 'Browse Events By Category: ',
    '_bx_events_caption_browse_by_day' => 'Browse Events By Day: ',
    '_bx_events_caption_browse_by_tag' => 'Browse Events By Tag: ',
    '_bx_events_caption_browse_featured' => 'Featured Events',
    '_bx_events_caption_browse_popular' => 'Popular Events',
    '_bx_events_caption_browse_recently_added' => 'Recently Added Events',
    '_bx_events_caption_browse_top_rated' => 'Top Rated Events',
    '_bx_events_caption_browse_upcoming' => 'Upcoming Events',
    '_bx_events_caption_browse_past' => 'Past Events',
    '_bx_events_caption_city' => 'City',
    '_bx_events_caption_country' => 'Country',
    '_bx_events_caption_desc' => 'Description',
    '_bx_events_caption_edit' => 'Edit Event',
    '_bx_events_caption_event_end' => 'Date end',
    '_bx_events_caption_event_start' => 'Date start',
    '_bx_events_caption_invite' => 'Send Invitation To ',
    '_bx_events_caption_join_filter' => 'Allow to join',
    '_bx_events_caption_keyword' => 'Keyword',
    '_bx_events_caption_membership_filter' => 'Allow joining by membership',
    '_bx_events_caption_photo' => 'Photo',
    '_bx_events_caption_place' => 'Place name',
    '_bx_events_caption_search' => 'Search',
    '_bx_events_caption_search_results' => 'Search Results:',
    '_bx_events_caption_title' => 'Title',
    '_bx_events_caption_share_event' => 'Share',
    '_bx_events_caption_videos' => 'Videos',
    '_bx_events_caption_photos' => 'Photos',
    '_bx_events_caption_sounds' => 'Sounds',
    '_bx_events_caption_files' => 'Files',
    '_bx_events_caption_comments' => 'Comments',
    '_bx_events_caption_participants' => 'Participants',
    '_bx_events_caption_broadcast' => 'Broadcast message to event\'s participants',
    '_bx_events_caption_manage_fans' => 'Manage Participants',
    '_bx_events_caption_upload_photos' => 'Add Photos',
    '_bx_events_caption_upload_videos' => 'Add Videos',
    '_bx_events_caption_upload_sounds' => 'Add Sounds',
    '_bx_events_caption_upload_files' => 'Add Files',

    '_bx_events_err_allow_comments' => 'incorrect value',
    '_bx_events_err_allow_rate' => 'incorrect value',
    '_bx_events_err_allow_view_participants' => 'incorrect value',
    '_bx_events_err_city' => 'please fill in city name',
    '_bx_events_err_country' => 'please specify country',
    '_bx_events_err_desc' => 'please specify description from 20 characters',
    '_bx_events_err_event_end' => 'date format is incorrect',
    '_bx_events_err_event_start' => 'date format is incorrect',
    '_bx_events_err_join_filter' => 'incorrect value',
    '_bx_events_err_keyword' => 'please specify keyword from 3 to 100 characters',
    '_bx_events_err_membership_filter' => 'incorrect value',
    '_bx_events_err_photo' => 'please select a photo',
    '_bx_events_err_place' => 'this is a required field',
    '_bx_events_err_tags' => 'please enter at least one word which describes this event',
    '_bx_events_err_title' => 'please specify title from 3 to 100 characters',
    '_bx_events_error_occured' => 'Error Occurred',

    '_bx_events_form_header_info' => 'Event\'s Info',
    '_bx_events_form_header_privacy' => 'Event\'s Privacy Settings',

    '_bx_events_form_caption_file_title' => 'Title:',
    '_bx_events_form_header_images' => 'Event\'s Photos',
    '_bx_events_form_caption_thumb_choice' => 'Choose thumbnail',
    '_bx_events_form_info_thumb_choice' => 'You can choose any uploaded image as event thumnail',
    '_bx_events_form_caption_images_choice' => 'Choose',
    '_bx_events_form_info_images_choice' => 'Unchecked images will be deleted',
    '_bx_events_form_caption_images_upload' => 'Upload',
    '_bx_events_form_info_images_upload' => 'Image will be placed in the "Events" category automatically',

    '_bx_events_form_header_videos' => 'Event\'s Videos',
    '_bx_events_form_caption_videos_choice' => 'Choose',
    '_bx_events_form_info_videos_choice' => 'Unchecked videos will be deleted',
    '_bx_events_form_caption_videos_upload' => 'Upload',
    '_bx_events_form_info_videos_upload' => 'Video will be placed in the "Events" category automatically',

    '_bx_events_form_header_sounds' => 'Event\'s Sounds',
    '_bx_events_form_caption_sounds_choice' => 'Choose',
    '_bx_events_form_info_sounds_choice' => 'Unchecked sounds will be deleted',
    '_bx_events_form_caption_sounds_upload' => 'Upload',
    '_bx_events_form_info_sounds_upload' => 'Sound will be placed in the "Events" category automatically',

    '_bx_events_form_header_files' => 'Event\'s Files',
    '_bx_events_form_caption_files_choice' => 'Choose',
    '_bx_events_form_info_files_choice' => 'Unchecked files will be deleted',
    '_bx_events_form_caption_files_upload' => 'Upload',
    '_bx_events_form_info_files_upload' => 'File will be placed in the "Events" category automatically',

    '_bx_events_form_caption_broadcast_title' => 'Broadcast Title',
    '_bx_events_form_err_broadcast_title' => 'Please enter from 3 to 100 characters',
    '_bx_events_form_caption_broadcast_message' => 'Broadcast Message',
    '_bx_events_form_err_broadcast_message' => 'Please enter at least 10 characters',

    '_bx_events_form_caption_join_confirmation' => 'Join confirmation',
    '_bx_events_form_info_join_confirmation' => 'If enabled, event admin(s) will have to confirm each user before he/she becomes a participant.',
    '_bx_events_form_join_confirmation_disabled' => 'Disabled',
    '_bx_events_form_join_confirmation_enabled' => 'Enabled',

    '_bx_events_event_join_success' => 'You have successfully joined this event',
    '_bx_events_event_joined_already' => 'You have already joined this event',
    '_bx_events_event_join_success_pending' => 'You have successfully joined this event, please wait while your request is reviewed by event admin(s)',
    '_bx_events_event_joined_already_pending' => 'Your join request is pending approval.',
    '_bx_events_event_leave_success' => 'You have successfully left this event',
    '_bx_events_event_was_deleted' => 'Event was deleted',
    '_bx_events_info_allow_comments' => 'only these members will be able to view and post comments',
    '_bx_events_info_allow_rete' => 'only these members will be able to rate the event',
    '_bx_events_info_allow_view_participants' => 'only these members will be able to view the participants list',
    '_bx_events_info_author' => 'you can see profile\\\'s ID in admin panel member\\\'s list',
    '_bx_events_info_join_filter' => 'only these members will be able to join this event',
    '_bx_events_info_membership_filter' => 'only these members will be able to join this event',
    '_bx_events_invitation_sent' => '%d invitations have been sent',

    '_bx_events_join_all' => 'All',
    '_bx_events_join_friends_only' => 'Friends Only',
    '_bx_events_main' => 'Events',
    '_bx_events_membership_filter_none' => 'Allow All',
    '_bx_events_msg_access_denied' => 'Access Denied',
    '_bx_events_msg_page_not_found' => 'Page Not Found',
    '_bx_events_msg_pending_approval' => 'This event is pending administrator approval. Please, wait.',
    '_bx_events_msg_added_to_featured' => 'Event was added to featured',
    '_bx_events_msg_removed_from_featured' => 'Event was removed from featured',
    '_bx_events_msg_you_have_pending_approval_events' => 'You have <a href="%s">%d pending approval events</a>',
    '_bx_events_msg_you_have_no_events' => 'You have not added any events. <a href="%s">Click here</a> to add one.',
    '_bx_events_msg_you_have_some_events' => 'You have <a href="%s">%d event(s)</a>. <a href="%s">Click here</a> to add more.',
    '_bx_events_msg_broadcast_no_participants' => 'This event has no participants yet',
    '_bx_events_msg_broadcast_message_sent' => 'Broadcast message has been successfully sent',
    '_bx_events_no_users_msg' => 'There are no users in your contacts',
    '_bx_events_pending_approval' => 'Pending Approval',
    '_bx_events_photo_is_pending_approval' => 'Photo is pending approval. Please be patient.',
    '_bx_events_settings_admin' => 'Settings',

    '_bx_events_privacy_view_event' => 'View Event',
    '_bx_events_privacy_join' => 'Allow joining',
    '_bx_events_privacy_comment' => 'Allow to view and post comments',
    '_bx_events_privacy_rate' => 'Allow rating',
    '_bx_events_privacy_view_participants' => 'Allow viewing participants',
    '_bx_events_privacy_post_in_forum' => 'Allow posting in forum',
    '_bx_events_privacy_participants_only' => 'Participants only',
    '_bx_events_privacy_participants' => 'Participants',
    '_bx_events_privacy_admins_only' => 'Admins Only',
    '_bx_events_privacy_upload_photos' => 'Upload Photos',
    '_bx_events_privacy_upload_videos' => 'Upload Videos',
    '_bx_events_privacy_upload_sounds' => 'Upload Sounds',
    '_bx_events_privacy_upload_files' => 'Upload Files',

    '_bx_events_tags' => 'Events Tags',
    '_bx_events_categories' => 'Events Categories',
    '_bx_events_view_participants_all' => 'All',
    '_bx_events_view_participants_friends' => 'Friends Only',
    '_bx_events_view_participants_none' => 'Nobody',

    '_bx_events_block_actions' => 'Actions',
    '_bx_events_block_info' => 'Information',
    '_bx_events_block_desc' => 'Description',
    '_bx_events_block_participants' => 'Participants',
    '_bx_events_block_participants_unconfirmed' => 'Unconfirmed Participants',
    '_bx_events_block_photos' => 'Photos',
    '_bx_events_block_videos' => 'Videos',
    '_bx_events_block_sounds' => 'Sounds',
    '_bx_events_block_files' => 'Files',
    '_bx_events_block_rate' => 'Rate',
    '_bx_events_block_comments' => 'Comments',
    '_bx_events_block_calendar' => 'Events Calendar ',
    '_bx_events_block_upcoming_photo' => 'Upcoming Public Event',
    '_bx_events_block_upcoming_list' => 'Upcoming Public Events',
    '_bx_events_block_past_list' => 'Past Public Events',
    '_bx_events_block_recently_added_list' => 'Recently Added Public Events',
    '_bx_events_block_my_events' => 'My Events',
    '_bx_events_block_joined_events' => 'Joined Events',
    '_bx_events_block_administration' => 'Administration',
    '_bx_events_block_user_events' => 'My Events',
    '_bx_events_block_home' => 'Public Events',

    '_bx_events_block_submenu_main' => 'Main',
    '_bx_events_block_submenu_add' => 'Add',
    '_bx_events_block_submenu_manage' => 'Manage',
    '_bx_events_block_submenu_pending' => 'Pending Approval',

    '_bx_events_menu_root' => 'Events',
    '_bx_events_menu_main' => 'Events Home',
    '_bx_events_menu_upcoming_events' => 'Upcoming',
    '_bx_events_menu_past_events' => 'Past',
    '_bx_events_menu_recently_added' => 'Recently Added',
    '_bx_events_menu_featured' => 'Featured',
    '_bx_events_menu_my_events' => 'My Events',
    '_bx_events_menu_my_events_profile' => 'Events',
    '_bx_events_menu_my_pending_events' => 'Pending Approval',
    '_bx_events_menu_calendar' => 'Calendar',
    '_bx_events_menu_popular' => 'Popular',
    '_bx_events_menu_search' => 'Search',
    '_bx_events_menu_tags' => 'Tags',
    '_bx_events_menu_categories' => 'Categories',
    '_bx_events_menu_top_rated' => 'Top Rated',
    '_bx_events_menu_add' => 'Create Event',
    '_bx_events_menu_view' => 'Main',
    '_bx_events_menu_view_forum' => 'Forum',
    '_bx_events_menu_view_comments' => 'Comments',
    '_bx_events_menu_view_participants' => 'Participants',
    '_bx_events_menu_view_photos' => 'Photos',
    '_bx_events_menu_view_videos' => 'Videos',
    '_bx_events_menu_view_sounds' => 'Sounds',
    '_bx_events_menu_view_files' => 'Files',

    '_bx_events_tab_recent' => 'Recently Added',
    '_bx_events_tab_upcoming' => 'Upcoming',
    '_bx_events_tab_featured' => 'Featured',
    '_bx_events_tab_top' => 'Top',
    '_bx_events_tab_popular' => 'Popular',

    '_bx_event_wall_added_new' => 'added new',
    '_bx_event_wall_object' => 'event',

    '_bx_events_announce' => 'announce',

    '_mma_events_view' => 'events view',
    '_mma_events_browse' => 'events browse',
    '_mma_events_search' => 'events search',
    '_mma_events_add' => 'events add',
    '_mma_events_comments_delete_and_edit' => 'events comments delete and edit',
    '_mma_events_edit_any_event' => 'events edit any event',
    '_mma_events_delete_any_event' => 'events delete any event',
    '_mma_events_mark_as_featured' => 'events marked as featured',
    '_mma_events_approve' => 'events approve',
    '_mma_events_broadcast_message' => 'events broadcast message',
);

?>
