<?php

$aFilesDelete = array(
    'modules/base/text/template/account_link.html',
    'plugins/stripe/lib/Error',
    'plugins/stripe/lib/Util/AutoPagingIterator.php',
    'plugins/stripe/lib/FileUpload.php',
    'plugins/stripe/lib/IssuerFraudRecord.php',
    'plugins/stripe/.coveralls.yml',
    'plugins/stripe/.travis.yml',
    'plugins/stripe/phpunit.no_autoload.xml',
    'plugins/stripe/phpunit.xml',
    'studio/js/designs.js',
    'studio/js/languages.js',
    'studio/js/modules.js',
    'studio/template/css/designs.css',
    'studio/template/css/languages.css',
    'studio/template/css/modules.css',
    'studio/template/images/bx-std-bg-columns.png',
    'studio/template/dsn_js.html',
    'studio/template/lang_js.html',
    'studio/template/mod_action_result.html',
    'studio/template/mod_confirm.html',
    'studio/template/mod_js.html',
    'studio/languages.php',
    'studio/modules.php',
    'studio/templates.php',
    'template/images/icons/favicon.png',
    'template/form_field_location.html',
    'template/metatags_locations_map.html',
);

